---
title: "PBN RCT"
author: "Arielle Smith"
date: "2024-04-24"
output:
  html_document: default
  pdf_document: default
---

```{r working directory}
knitr::opts_knit$set(root.dir = "/Volumes/fsmresfiles/MSS/Schleider_Lab/jslab/Project Body Neutrality/RCT/Data/Full Sample (Baseline and Follow-Up)")
setwd("/Volumes/fsmresfiles/MSS/Schleider_Lab/jslab/Project Body Neutrality/RCT/Data/Full Sample (Baseline and Follow-Up)")
```

```{r load packages and data}
#Load required packages
if(!require(tidyverse)){install.packages('tidyverse')}
library(tidyverse)
if(!require(lmtest)){install.packages('lmtest')}
library(lmtest)
if(!require(car)){install.packages('car')}
library(car)
if(!require(olsrr)){install.packages('olsrr')}
library(olsrr)
if(!require(sandwich)){install.packages('sandwich')}
library(sandwich)
if(!require(MOTE)){install.packages('MOTE')}
library(MOTE)
if(!require(openxlsx)){install.packages('openxlsx')}
library(openxlsx)
if(!require(missForest)){install.packages('missForest')}
library(missForest)
if(!require(visdat)){install.packages('visdat')}
library(visdat)
if(!require(qualtRics)){install.packages('qualtRics')}
library(qualtRics)
if(!require(readxl)){install.packages('readxl')}
library(readxl)

#Load data - #Using the .cols argument because otherwise some variables that should not be numeric are imported as such (e.g.,  demographics)
original_baseline_survey_data <- read_survey("/Volumes/fsmresfiles/MSS/Schleider_Lab/jslab/Project Body Neutrality/RCT/Data/Full Sample (Baseline and Follow-Up)/original_baseline_survey_data.csv",  col_types = cols(.default = "c"))
new_baseline_survey_data <- read_survey("/Volumes/fsmresfiles/MSS/Schleider_Lab/jslab/Project Body Neutrality/RCT/Data/Full Sample (Baseline and Follow-Up)/new_baseline_survey_data.csv",  col_types = cols(.default = "c"))
followup_data <- read_survey("/Volumes/fsmresfiles/MSS/Schleider_Lab/jslab/Project Body Neutrality/RCT/Data/Full Sample (Baseline and Follow-Up)/followup_survey_data.csv",  col_types = cols(.default = "c")) 
participant_database <- read.csv(
  "/Volumes/fsmresfiles/MSS/Schleider_Lab/jslab/Project Body Neutrality/RCT/Data/Full Sample (Baseline and Follow-Up)/participant_database.csv",
  stringsAsFactors = FALSE,
  colClasses = "character")
```

```{r merge data}
#Merge original_baseline_survey_data (closed because of frauds) and new_baseline_survey_data

#original_baseline_survey_data has 731 columns but new_baseline_survey_data has 729. Figure out the 2 differences
cols_in_original_only <- setdiff(names(original_baseline_survey_data),  names(new_baseline_survey_data))
print(cols_in_original_only)

#Remove the 2 extra Qualtrics columns from original_baseline_survey_data (won't mess things up because they are at the end and don't have anything important)
original_baseline_survey_data <- original_baseline_survey_data %>%
  select(-Q_AmbiguousTextPresent,  -Q_AmbiguousTextQuestions)

#Now we can merge
merged_baseline_data <- bind_rows(original_baseline_survey_data,  new_baseline_survey_data)

#Drop columns with no Participant IDs (they did not get far enough to get assigned an ID) 
merged_baseline_data <- merged_baseline_data %>%
  filter(!is.na(Participant_ID))

#Now, we need to make sure that the participant database gets linked to the baseline data which it draws from
merged_participant_database_baseline_data <- participant_database %>% 
  left_join(merged_baseline_data, by = "Participant_ID")

#We also need to merge with the follow-up data, accounting for duplicates (people that submitted follow-ups multiple times)
followup_data <- followup_data %>%
  group_by(Participant_ID) %>%
  arrange(desc(Progress),  RecordedDate) %>%
  slice(1)

all_data <- merged_participant_database_baseline_data %>% 
  left_join(followup_data,  by = "Participant_ID")
```

```{r transform data}
#The gender and race/ethnicity items include all responses from the multiple-select questions in one column. I need to separate them out in order to make them factors.

#First focus on transforming gender
transforming_gender <- all_data %>% 
  select(b_dem_gender, Participant_ID) %>%
  separate_rows(b_dem_gender, sep = ",") %>%
  pivot_wider(
    names_from = b_dem_gender,
    values_from = b_dem_gender,
    values_fill = list(b_dem_gender = "0")) %>%
  mutate(across(-Participant_ID, ~ as.factor(as.numeric(. != "0")))) %>% 
  rename_with(~ str_c("b_dem_gender_", .), -Participant_ID)

#Now focus on transforming race/ethnicity
transforming_race_ethnicity <- all_data %>% 
  select(b_dem_race_ethnicity, Participant_ID) %>%
  separate_rows(b_dem_race_ethnicity, sep = ",") %>%
  pivot_wider(
    names_from = b_dem_race_ethnicity,
    values_from = b_dem_race_ethnicity,
    values_fill = list(b_dem_race_ethnicity = "0")) %>%
  mutate(across(-Participant_ID, ~ as.factor(as.numeric(. != "0")))) %>% 
  rename_with(~ str_c("b_dem_race_ethnicity_", .), -Participant_ID)

all_data <- all_data %>%
  left_join(transforming_gender, by = "Participant_ID") %>%
  left_join(transforming_race_ethnicity, by = "Participant_ID") %>%
  select(-b_dem_gender, -b_dem_race_ethnicity)

#Now I need to make all other appropriate variables into factors
all_data <- all_data %>% 
  mutate(across(.cols = c(b_dem_saab, b_dem_sexuality, b_dem_sex, b_current_mood, b_past_px, b_past_mood, b_unmet_mood_now, b_unmet_mood_past, b_current_ed, b_past_ed, b_unmet_ed_now, b_unmet_ed_past, b_hunger_1, b_hunger_2, f_new_support_mood, f_new_support_ed), as.factor))

#And I need to make all necessary variables numeric
all_data <- all_data %>% mutate(across(c(pi_pfs_1:pi_pfs_7,  starts_with("b_dem_age"),  starts_with("b_bhs"),  starts_with("b_shs_agency"), starts_with("b_biss"),  starts_with("b_fas"),  starts_with("b_biaaq"),   starts_with("b_chime"),  starts_with("b_mfq"),  starts_with("b_edeq"),  starts_with("b_mddi"),  starts_with("pi_bhs"),  starts_with("pi_shs_agency"),  starts_with("pi_biss"),  starts_with("pi_fas"),  starts_with("pi_biaaq"),  starts_with("pi_chime"),  starts_with("f_bhs"),  starts_with("f_shs_agency"),  starts_with("f_biss"),  starts_with("f_fas"),  starts_with("f_biaaq"), starts_with("f_chime"),  starts_with("f_mfq"),  starts_with("f_edeq"),  starts_with("f_mddi")),  
                as.numeric))

#Create a binary variable to identify the treatment group
all_data <- all_data %>%
  mutate(
    treatment_group = factor(Condition.y == "Intervention", 
                             levels = c(FALSE, TRUE), 
                             labels = c("Control", "Intervention")))

#Create a binary variable to identify if participants completed the intervention condition
all_data <- all_data %>%
  mutate(
    intervention_completed = factor("Intervention Completed" == "Intervention Completed", 
                                    levels = c(TRUE, FALSE), 
                                    labels = c("Completed", "Not Completed")))

#Create a binary variable to identify if participants completed the control condition
all_data <- all_data %>%
  mutate(
    control_completed = factor("Control Completed" == "Control", 
                               levels = c(TRUE, FALSE), 
                               labels = c("Completed", "Not Completed")))
```

```{r create sum scores}
#All relevant items are already reverse-scored in Qualtrics
all_data <- all_data %>%
  mutate(b_bhs_sum = b_bhs_1 + b_bhs_2 + b_bhs_3 + b_bhs_4, 
         pi_bhs_sum = pi_bhs_1 + pi_bhs_2 + pi_bhs_3 + pi_bhs_4, 
         f_bhs_sum = f_bhs_1 + f_bhs_2 + f_bhs_3 + f_bhs_4, 
         b_shs_agency_sum = b_shs_agency_1 + b_shs_agency_2 + b_shs_agency_3, 
         pi_shs_agency_sum = pi_shs_agency_1 + pi_shs_agency_2 + pi_shs_agency_3, 
         f_shs_agency_sum = f_shs_agency_1 + f_shs_agency_2 + f_shs_agency_3, 
         b_biss_sum = b_biss_1 + b_biss_2 + b_biss_3 + b_biss_4 +  b_biss_5 + b_biss_6, 
         pi_biss_sum = pi_biss_1 + pi_biss_2 + pi_biss_3 + pi_biss_4 +  pi_biss_5 + pi_biss_6, 
         f_biss_sum = f_biss_1 + f_biss_2 + f_biss_3 + f_biss_4 +  f_biss_5 + f_biss_6, 
         b_fas_sum = b_fas_1 + b_fas_2 + b_fas_3 + b_fas_4 + b_fas_5 + b_fas_6 + b_fas_7, 
         pi_fas_sum = pi_fas_1 + pi_fas_2 + pi_fas_3 + pi_fas_4 + pi_fas_5 + pi_fas_6 + pi_fas_7, 
         f_fas_sum = f_fas_1 + f_fas_2 + f_fas_3 + f_fas_4 + f_fas_5 + f_fas_6 + f_fas_7, 
         b_biaaq_sum = b_biaaq_1 + b_biaaq_2 + b_biaaq_3 + b_biaaq_4 + b_biaaq_5 + b_biaaq_6 + b_biaaq_7 + b_biaaq_8 + b_biaaq_9 + b_biaaq_10 + b_biaaq_11 + b_biaaq_12, 
         pi_biaaq_sum = pi_biaaq_1 + pi_biaaq_2 + pi_biaaq_3 + pi_biaaq_4 + pi_biaaq_5 + pi_biaaq_6 + pi_biaaq_7 + pi_biaaq_8 + pi_biaaq_9 + pi_biaaq_10 + pi_biaaq_11 + pi_biaaq_12,  
        f_biaaq_sum = f_biaaq_1 + f_biaaq_2 + f_biaaq_3 + f_biaaq_4 + f_biaaq_5 + f_biaaq_6 + f_biaaq_7 + f_biaaq_8 + f_biaaq_9 + f_biaaq_10 + f_biaaq_11 + f_biaaq_12, 
         b_chime_sum = b_chime_1 + b_chime_2 + b_chime_3, 
         pi_chime_sum = pi_chime_1 + pi_chime_2 + pi_chime_3, 
         f_chime_sum = f_chime_1 + f_chime_2 + f_chime_3, 
         pi_pfs_sum = pi_pfs_1 + pi_pfs_2 + pi_pfs_3 + pi_pfs_4 + pi_pfs_5 + pi_pfs_6 + pi_pfs_7, 
         b_mfq_sum = b_mfq_1 + b_mfq_2 + b_mfq_3 + b_mfq_4 + b_mfq_5 + b_mfq_6 + b_mfq_7 + b_mfq_8 + b_mfq_9 + b_mfq_10 + b_mfq_11 + b_mfq_12 + b_mfq_13,  
         f_mfq_sum = f_mfq_1 + f_mfq_2 + f_mfq_3 + f_mfq_4 + f_mfq_5 + f_mfq_6 + f_mfq_7 + f_mfq_8 + f_mfq_9 + f_mfq_10 + f_mfq_11 + f_mfq_12 + f_mfq_13, 
         b_edeq_sum = b_edeq_1 + b_edeq_2 + b_edeq_3 + b_edeq_4 + b_edeq_5 + b_edeq_6 + b_edeq_7 + b_edeq_8 + b_edeq_9 + b_edeq_10, 
         f_edeq_sum = f_edeq_1 + f_edeq_2 + f_edeq_3 + f_edeq_4 + f_edeq_5 + f_edeq_6 + f_edeq_7 + f_edeq_8 + f_edeq_9 + f_edeq_10,  
         b_mddi_sum = b_mddi_1 + b_mddi_2 + b_mddi_3 + b_mddi_4 + b_mddi_5 + b_mddi_6 + b_mddi_7 + b_mddi_8 + b_mddi_9 + b_mddi_10 + b_mddi_11 + b_mddi_12 + b_mddi_13, 
         f_mddi_sum = f_mddi_1 + f_mddi_2 + f_mddi_3 + f_mddi_4 + f_mddi_5 + f_mddi_6 + f_mddi_7 + f_mddi_8 + f_mddi_9 + f_mddi_10 + f_mddi_11 + f_mddi_12 + f_mddi_13) 
```

```{r handling missing data}
#Identify participants with greater than 5% missing baseline primary outcomes data
#For each participant,  add a new column that calculates the percent missing of baseline primary outcome items
all_data <- all_data %>%
  mutate(percent_missing = rowMeans(
    is.na(select(all_data,  b_mfq_1,  b_mfq_2,  b_mfq_3,  b_mfq_4,  b_mfq_5,  b_mfq_6,  b_mfq_7,  b_mfq_8,  b_mfq_9,  b_mfq_10,  b_mfq_11,  b_mfq_12,  b_mfq_13,  b_edeq_1,  b_edeq_2,  b_edeq_3,  b_edeq_4,  b_edeq_5,  b_edeq_6,  b_edeq_7,  b_edeq_8,  b_edeq_9,  b_edeq_10)),  
    na.rm = TRUE)) %>%
  mutate(percent_missing = percent_missing * 100)

#Make a new variable that identifies participants with more than 5% missing data (those with more than 5% missing are TRUE)
all_data <- all_data %>%
  mutate(more_than_5_percent_missing = percent_missing > 5)
#Remove participants where more_than_5_percent_missing is TRUE
all_data <- all_data %>%
  filter(!more_than_5_percent_missing)
```

```{r sample breakdowns}
#Some of this code is to build dataframes for specific analyses, but a lot of it is for a CONSORT diagram and to double check that the study workflow went as planned

#Participants who submitted the baseline, were compensated, and passed data integrity checks
completer_baseline <- all_data %>% 
  filter(Include.in.Analysis == "Yes" & Compensation.Date != "N/A")  
nrow(completer_baseline)
#N=191

#Participants who submitted the baseline, were compensated, and passed data integrity checks - from the intervention group
completer_baseline_intervention <- completer_baseline %>% 
  filter(Condition.y == "Intervention")
nrow(completer_baseline_intervention)
#N=96
  
#Participants who submitted the baseline, were compensated, and passed data integrity checks - from the control group
completer_baseline_control <- completer_baseline %>% 
  filter(Condition.y == "Control")
nrow(completer_baseline_control)
#N=95

#Participants who got randomized and passed data integrity checks but did not get compensated (due to baseline incomplete)
incomplete_baseline <- all_data %>% 
  filter(Measures.Complete == "No" & Include.in.Analysis == "Yes")
nrow(incomplete_baseline)
#N=27

#Participants who got randomized and passed the data integrity checks (regardless of intervention or baseline completion)
randomized <- bind_rows(completer_baseline,  incomplete_baseline)
nrow(randomized)
#N=218

#Participants who got randomized, passed data integrity checks, and completed their intervention
completer_intervention <- all_data %>% 
  filter(`Intervention Completed` == "Intervention Completed" | `Control Completed` == "Control Completed")  %>%
  semi_join(randomized,  by = "Participant_ID")
nrow(completer_intervention)
#N=204

#Participants who got randomized, passed data integrity checks, and did not completed their intervention
incomplete_intervention <- all_data %>%
  filter((`Condition.y` == "Intervention" & (is.na(`Intervention Completed`) | `Intervention Completed` != "Intervention Completed")) | (`Condition.y` == "Control" & (is.na(`Control Completed`) | `Control Completed` != "Control Completed"))) %>%
  semi_join(randomized,  by = "Participant_ID")
nrow(incomplete_intervention)
#N=14

#Intervention group participants who passed data integrity checks (regardless of completion)
randomized_intervention <- randomized  %>%
  filter(Condition.y == "Intervention")
nrow(randomized_intervention)
#N=103

#Control group participants who passed data integrity checks (regardless of completion)
randomized_control <- randomized  %>%
  filter(Condition.y == "Control")
nrow(randomized_control)
#N=115

#Intervention group participants who passed data integrity checks and completed their intervention
randomized_intervention_complete <- randomized_intervention %>%
  semi_join(completer_intervention %>% select(Participant_ID), by = "Participant_ID")
nrow(randomized_intervention_complete)
#N=99

#Control group participants who passed data integrity checks and completed their intervention
randomized_control_complete <- randomized_control %>%
  semi_join(completer_intervention %>% select(Participant_ID), by = "Participant_ID")
nrow(randomized_control_complete)
#N=105

#Intervention group participants who passed data integrity checks, completed their intervention, and completed the PFS (for qual and PFS analyses)
randomized_intervention_pfs_complete <- randomized_intervention_complete %>% 
  filter(!is.na(pi_pfs_sum))
nrow(randomized_intervention_pfs_complete)
#N=97

#Control group participants who passed data integrity checks, completed their intervention, and completed the PFS (for PFS analyses)
randomized_control_pfs_complete <- randomized_control_complete %>% 
  filter(!is.na(pi_pfs_sum))
nrow(randomized_intervention_pfs_complete)
#N=97

#Intervention group participants who passed data integrity checks and did not complete their intervention
randomized_intervention_incomplete <- randomized_intervention %>%
  semi_join(incomplete_intervention %>% select(Participant_ID), by = "Participant_ID")
nrow(randomized_intervention_incomplete)
#N=4

#Control group participants who passed data integrity checks and did not complete their intervention
randomized_control_incomplete <- randomized_control %>%
  semi_join(incomplete_intervention %>% select(Participant_ID), by = "Participant_ID")
nrow(randomized_control_incomplete)
#N=10

#Participants who received follow-up emails (have to hard code based on the listservs we created manually)
invited_followup <- all_data %>%
 filter(Participant_ID %in% c(69913, 93022, 76432, 75263, 56815, 17052, 13023, 72038, 48022, 22684, 56590, 13302, 21313, 57955, 68198, 64531, 16855, 17670, 20364, 49102, 63743, 48593, 96225, 97410, 71632, 90795, 44268, 62193, 85350, 11827, 93664, 78161, 42215, 50466, 29614, 41799, 87127, 15065, 20973, 38572, 13638, 26776, 86023, 35047, 25638, 65863, 99374, 43295, 88046, 77450, 53220, 86114, 73614, 80888, 86314, 55845, 81514, 92289, 22584, 38538, 64719, 19199, 78881, 96320, 26869, 65509, 49236, 23158, 49034, 76870, 78040, 21842, 54988, 48970, 87771, 77719, 86763, 32309, 85344, 85411, 33280, 47331, 93980, 50401, 96007, 65187, 72626, 64019, 31188, 43258, 99949, 80941, 15777, 53969, 95004, 68267, 35553, 67236, 88241, 11868, 55765, 66912, 39606, 95389, 17032, 62781, 53863, 60501, 27455, 90947, 86804, 18348, 38488, 45565, 86300, 48031, 19978, 25643, 25987, 71511, 84417, 56534, 84267, 98233, 45789, 68200, 76371, 17149, 39743, 31067, 21592, 59978, 70500, 66920, 53611, 57517, 11308, 89229, 49864, 24314, 69311, 47321, 35067, 43097, 38601, 26551, 15025, 69898, 74462, 96711, 49908, 77121, 74951, 58830, 11290, 60126, 82287, 40376, 98726, 66481, 90314, 83329, 63962, 80569, 75164, 65322, 41917, 64886, 31849, 71675, 96986, 72424, 20457, 30277, 68213, 93863, 33504, 50884, 48434, 14806, 18169, 92104, 38713, 56049, 74139, 93764, 28301, 39455, 18974, 15333, 49399, 45841, 86883, 57712, 18856, 58650, 70371, 53775, 13842, 35756, 52326, 40397, 14617, 17231, 96120, 95674, 62516, 22485, 21140, 58776, 40077, 15186, 16432, 83679, 13649, 61437, 11697, 24378, 84608, 40889))
nrow(invited_followup)
#N=218

#Participants who completed the follow-up
completer_followup <- all_data %>%
  filter(Follow.Up.Completion == "Yes") %>% 
  filter(!if_any(contains("sum"), is.na))
nrow(completer_followup)
#N=107

#Participants who completed the follow-up - from the intervention group
completer_followup_intervention <- completer_followup %>% 
  filter(Condition.y == "Intervention")
nrow(completer_followup_intervention)
#N=49

#Participants who completed the follow-up - from the control group
completer_followup_control <- completer_followup %>% 
  filter(Condition.y == "Control")
nrow(completer_followup_control)
#N=58

#Participants who did not complete the follow-up
incomplete_followup <- all_data %>%
  filter(Follow.Up.Completion != "Yes" & Include.in.Analysis == "Yes")
nrow(incomplete_followup)
#N=99

#Participants who were randomized but did not complete their intervention who did end up completing their follow-up
incomplete_intervention_completer_followup <- incomplete_intervention %>%
  semi_join(completer_followup %>% select(Participant_ID), by = "Participant_ID")
nrow(incomplete_intervention_completer_followup)
#N=1

#Participants who were randomized but did not complete their intervention who did not complete their follow-up
incomplete_intervention_incomplete_followup <- incomplete_intervention %>%
  semi_join(incomplete_followup %>% select(Participant_ID), by = "Participant_ID")
nrow(incomplete_intervention_incomplete_followup)
#N=13
```

```{r make seperate dataframes for quant data}
#Dataframe for quantitative analysis (randomized)
randomized_quant <- randomized %>%
   select(treatment_group,  intervention_completed,  starts_with(c("b_dem",  "b_current",  "b_past",  "b_unmet",  "b_hunger",  "b_bhs",  "b_shs_agency",  "b_biss",  "b_fas",  "b_biaaq",  "b_chime",  "b_mfq",  "b_edeq",  "b_mddi",  "pi_pfs",  "pi_bhs",  "pi_shs_agency",  "pi_biss",  "pi_fas",  "pi_biaaq",  "pi_chime",  "f_new",  "f_bhs",  "f_shs_agency",  "f_biss",  "f_fas",  "f_biaaq",  "f_chime",  "f_mfq",  "f_edeq",  "f_mddi"))) %>%
  select(-contains("free"),  -contains("TEXT"),  -contains("_tim_"),  -contains("pfs_like"),  -contains("pfs_change"),  -contains("pfs_other"), -contains("percent_missing")) 

#Dataframe for quantitative analysis (completer_intervention)
completer_intervention_quant <- completer_intervention %>%
   select(treatment_group,  intervention_completed,  starts_with(c("b_dem",  "b_current",  "b_past",  "b_unmet",  "b_hunger",  "b_bhs",  "b_shs_agency",  "b_biss",  "b_fas",  "b_biaaq",  "b_chime",  "b_mfq",  "b_edeq",  "b_mddi",  "pi_pfs",  "pi_bhs",  "pi_shs_agency",  "pi_biss",  "pi_fas",  "pi_biaaq",  "pi_chime",  "f_new",  "f_bhs",  "f_shs_agency",  "f_biss",  "f_fas",  "f_biaaq",  "f_chime",  "f_mfq",  "f_edeq",  "f_mddi"))) %>%
  select(-contains("free"),  -contains("TEXT"),  -contains("_tim_"),  -contains("pfs_like"),  -contains("pfs_change"),  -contains("pfs_other"), -contains("percent_missing")) 

#Dataframe for quantitative analysis (completer_baseline)
completer_baseline_quant <- completer_baseline %>%
   select(treatment_group,  intervention_completed,  starts_with(c("b_dem",  "b_current",  "b_past",  "b_unmet",  "b_hunger",  "b_bhs",  "b_shs_agency",  "b_biss",  "b_fas",  "b_biaaq",  "b_chime",  "b_mfq",  "b_edeq",  "b_mddi",  "pi_pfs",  "pi_bhs",  "pi_shs_agency",  "pi_biss",  "pi_fas",  "pi_biaaq",  "pi_chime",  "f_new",  "f_bhs",  "f_shs_agency",  "f_biss",  "f_fas",  "f_biaaq",  "f_chime",  "f_mfq",  "f_edeq",  "f_mddi"))) %>%
  select(-contains("free"),  -contains("TEXT"),  -contains("_tim_"),  -contains("pfs_like"),  -contains("pfs_change"),  -contains("pfs_other"), -contains("percent_missing")) 

#Dataframe for quantitative analysis (completed_followup)
completer_followup_quant <- completer_followup %>%
   select(treatment_group,  intervention_completed,  starts_with(c("b_dem",  "b_current",  "b_past",  "b_unmet",  "b_hunger",  "b_bhs",  "b_shs_agency",  "b_biss",  "b_fas",  "b_biaaq",  "b_chime",  "b_mfq",  "b_edeq",  "b_mddi",  "pi_pfs",  "pi_bhs",  "pi_shs_agency",  "pi_biss",  "pi_fas",  "pi_biaaq",  "pi_chime",  "f_new",  "f_bhs",  "f_shs_agency",  "f_biss",  "f_fas",  "f_biaaq",  "f_chime",  "f_mfq",  "f_edeq",  "f_mddi"))) %>%
  select(-contains("free"),  -contains("TEXT"),  -contains("_tim_"),  -contains("pfs_like"),  -contains("pfs_change"),  -contains("pfs_other"), -contains("percent_missing")) 
```

```{r extract data for qual analysis}
#Dataframe for qualitative analysis (intervention completers with PFS data)
qual_data <- randomized_intervention_pfs_complete %>%
 select(Participant_ID, pi_pfs_like, pi_pfs_change, pi_pfs_other)

#Table export (only run again if file gets deleted)
#flextable::flextable(qual_data,  cwidth = c(0.5, 7, 0.5))
#write.xlsx(qual_data,  "pfs_qual_intervention.xlsx")
```

```{r imputation}
#set.seed(12345) #use the same seed number each time to make the code reproducible (the seed number is just the starting point used in the generation of a sequence of random numbers in the random forest)

#For randomized
#imputed_randomized_quant <- missForest(randomized_quant)
#imputed_randomized_quant_error <- as.data.frame(imputed_randomized_quant$OOBerror)
#imputed_randomized_quant <- as.data.frame(imputed_randomized_quant$ximp)
#randomized_quant <- round(randomized_quant) #Since the algorithm introduces decimals which is not appropriate for this data,  round to the nearest whole number. UPDATE FROM ISAAC: It may actually make sense to include decimals - discuss this. 
#write.csv(imputed_randomized_quant,file='imputed_randomized_quant.csv')

#For completer_intervention
#imputed_completer_intervention_quant <- missForest(completer_intervention_quant)
#imputed_completer_intervention_quant_error <- as.data.frame(imputed_completer_intervention_quant$OOBerror)
#imputed_completer_intervention_quant <- as.data.frame(imputed_completer_intervention_quant$ximp)
#completer_intervention_quant <- round(completer_intervention_quant) #Since the algorithm introduces decimals which is not appropriate for this data,  round to the nearest whole number. UPDATE FROM ISAAC: It may actually make sense to include decimals - discuss this. 
#write.csv(imputed_completer_intervention_quant,file='imputed_completer_intervention_quant.csv')

#For completer_baseline
#imputed_completer_baseline_quant <- missForest(completer_baseline_quant)
#imputed_completer_baseline_quant_error <- as.data.frame(imputed_completer_baseline_quant$OOBerror)
#imputed_completer_baseline_quant <- as.data.frame(imputed_completer_baseline_quant$ximp)
#completer_baseline_quant <- round(completer_baseline_quant) #Since the algorithm introduces decimals which is not appropriate for this data,  round to the nearest whole number. UPDATE FROM ISAAC: It may actually make sense to include decimals - discuss this. 
#write.csv(imputed_completer_baseline_quant,file='imputed_completer_baseline_quant.csv')
```

```{r load imputed data}
imputed_randomized_quant <- read.csv("imputed_randomized_quant.csv")
imputed_completer_intervention_quant <- read.csv("imputed_completer_intervention_quant.csv")
imputed_completer_baseline_quant <- read.csv("imputed_completer_baseline_quant.csv")
```

```{r descriptives of outcomes using ITT sample (imputed)}
descriptives <- imputed_randomized_quant %>%
  group_by(treatment_group) %>%
  summarize(across(c(b_bhs_sum,  pi_bhs_sum,  f_bhs_sum, b_shs_agency_sum,  pi_shs_agency_sum,  f_shs_agency_sum, b_biss_sum,  pi_biss_sum, f_biss_sum,  b_fas_sum,  pi_fas_sum,  f_fas_sum, b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum, b_chime_sum,  pi_chime_sum,  f_chime_sum, pi_pfs_sum),  
                   list(mean = mean,  sd = sd)))
print(descriptives)
```

```{r primary analysis 1 - ITT}
#Hopelessness pre-post
lm_bhs_itt_1 <- lm(pi_bhs_sum ~ b_bhs_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_bhs_itt_1)
coefci(lm_bhs_itt_1)
#Significant effect of treatment_group (p<0.001) in the expected direction (negative)

#Hopelessness pre-followup
lm_bhs_itt_2 <- lm(f_bhs_sum ~ b_bhs_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_bhs_itt_2)
coefci(lm_bhs_itt_2)
#Significant effect of treatment_group (p<0.05) in the expected direction (negative)

#Agency pre-post
lm_shs_agency_itt_1 <- lm(pi_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_shs_agency_itt_1)
coefci(lm_shs_agency_itt_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.01) in the expected direction (positive)

#Agency pre-followup
lm_shs_agency_itt_2 <- lm(f_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_shs_agency_itt_2)
coefci(lm_shs_agency_itt_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body image state pre-post
lm_biss_itt_1 <- lm(pi_biss_sum ~ b_biss_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_biss_itt_1)
coefci(lm_biss_itt_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.001) in the expected direction (positive)

#Body image state pre-followup
lm_biss_itt_2 <- lm(f_biss_sum ~ b_biss_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_biss_itt_2)
coefci(lm_biss_itt_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Functionality appreciation pre-post
lm_fas_itt_1 <- lm(pi_fas_sum ~ b_fas_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_fas_itt_1)
coefci(lm_fas_itt_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.001) in the expected direction (positive)

#Functionality appreciation pre-followup
lm_fas_itt_2 <- lm(f_fas_sum ~ b_fas_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_fas_itt_2)
coefci(lm_fas_itt_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body image flexibility pre-post - EXPLORATORY
lm_biaaq_itt_1 <- lm(pi_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_biaaq_itt_1)
coefci(lm_biaaq_itt_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.01) in the expected direction (positive)

#Body image flexibility pre-followup - EXPLORATORY
lm_biaaq_itt_2 <- lm(f_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_biaaq_itt_2)
coefci(lm_biaaq_itt_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body-related mindfulness pre-post - EXPLORATORY
lm_chime_itt_1 <- lm(pi_chime_sum ~ b_chime_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_chime_itt_1)
coefci(lm_chime_itt_1,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body-related mindfulness pre-followup - EXPLORATORY
lm_chime_itt_2 <- lm(f_chime_sum ~ b_chime_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_chime_itt_2)
coefci(lm_chime_itt_2,  vcov = sandwich)
#Significant effect of treatment_group (p<0.01) in the expected direction (positive)

#Depression symptoms pre-followup
lm_mfq_itt <- lm(f_mfq_sum ~ b_mfq_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_mfq_itt)
coefci(lm_mfq_itt,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Eating disorder symptoms pre-followup
lm_edeq_itt <- lm(f_edeq_sum ~ b_edeq_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_edeq_itt)
coefci(lm_edeq_itt,  vcov = sandwich)
#Significant effect of treatment_group (p<0.05) in the expected direction (negative)

#Muscle dysmorphia symptoms pre-followup - EXPLORATORY
lm_mddi_itt <- lm(f_mddi_sum ~ b_mddi_sum + treatment_group,  data = imputed_randomized_quant)
summary(lm_mddi_itt)
coefci(lm_mddi_itt,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)
```

```{r primary analysis 2 - TOT}
#Hopelessness pre-post
lm_bhs_tot_1 <- lm(pi_bhs_sum ~ b_bhs_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_bhs_tot_1)
coefci(lm_bhs_tot_1)
#Significant effect of treatment_group (p<0.001) in the expected direction (negative)

#Hopelessness pre-followup
lm_bhs_tot_2 <- lm(f_bhs_sum ~ b_bhs_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_bhs_tot_2)
coefci(lm_bhs_tot_2)
#Either significant effect of treatment_group (p<0.05) in the expected direction (negative) or not significant depending on rounding

#Agency pre-post
lm_shs_agency_tot_1 <- lm(pi_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_shs_agency_tot_1)
coefci(lm_shs_agency_tot_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.01) in the expected direction (positive)

#Agency pre-followup
lm_shs_agency_tot_2 <- lm(f_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_shs_agency_tot_2)
coefci(lm_shs_agency_tot_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body image state pre-post
lm_biss_tot_1 <- lm(pi_biss_sum ~ b_biss_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_biss_tot_1)
coefci(lm_biss_tot_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.001) in the expected direction (positive)

#Body image state pre-followup
lm_biss_tot_2 <- lm(f_biss_sum ~ b_biss_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_biss_tot_2)
coefci(lm_biss_tot_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Functionality appreciation pre-post
lm_fas_tot_1 <- lm(pi_fas_sum ~ b_fas_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_fas_tot_1)
coefci(lm_fas_tot_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.001) in the expected direction (positive)

#Functionality appreciation pre-followup
lm_fas_tot_2 <- lm(f_fas_sum ~ b_fas_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_fas_tot_2)
coefci(lm_fas_tot_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body image flexibility pre-post - EXPLORATORY
lm_biaaq_tot_1 <- lm(pi_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_biaaq_tot_1)
coefci(lm_biaaq_tot_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.01) in the expected direction (positive)

#Body image flexibility pre-followup - EXPLORATORY
lm_biaaq_tot_2 <- lm(f_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_biaaq_tot_2)
coefci(lm_biaaq_tot_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body-related mindfulness pre-post - EXPLORATORY
lm_chime_tot_1 <- lm(pi_chime_sum ~ b_chime_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_chime_tot_1)
coefci(lm_chime_tot_1,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body-related mindfulness pre-followup - EXPLORATORY
lm_chime_tot_2 <- lm(f_chime_sum ~ b_chime_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_chime_tot_2)
coefci(lm_chime_tot_2,  vcov = sandwich)
#Significant effect of treatment_group (p<0.05) in the expected direction (positive)

#Depression symptoms pre-followup
lm_mfq_tot <- lm(f_mfq_sum ~ b_mfq_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_mfq_tot)
coefci(lm_mfq_tot,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Eating disorder symptoms pre-followup
lm_edeq_tot <- lm(f_edeq_sum ~ b_edeq_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_edeq_tot)
coefci(lm_edeq_tot,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Muscle dysmorphia symptoms pre-followup - EXPLORATORY
lm_mddi_tot <- lm(f_mddi_sum ~ b_mddi_sum + treatment_group,  data = imputed_completer_intervention_quant)
summary(lm_mddi_tot)
coefci(lm_mddi_tot,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)
```

```{r robustness check 1 - baseline completers}
#Hopelessness pre-post
lm_bhs_b_1 <- lm(pi_bhs_sum ~ b_bhs_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_bhs_b_1)
coefci(lm_bhs_b_1)
#Significant effect of treatment_group (p<0.001) in the expected direction (negative)

#Hopelessness pre-followup
lm_bhs_b_2 <- lm(f_bhs_sum ~ b_bhs_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_bhs_b_2)
coefci(lm_bhs_b_2)
#No significant effect of treatment_group (p>0.05)

#Agency pre-post
lm_shs_agency_b_1 <- lm(pi_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_shs_agency_b_1)
coefci(lm_shs_agency_b_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.01) in the expected direction (positive)

#Agency pre-followup
lm_shs_agency_b_2 <- lm(f_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_shs_agency_b_2)
coefci(lm_shs_agency_b_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body image state pre-post
lm_biss_b_1 <- lm(pi_biss_sum ~ b_biss_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_biss_b_1)
coefci(lm_biss_b_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.001) in the expected direction (positive)

#Body image state pre-followup
lm_biss_b_2 <- lm(f_biss_sum ~ b_biss_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_biss_b_2)
coefci(lm_biss_b_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Functionality appreciation pre-post
lm_fas_b_1 <- lm(pi_fas_sum ~ b_fas_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_fas_b_1)
coefci(lm_fas_b_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.001) in the expected direction (positive)

#Functionality appreciation pre-followup
lm_fas_b_2 <- lm(f_fas_sum ~ b_fas_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_fas_b_2)
coefci(lm_fas_b_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body image flexibility pre-post - EXPLORATORY
lm_biaaq_b_1 <- lm(pi_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_biaaq_b_1)
coefci(lm_biaaq_b_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.01) in the expected direction (positive)

#Body image flexibility pre-followup - EXPLORATORY
lm_biaaq_b_2 <- lm(f_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_biaaq_b_2)
coefci(lm_biaaq_b_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body-related mindfulness pre-post - EXPLORATORY
lm_chime_b_1 <- lm(pi_chime_sum ~ b_chime_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_chime_b_1)
coefci(lm_chime_b_1,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body-related mindfulness pre-followup - EXPLORATORY
lm_chime_b_2 <- lm(f_chime_sum ~ b_chime_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_chime_b_2)
coefci(lm_chime_b_2,  vcov = sandwich)
#Significant effect of treatment_group (p<0.05) in the expected direction (positive)

#Depression symptoms pre-followup
lm_mfq_b <- lm(f_mfq_sum ~ b_mfq_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_mfq_b)
coefci(lm_mfq_b,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Eating disorder symptoms pre-followup
lm_edeq_b <- lm(f_edeq_sum ~ b_edeq_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_edeq_b)
coefci(lm_edeq_b,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Muscle dysmorphia symptoms pre-followup - EXPLORATORY
lm_mddi_b <- lm(f_mddi_sum ~ b_mddi_sum + treatment_group,  data = imputed_completer_baseline_quant)
summary(lm_mddi_b)
coefci(lm_mddi_b,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)
```

```{r robustness check 2 - followup completers}
#Hopelessness pre-post
lm_bhs_f_1 <- lm(pi_bhs_sum ~ b_bhs_sum + treatment_group,  data = completer_followup_quant)
summary(lm_bhs_f_1)
coefci(lm_bhs_f_1)
#Significant effect of treatment_group (p<0.05) in the expected direction (negative)

#Hopelessness pre-followup
lm_bhs_f_2 <- lm(f_bhs_sum ~ b_bhs_sum + treatment_group,  data = completer_followup_quant)
summary(lm_bhs_f_2)
coefci(lm_bhs_f_2)
#No significant effect of treatment_group (p>0.05)

#Agency pre-post
lm_shs_agency_f_1 <- lm(pi_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = completer_followup_quant)
summary(lm_shs_agency_f_1)
coefci(lm_shs_agency_f_1,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Agency pre-followup
lm_shs_agency_f_2 <- lm(f_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = completer_followup_quant)
summary(lm_shs_agency_f_2)
coefci(lm_shs_agency_f_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body image state pre-post
lm_biss_f_1 <- lm(pi_biss_sum ~ b_biss_sum + treatment_group,  data = completer_followup_quant)
summary(lm_biss_f_1)
coefci(lm_biss_f_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.01) in the expected direction (positive)

#Body image state pre-followup
lm_biss_f_2 <- lm(f_biss_sum ~ b_biss_sum + treatment_group,  data = completer_followup_quant)
summary(lm_biss_f_2)
coefci(lm_biss_f_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Functionality appreciation pre-post
lm_fas_f_1 <- lm(pi_fas_sum ~ b_fas_sum + treatment_group,  data = completer_followup_quant)
summary(lm_fas_f_1)
coefci(lm_fas_f_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.001) in the expected direction (positive)

#Functionality appreciation pre-followup
lm_fas_f_2 <- lm(f_fas_sum ~ b_fas_sum + treatment_group,  data = completer_followup_quant)
summary(lm_fas_f_2)
coefci(lm_fas_f_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body image flexibility pre-post - EXPLORATORY
lm_biaaq_f_1 <- lm(pi_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = completer_followup_quant)
summary(lm_biaaq_f_1)
coefci(lm_biaaq_f_1,  vcov = sandwich)
#Significant effect of treatment_group (p<0.01) in the expected direction (positive)

#Body image flexibility pre-followup - EXPLORATORY
lm_biaaq_f_2 <- lm(f_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = completer_followup_quant)
summary(lm_biaaq_f_2)
coefci(lm_biaaq_f_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body-related mindfulness pre-post - EXPLORATORY
lm_chime_f_1 <- lm(pi_chime_sum ~ b_chime_sum + treatment_group,  data = completer_followup_quant)
summary(lm_chime_f_1)
coefci(lm_chime_f_1,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Body-related mindfulness pre-followup - EXPLORATORY
lm_chime_f_2 <- lm(f_chime_sum ~ b_chime_sum + treatment_group,  data = completer_followup_quant)
summary(lm_chime_f_2)
coefci(lm_chime_f_2,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Depression symptoms pre-followup
lm_mfq_f <- lm(f_mfq_sum ~ b_mfq_sum + treatment_group,  data = completer_followup_quant)
summary(lm_mfq_f)
coefci(lm_mfq_f,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Eating disorder symptoms pre-followup
lm_edeq_f <- lm(f_edeq_sum ~ b_edeq_sum + treatment_group,  data = completer_followup_quant)
summary(lm_edeq_f)
coefci(lm_edeq_f,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)

#Muscle dysmorphia symptoms pre-followup - EXPLORATORY
lm_mddi_f <- lm(f_mddi_sum ~ b_mddi_sum + treatment_group,  data = completer_followup_quant)
summary(lm_mddi_f)
coefci(lm_mddi_f,  vcov = sandwich)
#No significant effect of treatment_group (p>0.05)
```

```{r regression assumptions - ITT}
#Check ITT pre-post

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_itt_1))
sqrt(vif(lm_shs_agency_itt_1))
sqrt(vif(lm_biss_itt_1))
sqrt(vif(lm_fas_itt_1))
sqrt(vif(lm_biaaq_itt_1))
sqrt(vif(lm_chime_itt_1))

##Linearity of data
plot(lm_bhs_itt_1,  1)
plot(lm_shs_agency_itt_1,  1)
plot(lm_biss_itt_1,  1)
plot(lm_fas_itt_1,  1)
plot(lm_biaaq_itt_1,  1)
plot(lm_chime_itt_1,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_itt_1)
durbinWatsonTest(lm_shs_agency_itt_1)
durbinWatsonTest(lm_biss_itt_1)
durbinWatsonTest(lm_fas_itt_1) 
durbinWatsonTest(lm_biaaq_itt_1)
durbinWatsonTest(lm_chime_itt_1) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_itt_1,  3) 
plot(lm_shs_agency_itt_1,  3)
plot(lm_biss_itt_1,  3) 
plot(lm_fas_itt_1,  3)
plot(lm_biaaq_itt_1,  3)
plot(lm_chime_itt_1,  3)
ncvTest(lm_bhs_itt_1) 
ncvTest(lm_shs_agency_itt_1)
ncvTest(lm_biss_itt_1)
ncvTest(lm_fas_itt_1) 
ncvTest(lm_biaaq_itt_1)
ncvTest(lm_chime_itt_1)
bptest(lm_bhs_itt_1)
bptest(lm_shs_agency_itt_1)
bptest(lm_biss_itt_1)
bptest(lm_fas_itt_1) 
bptest(lm_biaaq_itt_1)
bptest(lm_chime_itt_1)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_itt_1)
ols_plot_resid_qq(lm_shs_agency_itt_1) 
ols_plot_resid_qq(lm_biss_itt_1)
ols_plot_resid_qq(lm_fas_itt_1)
ols_plot_resid_qq(lm_biaaq_itt_1)
ols_plot_resid_qq(lm_chime_itt_1)

#Check ITT pre-followup

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_itt_2))
sqrt(vif(lm_shs_agency_itt_2))
sqrt(vif(lm_biss_itt_2))
sqrt(vif(lm_fas_itt_2))
sqrt(vif(lm_biaaq_itt_2))
sqrt(vif(lm_chime_itt_2))

##Linearity of data
plot(lm_bhs_itt_2,  1)
plot(lm_shs_agency_itt_2,  1)
plot(lm_biss_itt_2,  1)
plot(lm_fas_itt_2,  1)
plot(lm_biaaq_itt_2,  1)
plot(lm_chime_itt_2,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_itt_2)
durbinWatsonTest(lm_shs_agency_itt_2)
durbinWatsonTest(lm_biss_itt_2)
durbinWatsonTest(lm_fas_itt_2) 
durbinWatsonTest(lm_biaaq_itt_2)
durbinWatsonTest(lm_chime_itt_2) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_itt_2,  3) 
plot(lm_shs_agency_itt_2,  3)
plot(lm_biss_itt_2,  3) 
plot(lm_fas_itt_2,  3)
plot(lm_biaaq_itt_2,  3)
plot(lm_chime_itt_2,  3)
ncvTest(lm_bhs_itt_2) 
ncvTest(lm_shs_agency_itt_2)
ncvTest(lm_biss_itt_2)
ncvTest(lm_fas_itt_2) 
ncvTest(lm_biaaq_itt_2)
ncvTest(lm_chime_itt_2)
bptest(lm_bhs_itt_2)
bptest(lm_shs_agency_itt_2)
bptest(lm_biss_itt_2)
bptest(lm_fas_itt_2) 
bptest(lm_biaaq_itt_2)
bptest(lm_chime_itt_2)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_itt_2)
ols_plot_resid_qq(lm_shs_agency_itt_2) 
ols_plot_resid_qq(lm_biss_itt_2)
ols_plot_resid_qq(lm_fas_itt_2)
ols_plot_resid_qq(lm_biaaq_itt_2)
ols_plot_resid_qq(lm_chime_itt_2)
```

```{r regression assumptions - TOT}
#Check TOT pre-post

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_tot_1))
sqrt(vif(lm_shs_agency_tot_1))
sqrt(vif(lm_biss_tot_1))
sqrt(vif(lm_fas_tot_1))
sqrt(vif(lm_biaaq_tot_1))
sqrt(vif(lm_chime_tot_1))

##Linearity of data
plot(lm_bhs_tot_1,  1)
plot(lm_shs_agency_tot_1,  1)
plot(lm_biss_tot_1,  1)
plot(lm_fas_tot_1,  1)
plot(lm_biaaq_tot_1,  1)
plot(lm_chime_tot_1,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_tot_1)
durbinWatsonTest(lm_shs_agency_tot_1)
durbinWatsonTest(lm_biss_tot_1)
durbinWatsonTest(lm_fas_tot_1) 
durbinWatsonTest(lm_biaaq_tot_1)
durbinWatsonTest(lm_chime_tot_1) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_tot_1,  3) 
plot(lm_shs_agency_tot_1,  3)
plot(lm_biss_tot_1,  3) 
plot(lm_fas_tot_1,  3)
plot(lm_biaaq_tot_1,  3)
plot(lm_chime_tot_1,  3)
ncvTest(lm_bhs_tot_1) 
ncvTest(lm_shs_agency_tot_1)
ncvTest(lm_biss_tot_1)
ncvTest(lm_fas_tot_1) 
ncvTest(lm_biaaq_tot_1)
ncvTest(lm_chime_tot_1)
bptest(lm_bhs_tot_1)
bptest(lm_shs_agency_tot_1)
bptest(lm_biss_tot_1)
bptest(lm_fas_tot_1) 
bptest(lm_biaaq_tot_1)
bptest(lm_chime_tot_1)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_tot_1)
ols_plot_resid_qq(lm_shs_agency_tot_1) 
ols_plot_resid_qq(lm_biss_tot_1)
ols_plot_resid_qq(lm_fas_tot_1)
ols_plot_resid_qq(lm_biaaq_tot_1)
ols_plot_resid_qq(lm_chime_tot_1)

#Check TOT pre-followup

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_tot_2))
sqrt(vif(lm_shs_agency_tot_2))
sqrt(vif(lm_biss_tot_2))
sqrt(vif(lm_fas_tot_2))
sqrt(vif(lm_biaaq_tot_2))
sqrt(vif(lm_chime_tot_2))

##Linearity of data
plot(lm_bhs_tot_2,  1)
plot(lm_shs_agency_tot_2,  1)
plot(lm_biss_tot_2,  1)
plot(lm_fas_tot_2,  1)
plot(lm_biaaq_tot_2,  1)
plot(lm_chime_tot_2,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_tot_2)
durbinWatsonTest(lm_shs_agency_tot_2)
durbinWatsonTest(lm_biss_tot_2)
durbinWatsonTest(lm_fas_tot_2) 
durbinWatsonTest(lm_biaaq_tot_2)
durbinWatsonTest(lm_chime_tot_2) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_tot_2,  3) 
plot(lm_shs_agency_tot_2,  3)
plot(lm_biss_tot_2,  3) 
plot(lm_fas_tot_2,  3)
plot(lm_biaaq_tot_2,  3)
plot(lm_chime_tot_2,  3)
ncvTest(lm_bhs_tot_2) 
ncvTest(lm_shs_agency_tot_2)
ncvTest(lm_biss_tot_2)
ncvTest(lm_fas_tot_2) 
ncvTest(lm_biaaq_tot_2)
ncvTest(lm_chime_tot_2)
bptest(lm_bhs_tot_2)
bptest(lm_shs_agency_tot_2)
bptest(lm_biss_tot_2)
bptest(lm_fas_tot_2) 
bptest(lm_biaaq_tot_2)
bptest(lm_chime_tot_2)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_tot_2)
ols_plot_resid_qq(lm_shs_agency_tot_2) 
ols_plot_resid_qq(lm_biss_tot_2)
ols_plot_resid_qq(lm_fas_tot_2)
ols_plot_resid_qq(lm_biaaq_tot_2)
ols_plot_resid_qq(lm_chime_tot_2)
```

```{r regression assumptions - baseline completers}
#Check baseline completers pre-post

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_b_1))
sqrt(vif(lm_shs_agency_b_1))
sqrt(vif(lm_biss_b_1))
sqrt(vif(lm_fas_b_1))
sqrt(vif(lm_biaaq_b_1))
sqrt(vif(lm_chime_b_1))

##Linearity of data
plot(lm_bhs_b_1,  1)
plot(lm_shs_agency_b_1,  1)
plot(lm_biss_b_1,  1)
plot(lm_fas_b_1,  1)
plot(lm_biaaq_b_1,  1)
plot(lm_chime_b_1,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_b_1)
durbinWatsonTest(lm_shs_agency_b_1)
durbinWatsonTest(lm_biss_b_1)
durbinWatsonTest(lm_fas_b_1) 
durbinWatsonTest(lm_biaaq_b_1)
durbinWatsonTest(lm_chime_b_1) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_b_1,  3) 
plot(lm_shs_agency_b_1,  3)
plot(lm_biss_b_1,  3) 
plot(lm_fas_b_1,  3)
plot(lm_biaaq_b_1,  3)
plot(lm_chime_b_1,  3)
ncvTest(lm_bhs_b_1) 
ncvTest(lm_shs_agency_b_1)
ncvTest(lm_biss_b_1)
ncvTest(lm_fas_b_1) 
ncvTest(lm_biaaq_b_1)
ncvTest(lm_chime_b_1)
bptest(lm_bhs_b_1)
bptest(lm_shs_agency_b_1)
bptest(lm_biss_b_1)
bptest(lm_fas_b_1) 
bptest(lm_biaaq_b_1)
bptest(lm_chime_b_1)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_b_1)
ols_plot_resid_qq(lm_shs_agency_b_1) 
ols_plot_resid_qq(lm_biss_b_1)
ols_plot_resid_qq(lm_fas_b_1)
ols_plot_resid_qq(lm_biaaq_b_1)
ols_plot_resid_qq(lm_chime_b_1)

#Check baseline completers pre-followup

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_b_2))
sqrt(vif(lm_shs_agency_b_2))
sqrt(vif(lm_biss_b_2))
sqrt(vif(lm_fas_b_2))
sqrt(vif(lm_biaaq_b_2))
sqrt(vif(lm_chime_b_2))

##Linearity of data
plot(lm_bhs_b_2,  1)
plot(lm_shs_agency_b_2,  1)
plot(lm_biss_b_2,  1)
plot(lm_fas_b_2,  1)
plot(lm_biaaq_b_2,  1)
plot(lm_chime_b_2,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_b_2)
durbinWatsonTest(lm_shs_agency_b_2)
durbinWatsonTest(lm_biss_b_2)
durbinWatsonTest(lm_fas_b_2) 
durbinWatsonTest(lm_biaaq_b_2)
durbinWatsonTest(lm_chime_b_2) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_b_2,  3) 
plot(lm_shs_agency_b_2,  3)
plot(lm_biss_b_2,  3) 
plot(lm_fas_b_2,  3)
plot(lm_biaaq_b_2,  3)
plot(lm_chime_b_2,  3)
ncvTest(lm_bhs_b_2) 
ncvTest(lm_shs_agency_b_2)
ncvTest(lm_biss_b_2)
ncvTest(lm_fas_b_2) 
ncvTest(lm_biaaq_b_2)
ncvTest(lm_chime_b_2)
bptest(lm_bhs_b_2)
bptest(lm_shs_agency_b_2)
bptest(lm_biss_b_2)
bptest(lm_fas_b_2) 
bptest(lm_biaaq_b_2)
bptest(lm_chime_b_2)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_b_2)
ols_plot_resid_qq(lm_shs_agency_b_2) 
ols_plot_resid_qq(lm_biss_b_2)
ols_plot_resid_qq(lm_fas_b_2)
ols_plot_resid_qq(lm_biaaq_b_2)
ols_plot_resid_qq(lm_chime_b_2)
```

```{r regression assumptions - followup completers}
#Check followup completers pre-post

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_f_1))
sqrt(vif(lm_shs_agency_f_1))
sqrt(vif(lm_biss_f_1))
sqrt(vif(lm_fas_f_1))
sqrt(vif(lm_biaaq_f_1))
sqrt(vif(lm_chime_f_1))

##Linearity of data
plot(lm_bhs_f_1,  1)
plot(lm_shs_agency_f_1,  1)
plot(lm_biss_f_1,  1)
plot(lm_fas_f_1,  1)
plot(lm_biaaq_f_1,  1)
plot(lm_chime_f_1,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_f_1)
durbinWatsonTest(lm_shs_agency_f_1)
durbinWatsonTest(lm_biss_f_1)
durbinWatsonTest(lm_fas_f_1) 
durbinWatsonTest(lm_biaaq_f_1)
durbinWatsonTest(lm_chime_f_1) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_f_1,  3) 
plot(lm_shs_agency_f_1,  3)
plot(lm_biss_f_1,  3) 
plot(lm_fas_f_1,  3)
plot(lm_biaaq_f_1,  3)
plot(lm_chime_f_1,  3)
ncvTest(lm_bhs_f_1) 
ncvTest(lm_shs_agency_f_1)
ncvTest(lm_biss_f_1)
ncvTest(lm_fas_f_1) 
ncvTest(lm_biaaq_f_1)
ncvTest(lm_chime_f_1)
bptest(lm_bhs_f_1)
bptest(lm_shs_agency_f_1)
bptest(lm_biss_f_1)
bptest(lm_fas_f_1) 
bptest(lm_biaaq_f_1)
bptest(lm_chime_f_1)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_f_1)
ols_plot_resid_qq(lm_shs_agency_f_1) 
ols_plot_resid_qq(lm_biss_f_1)
ols_plot_resid_qq(lm_fas_f_1)
ols_plot_resid_qq(lm_biaaq_f_1)
ols_plot_resid_qq(lm_chime_f_1)

#Check followup completers pre-followup

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_f_2))
sqrt(vif(lm_shs_agency_f_2))
sqrt(vif(lm_biss_f_2))
sqrt(vif(lm_fas_f_2))
sqrt(vif(lm_biaaq_f_2))
sqrt(vif(lm_chime_f_2))

##Linearity of data
plot(lm_bhs_f_2,  1)
plot(lm_shs_agency_f_2,  1)
plot(lm_biss_f_2,  1)
plot(lm_fas_f_2,  1)
plot(lm_biaaq_f_2,  1)
plot(lm_chime_f_2,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_f_2)
durbinWatsonTest(lm_shs_agency_f_2)
durbinWatsonTest(lm_biss_f_2)
durbinWatsonTest(lm_fas_f_2) 
durbinWatsonTest(lm_biaaq_f_2)
durbinWatsonTest(lm_chime_f_2) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_f_2,  3) 
plot(lm_shs_agency_f_2,  3)
plot(lm_biss_f_2,  3) 
plot(lm_fas_f_2,  3)
plot(lm_biaaq_f_2,  3)
plot(lm_chime_f_2,  3)
ncvTest(lm_bhs_f_2) 
ncvTest(lm_shs_agency_f_2)
ncvTest(lm_biss_f_2)
ncvTest(lm_fas_f_2) 
ncvTest(lm_biaaq_f_2)
ncvTest(lm_chime_f_2)
bptest(lm_bhs_f_2)
bptest(lm_shs_agency_f_2)
bptest(lm_biss_f_2)
bptest(lm_fas_f_2) 
bptest(lm_biaaq_f_2)
bptest(lm_chime_f_2)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_f_2)
ols_plot_resid_qq(lm_shs_agency_f_2) 
ols_plot_resid_qq(lm_biss_f_2)
ols_plot_resid_qq(lm_fas_f_2)
ols_plot_resid_qq(lm_biaaq_f_2)
ols_plot_resid_qq(lm_chime_f_2)
```

```{r effect sizes - ITT}
#Make new dataframes to separate Intervention and Control folks (with imputed data)
imputed_randomized_quant_intervention <- imputed_randomized_quant %>% 
  filter(treatment_group == "Intervention")

imputed_completer_intervention_quant_contro <- imputed_randomized_quant %>% 
  filter(treatment_group == "Control")

#Hopelessness descriptives

##Descriptives for intervention
bhs_stats_intervention_itt <- imputed_randomized_quant_intervention %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
bhs_stats_control_itt <- imputed_completer_intervention_quant_contro %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Hopelessness pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = bhs_stats_intervention_itt$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_itt$pi_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_itt$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_itt$pi_bhs_sum_sd, 
            n = bhs_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = bhs_stats_control_itt$b_bhs_sum_mean, 
            m2 = bhs_stats_control_itt$pi_bhs_sum_mean, 
            sd1 = bhs_stats_control_itt$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_itt$pi_bhs_sum_sd, 
            n = bhs_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = bhs_stats_intervention_itt$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_intervention_itt$bhs_sum_change_pre_post_sd,
             n = bhs_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = bhs_stats_control_itt$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_control_itt$bhs_sum_change_pre_post_sd,
             n = bhs_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = bhs_stats_intervention_itt$bhs_sum_change_pre_post_mean,  
        m2 = bhs_stats_control_itt$bhs_sum_change_pre_post_mean,  
        sd1 = bhs_stats_intervention_itt$bhs_sum_change_pre_post_sd,  
        sd2 = bhs_stats_control_itt$bhs_sum_change_pre_post_sd,  
        n1 = bhs_stats_intervention_itt$n,  
        n2 = bhs_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Hopelessness pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = bhs_stats_intervention_itt$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_itt$f_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_itt$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_itt$f_bhs_sum_sd, 
            n = bhs_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = bhs_stats_control_itt$b_bhs_sum_mean, 
            m2 = bhs_stats_control_itt$f_bhs_sum_mean, 
            sd1 = bhs_stats_control_itt$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_itt$f_bhs_sum_sd, 
            n = bhs_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = bhs_stats_intervention_itt$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_intervention_itt$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = bhs_stats_control_itt$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_control_itt$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = bhs_stats_intervention_itt$bhs_sum_change_pre_followup_mean,  
        m2 = bhs_stats_control_itt$bhs_sum_change_pre_followup_mean,  
        sd1 = bhs_stats_intervention_itt$bhs_sum_change_pre_followup_sd,  
        sd2 = bhs_stats_control_itt$bhs_sum_change_pre_followup_sd,  
        n1 = bhs_stats_intervention_itt$n,  
        n2 = bhs_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency descriptives

##Descriptives for intervention
shs_agency_stats_intervention_itt <- imputed_randomized_quant_intervention %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
shs_agency_stats_control_itt <- imputed_completer_intervention_quant_contro %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Agency pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = shs_agency_stats_intervention_itt$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_itt$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_itt$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_itt$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = shs_agency_stats_control_itt$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_itt$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_itt$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_itt$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = shs_agency_stats_control_itt$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_control_itt$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_post_mean,  
        m2 = shs_agency_stats_control_itt$shs_agency_sum_change_pre_post_mean,  
        sd1 = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_post_sd,  
        sd2 = shs_agency_stats_control_itt$shs_agency_sum_change_pre_post_sd,  
        n1 = shs_agency_stats_intervention_itt$n,  
        n2 = shs_agency_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = shs_agency_stats_intervention_itt$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_itt$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_itt$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_itt$f_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = shs_agency_stats_control_itt$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_itt$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_itt$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_itt$f_shs_agency_sum_sd, 
            n = shs_agency_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = shs_agency_stats_control_itt$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_control_itt$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_followup_mean,  
        m2 = shs_agency_stats_control_itt$shs_agency_sum_change_pre_followup_mean,  
        sd1 = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_followup_sd,  
        sd2 = shs_agency_stats_control_itt$shs_agency_sum_change_pre_followup_sd,  
        n1 = shs_agency_stats_intervention_itt$n,  
        n2 = shs_agency_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state descriptives

##Descriptives for intervention
biss_stats_intervention_itt <- imputed_randomized_quant_intervention %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biss_stats_control_itt <- imputed_completer_intervention_quant_contro %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image state pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = biss_stats_intervention_itt$b_biss_sum_mean, 
            m2 = biss_stats_intervention_itt$pi_biss_sum_mean, 
            sd1 = biss_stats_intervention_itt$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_itt$pi_biss_sum_sd, 
            n = biss_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biss_stats_control_itt$b_biss_sum_mean, 
            m2 = biss_stats_control_itt$pi_biss_sum_mean, 
            sd1 = biss_stats_control_itt$b_biss_sum_sd, 
            sd2 = biss_stats_control_itt$pi_biss_sum_sd, 
            n = biss_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biss_stats_intervention_itt$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_intervention_itt$biss_sum_change_pre_post_sd,
             n = biss_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biss_stats_control_itt$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_control_itt$biss_sum_change_pre_post_sd,
             n = biss_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biss_stats_intervention_itt$biss_sum_change_pre_post_mean,  
        m2 = biss_stats_control_itt$biss_sum_change_pre_post_mean,  
        sd1 = biss_stats_intervention_itt$biss_sum_change_pre_post_sd,  
        sd2 = biss_stats_control_itt$biss_sum_change_pre_post_sd,  
        n1 = biss_stats_intervention_itt$n,  
        n2 = biss_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = biss_stats_intervention_itt$b_biss_sum_mean, 
            m2 = biss_stats_intervention_itt$f_biss_sum_mean, 
            sd1 = biss_stats_intervention_itt$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_itt$f_biss_sum_sd, 
            n = biss_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biss_stats_control_itt$b_biss_sum_mean, 
            m2 = biss_stats_control_itt$f_biss_sum_mean, 
            sd1 = biss_stats_control_itt$b_biss_sum_sd, 
            sd2 = biss_stats_control_itt$f_biss_sum_sd, 
            n = biss_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biss_stats_intervention_itt$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_intervention_itt$biss_sum_change_pre_followup_sd,
             n = biss_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biss_stats_control_itt$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_control_itt$biss_sum_change_pre_followup_sd,
             n = biss_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biss_stats_intervention_itt$biss_sum_change_pre_followup_mean,  
        m2 = biss_stats_control_itt$biss_sum_change_pre_followup_mean,  
        sd1 = biss_stats_intervention_itt$biss_sum_change_pre_followup_sd,  
        sd2 = biss_stats_control_itt$biss_sum_change_pre_followup_sd,  
        n1 = biss_stats_intervention_itt$n,  
        n2 = biss_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")   
  
#Functionality appreciation descriptives

##Descriptives for intervention
fas_stats_intervention_itt <- imputed_randomized_quant_intervention %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
fas_stats_control_itt <- imputed_completer_intervention_quant_contro %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Functionality appreciation pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = fas_stats_intervention_itt$b_fas_sum_mean, 
            m2 = fas_stats_intervention_itt$pi_fas_sum_mean, 
            sd1 = fas_stats_intervention_itt$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_itt$pi_fas_sum_sd, 
            n = fas_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = fas_stats_control_itt$b_fas_sum_mean, 
            m2 = fas_stats_control_itt$pi_fas_sum_mean, 
            sd1 = fas_stats_control_itt$b_fas_sum_sd, 
            sd2 = fas_stats_control_itt$pi_fas_sum_sd, 
            n = fas_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = fas_stats_intervention_itt$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_intervention_itt$fas_sum_change_pre_post_sd,
             n = fas_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = fas_stats_control_itt$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_control_itt$fas_sum_change_pre_post_sd,
             n = fas_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = fas_stats_intervention_itt$fas_sum_change_pre_post_mean,  
        m2 = fas_stats_control_itt$fas_sum_change_pre_post_mean,  
        sd1 = fas_stats_intervention_itt$fas_sum_change_pre_post_sd,  
        sd2 = fas_stats_control_itt$fas_sum_change_pre_post_sd,  
        n1 = fas_stats_intervention_itt$n,  
        n2 = fas_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Functionality appreciation pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = fas_stats_intervention_itt$b_fas_sum_mean, 
            m2 = fas_stats_intervention_itt$f_fas_sum_mean, 
            sd1 = fas_stats_intervention_itt$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_itt$f_fas_sum_sd, 
            n = fas_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = fas_stats_control_itt$b_fas_sum_mean, 
            m2 = fas_stats_control_itt$f_fas_sum_mean, 
            sd1 = fas_stats_control_itt$b_fas_sum_sd, 
            sd2 = fas_stats_control_itt$f_fas_sum_sd, 
            n = fas_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = fas_stats_intervention_itt$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_intervention_itt$fas_sum_change_pre_followup_sd,
             n = fas_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = fas_stats_control_itt$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_control_itt$fas_sum_change_pre_followup_sd,
             n = fas_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = fas_stats_intervention_itt$fas_sum_change_pre_followup_mean,  
        m2 = fas_stats_control_itt$fas_sum_change_pre_followup_mean,  
        sd1 = fas_stats_intervention_itt$fas_sum_change_pre_followup_sd,  
        sd2 = fas_stats_control_itt$fas_sum_change_pre_followup_sd,  
        n1 = fas_stats_intervention_itt$n,  
        n2 = fas_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Body image flexibility descriptives

##Descriptives for intervention
biaaq_stats_intervention_itt <- imputed_randomized_quant_intervention %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biaaq_stats_control_itt <- imputed_completer_intervention_quant_contro %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image flexibility pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = biaaq_stats_intervention_itt$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_itt$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_itt$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_itt$pi_biaaq_sum_sd, 
            n = biaaq_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biaaq_stats_control_itt$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_itt$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_itt$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_itt$pi_biaaq_sum_sd, 
            n = biaaq_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biaaq_stats_intervention_itt$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_intervention_itt$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biaaq_stats_control_itt$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_control_itt$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biaaq_stats_intervention_itt$biaaq_sum_change_pre_post_mean,  
        m2 = biaaq_stats_control_itt$biaaq_sum_change_pre_post_mean,  
        sd1 = biaaq_stats_intervention_itt$biaaq_sum_change_pre_post_sd,  
        sd2 = biaaq_stats_control_itt$biaaq_sum_change_pre_post_sd,  
        n1 = biaaq_stats_intervention_itt$n,  
        n2 = biaaq_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image flexibility pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = biaaq_stats_intervention_itt$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_itt$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_itt$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_itt$f_biaaq_sum_sd, 
            n = biaaq_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biaaq_stats_control_itt$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_itt$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_itt$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_itt$f_biaaq_sum_sd, 
            n = biaaq_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biaaq_stats_intervention_itt$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_intervention_itt$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biaaq_stats_control_itt$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_control_itt$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biaaq_stats_intervention_itt$biaaq_sum_change_pre_followup_mean,  
        m2 = biaaq_stats_control_itt$biaaq_sum_change_pre_followup_mean,  
        sd1 = biaaq_stats_intervention_itt$biaaq_sum_change_pre_followup_sd,  
        sd2 = biaaq_stats_control_itt$biaaq_sum_change_pre_followup_sd,  
        n1 = biaaq_stats_intervention_itt$n,  
        n2 = biaaq_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness descriptives

##Descriptives for intervention
chime_stats_intervention_itt <- imputed_randomized_quant_intervention %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
chime_stats_control_itt <- imputed_completer_intervention_quant_contro %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body-related mindfulness pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = chime_stats_intervention_itt$b_chime_sum_mean, 
            m2 = chime_stats_intervention_itt$pi_chime_sum_mean, 
            sd1 = chime_stats_intervention_itt$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_itt$pi_chime_sum_sd, 
            n = chime_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = chime_stats_control_itt$b_chime_sum_mean, 
            m2 = chime_stats_control_itt$pi_chime_sum_mean, 
            sd1 = chime_stats_control_itt$b_chime_sum_sd, 
            sd2 = chime_stats_control_itt$pi_chime_sum_sd, 
            n = chime_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = chime_stats_intervention_itt$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_intervention_itt$chime_sum_change_pre_post_sd,
             n = chime_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = chime_stats_control_itt$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_control_itt$chime_sum_change_pre_post_sd,
             n = chime_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = chime_stats_intervention_itt$chime_sum_change_pre_post_mean,  
        m2 = chime_stats_control_itt$chime_sum_change_pre_post_mean,  
        sd1 = chime_stats_intervention_itt$chime_sum_change_pre_post_sd,  
        sd2 = chime_stats_control_itt$chime_sum_change_pre_post_sd,  
        n1 = chime_stats_intervention_itt$n,  
        n2 = chime_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = chime_stats_intervention_itt$b_chime_sum_mean, 
            m2 = chime_stats_intervention_itt$f_chime_sum_mean, 
            sd1 = chime_stats_intervention_itt$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_itt$f_chime_sum_sd, 
            n = chime_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = chime_stats_control_itt$b_chime_sum_mean, 
            m2 = chime_stats_control_itt$f_chime_sum_mean, 
            sd1 = chime_stats_control_itt$b_chime_sum_sd, 
            sd2 = chime_stats_control_itt$f_chime_sum_sd, 
            n = chime_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = chime_stats_intervention_itt$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_intervention_itt$chime_sum_change_pre_followup_sd,
             n = chime_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = chime_stats_control_itt$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_control_itt$chime_sum_change_pre_followup_sd,
             n = chime_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = chime_stats_intervention_itt$chime_sum_change_pre_followup_mean,  
        m2 = chime_stats_control_itt$chime_sum_change_pre_followup_mean,  
        sd1 = chime_stats_intervention_itt$chime_sum_change_pre_followup_sd,  
        sd2 = chime_stats_control_itt$chime_sum_change_pre_followup_sd,  
        n1 = chime_stats_intervention_itt$n,  
        n2 = chime_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Depression symptoms descriptives

##Descriptives for intervention
mfq_stats_intervention_itt <- imputed_randomized_quant_intervention %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mfq_stats_control_itt <- imputed_completer_intervention_quant_contro %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Depression symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = mfq_stats_intervention_itt$b_mfq_sum_mean, 
            m2 = mfq_stats_intervention_itt$f_mfq_sum_mean, 
            sd1 = mfq_stats_intervention_itt$b_mfq_sum_sd, 
            sd2 = mfq_stats_intervention_itt$f_mfq_sum_sd, 
            n = mfq_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = mfq_stats_control_itt$b_mfq_sum_mean, 
            m2 = mfq_stats_control_itt$f_mfq_sum_mean, 
            sd1 = mfq_stats_control_itt$b_mfq_sum_sd, 
            sd2 = mfq_stats_control_itt$f_mfq_sum_sd, 
            n = mfq_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = mfq_stats_intervention_itt$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_intervention_itt$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = mfq_stats_control_itt$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_control_itt$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = mfq_stats_intervention_itt$mfq_sum_change_pre_followup_mean,  
        m2 = mfq_stats_control_itt$mfq_sum_change_pre_followup_mean,  
        sd1 = mfq_stats_intervention_itt$mfq_sum_change_pre_followup_sd,  
        sd2 = mfq_stats_control_itt$mfq_sum_change_pre_followup_sd,  
        n1 = mfq_stats_intervention_itt$n,  
        n2 = mfq_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Eating disorder symptoms descriptives

##Descriptives for intervention
edeq_stats_intervention_itt <- imputed_randomized_quant_intervention %>%
  select(b_edeq_sum, f_edeq_sum) %>%
  mutate(edeq_sum_change_pre_followup = f_edeq_sum - b_edeq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
edeq_stats_control_itt <- imputed_completer_intervention_quant_contro %>%
  select(b_edeq_sum, f_edeq_sum) %>%
  mutate(edeq_sum_change_pre_followup = f_edeq_sum - b_edeq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Eating disorder symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = edeq_stats_intervention_itt$b_edeq_sum_mean, 
            m2 = edeq_stats_intervention_itt$f_edeq_sum_mean, 
            sd1 = edeq_stats_intervention_itt$b_edeq_sum_sd, 
            sd2 = edeq_stats_intervention_itt$f_edeq_sum_sd, 
            n = edeq_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = edeq_stats_control_itt$b_edeq_sum_mean, 
            m2 = edeq_stats_control_itt$f_edeq_sum_mean, 
            sd1 = edeq_stats_control_itt$b_edeq_sum_sd, 
            sd2 = edeq_stats_control_itt$f_edeq_sum_sd, 
            n = edeq_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = edeq_stats_intervention_itt$edeq_sum_change_pre_followup_mean,
             sddiff = edeq_stats_intervention_itt$edeq_sum_change_pre_followup_sd,
             n = edeq_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = edeq_stats_control_itt$edeq_sum_change_pre_followup_mean,
             sddiff = edeq_stats_control_itt$edeq_sum_change_pre_followup_sd,
             n = edeq_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = edeq_stats_intervention_itt$edeq_sum_change_pre_followup_mean,  
        m2 = edeq_stats_control_itt$edeq_sum_change_pre_followup_mean,  
        sd1 = edeq_stats_intervention_itt$edeq_sum_change_pre_followup_sd,  
        sd2 = edeq_stats_control_itt$edeq_sum_change_pre_followup_sd,  
        n1 = edeq_stats_intervention_itt$n,  
        n2 = edeq_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Muscle dysmorphia symptoms descriptives

##Descriptives for intervention
mddi_stats_intervention_itt <- imputed_randomized_quant_intervention %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mddi_stats_control_itt <- imputed_completer_intervention_quant_contro %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Muscle dysmorphia symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = mddi_stats_intervention_itt$b_mddi_sum_mean, 
            m2 = mddi_stats_intervention_itt$f_mddi_sum_mean, 
            sd1 = mddi_stats_intervention_itt$b_mddi_sum_sd, 
            sd2 = mddi_stats_intervention_itt$f_mddi_sum_sd, 
            n = mddi_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = mddi_stats_control_itt$b_mddi_sum_mean, 
            m2 = mddi_stats_control_itt$f_mddi_sum_mean, 
            sd1 = mddi_stats_control_itt$b_mddi_sum_sd, 
            sd2 = mddi_stats_control_itt$f_mddi_sum_sd, 
            n = mddi_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = mddi_stats_intervention_itt$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_intervention_itt$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = mddi_stats_control_itt$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_control_itt$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = mddi_stats_intervention_itt$mddi_sum_change_pre_followup_mean,  
        m2 = mddi_stats_control_itt$mddi_sum_change_pre_followup_mean,  
        sd1 = mddi_stats_intervention_itt$mddi_sum_change_pre_followup_sd,  
        sd2 = mddi_stats_control_itt$mddi_sum_change_pre_followup_sd,  
        n1 = mddi_stats_intervention_itt$n,  
        n2 = mddi_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")
```

```{r effect sizes - TOT}
#Make new dataframes to separate Intervention and Control folks (with imputed data)
imputed_completer_intervention_quant_intervention <- imputed_completer_intervention_quant %>% 
  filter(treatment_group == "Intervention")

imputed_completer_intervention_quant_control <- imputed_completer_intervention_quant %>% 
  filter(treatment_group == "Control")

#Hopelessness descriptives

##Descriptives for intervention
bhs_stats_intervention_tot <- imputed_completer_intervention_quant_intervention %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
bhs_stats_control_tot <- imputed_completer_intervention_quant_control %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Hopelessness pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = bhs_stats_intervention_tot$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_tot$pi_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_tot$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_tot$pi_bhs_sum_sd, 
            n = bhs_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = bhs_stats_control_tot$b_bhs_sum_mean, 
            m2 = bhs_stats_control_tot$pi_bhs_sum_mean, 
            sd1 = bhs_stats_control_tot$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_tot$pi_bhs_sum_sd, 
            n = bhs_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = bhs_stats_intervention_tot$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_intervention_tot$bhs_sum_change_pre_post_sd,
             n = bhs_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = bhs_stats_control_tot$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_control_tot$bhs_sum_change_pre_post_sd,
             n = bhs_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = bhs_stats_intervention_tot$bhs_sum_change_pre_post_mean,  
        m2 = bhs_stats_control_tot$bhs_sum_change_pre_post_mean,  
        sd1 = bhs_stats_intervention_tot$bhs_sum_change_pre_post_sd,  
        sd2 = bhs_stats_control_tot$bhs_sum_change_pre_post_sd,  
        n1 = bhs_stats_intervention_tot$n,  
        n2 = bhs_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Hopelessness pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = bhs_stats_intervention_tot$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_tot$f_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_tot$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_tot$f_bhs_sum_sd, 
            n = bhs_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = bhs_stats_control_tot$b_bhs_sum_mean, 
            m2 = bhs_stats_control_tot$f_bhs_sum_mean, 
            sd1 = bhs_stats_control_tot$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_tot$f_bhs_sum_sd, 
            n = bhs_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = bhs_stats_intervention_tot$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_intervention_tot$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = bhs_stats_control_tot$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_control_tot$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = bhs_stats_intervention_tot$bhs_sum_change_pre_followup_mean,  
        m2 = bhs_stats_control_tot$bhs_sum_change_pre_followup_mean,  
        sd1 = bhs_stats_intervention_tot$bhs_sum_change_pre_followup_sd,  
        sd2 = bhs_stats_control_tot$bhs_sum_change_pre_followup_sd,  
        n1 = bhs_stats_intervention_tot$n,  
        n2 = bhs_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency descriptives

##Descriptives for intervention
shs_agency_stats_intervention_tot <- imputed_completer_intervention_quant_intervention %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
shs_agency_stats_control_tot <- imputed_completer_intervention_quant_control %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Agency pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = shs_agency_stats_intervention_tot$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_tot$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_tot$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_tot$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = shs_agency_stats_control_tot$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_tot$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_tot$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_tot$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = shs_agency_stats_control_tot$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_control_tot$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_post_mean,  
        m2 = shs_agency_stats_control_tot$shs_agency_sum_change_pre_post_mean,  
        sd1 = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_post_sd,  
        sd2 = shs_agency_stats_control_tot$shs_agency_sum_change_pre_post_sd,  
        n1 = shs_agency_stats_intervention_tot$n,  
        n2 = shs_agency_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = shs_agency_stats_intervention_tot$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_tot$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_tot$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_tot$f_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = shs_agency_stats_control_tot$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_tot$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_tot$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_tot$f_shs_agency_sum_sd, 
            n = shs_agency_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = shs_agency_stats_control_tot$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_control_tot$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_followup_mean,  
        m2 = shs_agency_stats_control_tot$shs_agency_sum_change_pre_followup_mean,  
        sd1 = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_followup_sd,  
        sd2 = shs_agency_stats_control_tot$shs_agency_sum_change_pre_followup_sd,  
        n1 = shs_agency_stats_intervention_tot$n,  
        n2 = shs_agency_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state descriptives

##Descriptives for intervention
biss_stats_intervention_tot <- imputed_completer_intervention_quant_intervention %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biss_stats_control_tot <- imputed_completer_intervention_quant_control %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image state pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = biss_stats_intervention_tot$b_biss_sum_mean, 
            m2 = biss_stats_intervention_tot$pi_biss_sum_mean, 
            sd1 = biss_stats_intervention_tot$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_tot$pi_biss_sum_sd, 
            n = biss_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biss_stats_control_tot$b_biss_sum_mean, 
            m2 = biss_stats_control_tot$pi_biss_sum_mean, 
            sd1 = biss_stats_control_tot$b_biss_sum_sd, 
            sd2 = biss_stats_control_tot$pi_biss_sum_sd, 
            n = biss_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biss_stats_intervention_tot$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_intervention_tot$biss_sum_change_pre_post_sd,
             n = biss_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biss_stats_control_tot$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_control_tot$biss_sum_change_pre_post_sd,
             n = biss_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biss_stats_intervention_tot$biss_sum_change_pre_post_mean,  
        m2 = biss_stats_control_tot$biss_sum_change_pre_post_mean,  
        sd1 = biss_stats_intervention_tot$biss_sum_change_pre_post_sd,  
        sd2 = biss_stats_control_tot$biss_sum_change_pre_post_sd,  
        n1 = biss_stats_intervention_tot$n,  
        n2 = biss_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = biss_stats_intervention_tot$b_biss_sum_mean, 
            m2 = biss_stats_intervention_tot$f_biss_sum_mean, 
            sd1 = biss_stats_intervention_tot$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_tot$f_biss_sum_sd, 
            n = biss_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biss_stats_control_tot$b_biss_sum_mean, 
            m2 = biss_stats_control_tot$f_biss_sum_mean, 
            sd1 = biss_stats_control_tot$b_biss_sum_sd, 
            sd2 = biss_stats_control_tot$f_biss_sum_sd, 
            n = biss_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biss_stats_intervention_tot$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_intervention_tot$biss_sum_change_pre_followup_sd,
             n = biss_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biss_stats_control_tot$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_control_tot$biss_sum_change_pre_followup_sd,
             n = biss_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biss_stats_intervention_tot$biss_sum_change_pre_followup_mean,  
        m2 = biss_stats_control_tot$biss_sum_change_pre_followup_mean,  
        sd1 = biss_stats_intervention_tot$biss_sum_change_pre_followup_sd,  
        sd2 = biss_stats_control_tot$biss_sum_change_pre_followup_sd,  
        n1 = biss_stats_intervention_tot$n,  
        n2 = biss_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")   
  
#Functionality appreciation descriptives

##Descriptives for intervention
fas_stats_intervention_tot <- imputed_completer_intervention_quant_intervention %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
fas_stats_control_tot <- imputed_completer_intervention_quant_control %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Functionality appreciation pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = fas_stats_intervention_tot$b_fas_sum_mean, 
            m2 = fas_stats_intervention_tot$pi_fas_sum_mean, 
            sd1 = fas_stats_intervention_tot$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_tot$pi_fas_sum_sd, 
            n = fas_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = fas_stats_control_tot$b_fas_sum_mean, 
            m2 = fas_stats_control_tot$pi_fas_sum_mean, 
            sd1 = fas_stats_control_tot$b_fas_sum_sd, 
            sd2 = fas_stats_control_tot$pi_fas_sum_sd, 
            n = fas_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = fas_stats_intervention_tot$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_intervention_tot$fas_sum_change_pre_post_sd,
             n = fas_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = fas_stats_control_tot$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_control_tot$fas_sum_change_pre_post_sd,
             n = fas_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = fas_stats_intervention_tot$fas_sum_change_pre_post_mean,  
        m2 = fas_stats_control_tot$fas_sum_change_pre_post_mean,  
        sd1 = fas_stats_intervention_tot$fas_sum_change_pre_post_sd,  
        sd2 = fas_stats_control_tot$fas_sum_change_pre_post_sd,  
        n1 = fas_stats_intervention_tot$n,  
        n2 = fas_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Functionality appreciation pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = fas_stats_intervention_tot$b_fas_sum_mean, 
            m2 = fas_stats_intervention_tot$f_fas_sum_mean, 
            sd1 = fas_stats_intervention_tot$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_tot$f_fas_sum_sd, 
            n = fas_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = fas_stats_control_tot$b_fas_sum_mean, 
            m2 = fas_stats_control_tot$f_fas_sum_mean, 
            sd1 = fas_stats_control_tot$b_fas_sum_sd, 
            sd2 = fas_stats_control_tot$f_fas_sum_sd, 
            n = fas_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = fas_stats_intervention_tot$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_intervention_tot$fas_sum_change_pre_followup_sd,
             n = fas_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = fas_stats_control_tot$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_control_tot$fas_sum_change_pre_followup_sd,
             n = fas_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = fas_stats_intervention_tot$fas_sum_change_pre_followup_mean,  
        m2 = fas_stats_control_tot$fas_sum_change_pre_followup_mean,  
        sd1 = fas_stats_intervention_tot$fas_sum_change_pre_followup_sd,  
        sd2 = fas_stats_control_tot$fas_sum_change_pre_followup_sd,  
        n1 = fas_stats_intervention_tot$n,  
        n2 = fas_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Body image flexibility descriptives

##Descriptives for intervention
biaaq_stats_intervention_tot <- imputed_completer_intervention_quant_intervention %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biaaq_stats_control_tot <- imputed_completer_intervention_quant_control %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image flexibility pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = biaaq_stats_intervention_tot$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_tot$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_tot$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_tot$pi_biaaq_sum_sd, 
            n = biaaq_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biaaq_stats_control_tot$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_tot$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_tot$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_tot$pi_biaaq_sum_sd, 
            n = biaaq_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biaaq_stats_intervention_tot$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_intervention_tot$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biaaq_stats_control_tot$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_control_tot$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biaaq_stats_intervention_tot$biaaq_sum_change_pre_post_mean,  
        m2 = biaaq_stats_control_tot$biaaq_sum_change_pre_post_mean,  
        sd1 = biaaq_stats_intervention_tot$biaaq_sum_change_pre_post_sd,  
        sd2 = biaaq_stats_control_tot$biaaq_sum_change_pre_post_sd,  
        n1 = biaaq_stats_intervention_tot$n,  
        n2 = biaaq_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image flexibility pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = biaaq_stats_intervention_tot$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_tot$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_tot$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_tot$f_biaaq_sum_sd, 
            n = biaaq_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biaaq_stats_control_tot$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_tot$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_tot$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_tot$f_biaaq_sum_sd, 
            n = biaaq_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biaaq_stats_intervention_tot$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_intervention_tot$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biaaq_stats_control_tot$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_control_tot$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biaaq_stats_intervention_tot$biaaq_sum_change_pre_followup_mean,  
        m2 = biaaq_stats_control_tot$biaaq_sum_change_pre_followup_mean,  
        sd1 = biaaq_stats_intervention_tot$biaaq_sum_change_pre_followup_sd,  
        sd2 = biaaq_stats_control_tot$biaaq_sum_change_pre_followup_sd,  
        n1 = biaaq_stats_intervention_tot$n,  
        n2 = biaaq_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness descriptives

##Descriptives for intervention
chime_stats_intervention_tot <- imputed_completer_intervention_quant_intervention %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
chime_stats_control_tot <- imputed_completer_intervention_quant_control %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body-related mindfulness pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = chime_stats_intervention_tot$b_chime_sum_mean, 
            m2 = chime_stats_intervention_tot$pi_chime_sum_mean, 
            sd1 = chime_stats_intervention_tot$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_tot$pi_chime_sum_sd, 
            n = chime_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = chime_stats_control_tot$b_chime_sum_mean, 
            m2 = chime_stats_control_tot$pi_chime_sum_mean, 
            sd1 = chime_stats_control_tot$b_chime_sum_sd, 
            sd2 = chime_stats_control_tot$pi_chime_sum_sd, 
            n = chime_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = chime_stats_intervention_tot$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_intervention_tot$chime_sum_change_pre_post_sd,
             n = chime_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = chime_stats_control_tot$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_control_tot$chime_sum_change_pre_post_sd,
             n = chime_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = chime_stats_intervention_tot$chime_sum_change_pre_post_mean,  
        m2 = chime_stats_control_tot$chime_sum_change_pre_post_mean,  
        sd1 = chime_stats_intervention_tot$chime_sum_change_pre_post_sd,  
        sd2 = chime_stats_control_tot$chime_sum_change_pre_post_sd,  
        n1 = chime_stats_intervention_tot$n,  
        n2 = chime_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = chime_stats_intervention_tot$b_chime_sum_mean, 
            m2 = chime_stats_intervention_tot$f_chime_sum_mean, 
            sd1 = chime_stats_intervention_tot$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_tot$f_chime_sum_sd, 
            n = chime_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = chime_stats_control_tot$b_chime_sum_mean, 
            m2 = chime_stats_control_tot$f_chime_sum_mean, 
            sd1 = chime_stats_control_tot$b_chime_sum_sd, 
            sd2 = chime_stats_control_tot$f_chime_sum_sd, 
            n = chime_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = chime_stats_intervention_tot$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_intervention_tot$chime_sum_change_pre_followup_sd,
             n = chime_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = chime_stats_control_tot$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_control_tot$chime_sum_change_pre_followup_sd,
             n = chime_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = chime_stats_intervention_tot$chime_sum_change_pre_followup_mean,  
        m2 = chime_stats_control_tot$chime_sum_change_pre_followup_mean,  
        sd1 = chime_stats_intervention_tot$chime_sum_change_pre_followup_sd,  
        sd2 = chime_stats_control_tot$chime_sum_change_pre_followup_sd,  
        n1 = chime_stats_intervention_tot$n,  
        n2 = chime_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Depression symptoms descriptives

##Descriptives for intervention
mfq_stats_intervention_tot <- imputed_completer_intervention_quant_intervention %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mfq_stats_control_tot <- imputed_completer_intervention_quant_control %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Depression symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = mfq_stats_intervention_tot$b_mfq_sum_mean, 
            m2 = mfq_stats_intervention_tot$f_mfq_sum_mean, 
            sd1 = mfq_stats_intervention_tot$b_mfq_sum_sd, 
            sd2 = mfq_stats_intervention_tot$f_mfq_sum_sd, 
            n = mfq_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = mfq_stats_control_tot$b_mfq_sum_mean, 
            m2 = mfq_stats_control_tot$f_mfq_sum_mean, 
            sd1 = mfq_stats_control_tot$b_mfq_sum_sd, 
            sd2 = mfq_stats_control_tot$f_mfq_sum_sd, 
            n = mfq_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = mfq_stats_intervention_tot$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_intervention_tot$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = mfq_stats_control_tot$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_control_tot$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = mfq_stats_intervention_tot$mfq_sum_change_pre_followup_mean,  
        m2 = mfq_stats_control_tot$mfq_sum_change_pre_followup_mean,  
        sd1 = mfq_stats_intervention_tot$mfq_sum_change_pre_followup_sd,  
        sd2 = mfq_stats_control_tot$mfq_sum_change_pre_followup_sd,  
        n1 = mfq_stats_intervention_tot$n,  
        n2 = mfq_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Eating disorder symptoms descriptives

##Descriptives for intervention
edeq_stats_intervention_tot <- imputed_completer_intervention_quant_intervention %>%
  select(b_edeq_sum, f_edeq_sum) %>%
  mutate(edeq_sum_change_pre_followup = f_edeq_sum - b_edeq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
edeq_stats_control_tot <- imputed_completer_intervention_quant_control %>%
  select(b_edeq_sum, f_edeq_sum) %>%
  mutate(edeq_sum_change_pre_followup = f_edeq_sum - b_edeq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Eating disorder symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = edeq_stats_intervention_tot$b_edeq_sum_mean, 
            m2 = edeq_stats_intervention_tot$f_edeq_sum_mean, 
            sd1 = edeq_stats_intervention_tot$b_edeq_sum_sd, 
            sd2 = edeq_stats_intervention_tot$f_edeq_sum_sd, 
            n = edeq_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = edeq_stats_control_tot$b_edeq_sum_mean, 
            m2 = edeq_stats_control_tot$f_edeq_sum_mean, 
            sd1 = edeq_stats_control_tot$b_edeq_sum_sd, 
            sd2 = edeq_stats_control_tot$f_edeq_sum_sd, 
            n = edeq_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = edeq_stats_intervention_tot$edeq_sum_change_pre_followup_mean,
             sddiff = edeq_stats_intervention_tot$edeq_sum_change_pre_followup_sd,
             n = edeq_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = edeq_stats_control_tot$edeq_sum_change_pre_followup_mean,
             sddiff = edeq_stats_control_tot$edeq_sum_change_pre_followup_sd,
             n = edeq_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = edeq_stats_intervention_tot$edeq_sum_change_pre_followup_mean,  
        m2 = edeq_stats_control_tot$edeq_sum_change_pre_followup_mean,  
        sd1 = edeq_stats_intervention_tot$edeq_sum_change_pre_followup_sd,  
        sd2 = edeq_stats_control_tot$edeq_sum_change_pre_followup_sd,  
        n1 = edeq_stats_intervention_tot$n,  
        n2 = edeq_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Muscle dysmorphia symptoms descriptives

##Descriptives for intervention
mddi_stats_intervention_tot <- imputed_completer_intervention_quant_intervention %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mddi_stats_control_tot <- imputed_completer_intervention_quant_control %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Muscle dysmorphia symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = mddi_stats_intervention_tot$b_mddi_sum_mean, 
            m2 = mddi_stats_intervention_tot$f_mddi_sum_mean, 
            sd1 = mddi_stats_intervention_tot$b_mddi_sum_sd, 
            sd2 = mddi_stats_intervention_tot$f_mddi_sum_sd, 
            n = mddi_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = mddi_stats_control_tot$b_mddi_sum_mean, 
            m2 = mddi_stats_control_tot$f_mddi_sum_mean, 
            sd1 = mddi_stats_control_tot$b_mddi_sum_sd, 
            sd2 = mddi_stats_control_tot$f_mddi_sum_sd, 
            n = mddi_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = mddi_stats_intervention_tot$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_intervention_tot$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = mddi_stats_control_tot$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_control_tot$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = mddi_stats_intervention_tot$mddi_sum_change_pre_followup_mean,  
        m2 = mddi_stats_control_tot$mddi_sum_change_pre_followup_mean,  
        sd1 = mddi_stats_intervention_tot$mddi_sum_change_pre_followup_sd,  
        sd2 = mddi_stats_control_tot$mddi_sum_change_pre_followup_sd,  
        n1 = mddi_stats_intervention_tot$n,  
        n2 = mddi_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")
```

```{r effect sizes - baseline completers}
#Make new dataframes to separate Intervention and Control folks (with imputed data)
imputed_completer_baseline_quant_intervention <- imputed_completer_baseline_quant %>% 
  filter(treatment_group == "Intervention")

imputed_completer_baseline_quant_control <- imputed_completer_baseline_quant %>% 
  filter(treatment_group == "Control")

#Hopelessness descriptives

##Descriptives for intervention
bhs_stats_intervention_b <- imputed_completer_baseline_quant_intervention %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
bhs_stats_control_b <- imputed_completer_baseline_quant_control %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Hopelessness pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = bhs_stats_intervention_b$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_b$pi_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_b$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_b$pi_bhs_sum_sd, 
            n = bhs_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = bhs_stats_control_b$b_bhs_sum_mean, 
            m2 = bhs_stats_control_b$pi_bhs_sum_mean, 
            sd1 = bhs_stats_control_b$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_b$pi_bhs_sum_sd, 
            n = bhs_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = bhs_stats_intervention_b$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_intervention_b$bhs_sum_change_pre_post_sd,
             n = bhs_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = bhs_stats_control_b$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_control_b$bhs_sum_change_pre_post_sd,
             n = bhs_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = bhs_stats_intervention_b$bhs_sum_change_pre_post_mean,  
        m2 = bhs_stats_control_b$bhs_sum_change_pre_post_mean,  
        sd1 = bhs_stats_intervention_b$bhs_sum_change_pre_post_sd,  
        sd2 = bhs_stats_control_b$bhs_sum_change_pre_post_sd,  
        n1 = bhs_stats_intervention_b$n,  
        n2 = bhs_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Hopelessness pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = bhs_stats_intervention_b$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_b$f_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_b$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_b$f_bhs_sum_sd, 
            n = bhs_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = bhs_stats_control_b$b_bhs_sum_mean, 
            m2 = bhs_stats_control_b$f_bhs_sum_mean, 
            sd1 = bhs_stats_control_b$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_b$f_bhs_sum_sd, 
            n = bhs_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = bhs_stats_intervention_b$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_intervention_b$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = bhs_stats_control_b$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_control_b$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = bhs_stats_intervention_b$bhs_sum_change_pre_followup_mean,  
        m2 = bhs_stats_control_b$bhs_sum_change_pre_followup_mean,  
        sd1 = bhs_stats_intervention_b$bhs_sum_change_pre_followup_sd,  
        sd2 = bhs_stats_control_b$bhs_sum_change_pre_followup_sd,  
        n1 = bhs_stats_intervention_b$n,  
        n2 = bhs_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency descriptives

##Descriptives for intervention
shs_agency_stats_intervention_b <- imputed_completer_baseline_quant_intervention %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
shs_agency_stats_control_b <- imputed_completer_baseline_quant_control %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Agency pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = shs_agency_stats_intervention_b$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_b$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_b$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_b$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = shs_agency_stats_control_b$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_b$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_b$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_b$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = shs_agency_stats_intervention_b$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_intervention_b$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = shs_agency_stats_control_b$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_control_b$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = shs_agency_stats_intervention_b$shs_agency_sum_change_pre_post_mean,  
        m2 = shs_agency_stats_control_b$shs_agency_sum_change_pre_post_mean,  
        sd1 = shs_agency_stats_intervention_b$shs_agency_sum_change_pre_post_sd,  
        sd2 = shs_agency_stats_control_b$shs_agency_sum_change_pre_post_sd,  
        n1 = shs_agency_stats_intervention_b$n,  
        n2 = shs_agency_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = shs_agency_stats_intervention_b$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_b$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_b$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_b$f_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = shs_agency_stats_control_b$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_b$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_b$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_b$f_shs_agency_sum_sd, 
            n = shs_agency_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = shs_agency_stats_intervention_b$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_intervention_b$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = shs_agency_stats_control_b$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_control_b$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = shs_agency_stats_intervention_b$shs_agency_sum_change_pre_followup_mean,  
        m2 = shs_agency_stats_control_b$shs_agency_sum_change_pre_followup_mean,  
        sd1 = shs_agency_stats_intervention_b$shs_agency_sum_change_pre_followup_sd,  
        sd2 = shs_agency_stats_control_b$shs_agency_sum_change_pre_followup_sd,  
        n1 = shs_agency_stats_intervention_b$n,  
        n2 = shs_agency_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state descriptives

##Descriptives for intervention
biss_stats_intervention_b <- imputed_completer_baseline_quant_intervention %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biss_stats_control_b <- imputed_completer_baseline_quant_control %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image state pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = biss_stats_intervention_b$b_biss_sum_mean, 
            m2 = biss_stats_intervention_b$pi_biss_sum_mean, 
            sd1 = biss_stats_intervention_b$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_b$pi_biss_sum_sd, 
            n = biss_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biss_stats_control_b$b_biss_sum_mean, 
            m2 = biss_stats_control_b$pi_biss_sum_mean, 
            sd1 = biss_stats_control_b$b_biss_sum_sd, 
            sd2 = biss_stats_control_b$pi_biss_sum_sd, 
            n = biss_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biss_stats_intervention_b$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_intervention_b$biss_sum_change_pre_post_sd,
             n = biss_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biss_stats_control_b$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_control_b$biss_sum_change_pre_post_sd,
             n = biss_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biss_stats_intervention_b$biss_sum_change_pre_post_mean,  
        m2 = biss_stats_control_b$biss_sum_change_pre_post_mean,  
        sd1 = biss_stats_intervention_b$biss_sum_change_pre_post_sd,  
        sd2 = biss_stats_control_b$biss_sum_change_pre_post_sd,  
        n1 = biss_stats_intervention_b$n,  
        n2 = biss_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = biss_stats_intervention_b$b_biss_sum_mean, 
            m2 = biss_stats_intervention_b$f_biss_sum_mean, 
            sd1 = biss_stats_intervention_b$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_b$f_biss_sum_sd, 
            n = biss_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biss_stats_control_b$b_biss_sum_mean, 
            m2 = biss_stats_control_b$f_biss_sum_mean, 
            sd1 = biss_stats_control_b$b_biss_sum_sd, 
            sd2 = biss_stats_control_b$f_biss_sum_sd, 
            n = biss_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biss_stats_intervention_b$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_intervention_b$biss_sum_change_pre_followup_sd,
             n = biss_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biss_stats_control_b$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_control_b$biss_sum_change_pre_followup_sd,
             n = biss_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biss_stats_intervention_b$biss_sum_change_pre_followup_mean,  
        m2 = biss_stats_control_b$biss_sum_change_pre_followup_mean,  
        sd1 = biss_stats_intervention_b$biss_sum_change_pre_followup_sd,  
        sd2 = biss_stats_control_b$biss_sum_change_pre_followup_sd,  
        n1 = biss_stats_intervention_b$n,  
        n2 = biss_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")   
  
#Functionality appreciation descriptives

##Descriptives for intervention
fas_stats_intervention_b <- imputed_completer_baseline_quant_intervention %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
fas_stats_control_b <- imputed_completer_baseline_quant_control %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Functionality appreciation pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = fas_stats_intervention_b$b_fas_sum_mean, 
            m2 = fas_stats_intervention_b$pi_fas_sum_mean, 
            sd1 = fas_stats_intervention_b$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_b$pi_fas_sum_sd, 
            n = fas_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = fas_stats_control_b$b_fas_sum_mean, 
            m2 = fas_stats_control_b$pi_fas_sum_mean, 
            sd1 = fas_stats_control_b$b_fas_sum_sd, 
            sd2 = fas_stats_control_b$pi_fas_sum_sd, 
            n = fas_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = fas_stats_intervention_b$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_intervention_b$fas_sum_change_pre_post_sd,
             n = fas_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = fas_stats_control_b$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_control_b$fas_sum_change_pre_post_sd,
             n = fas_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = fas_stats_intervention_b$fas_sum_change_pre_post_mean,  
        m2 = fas_stats_control_b$fas_sum_change_pre_post_mean,  
        sd1 = fas_stats_intervention_b$fas_sum_change_pre_post_sd,  
        sd2 = fas_stats_control_b$fas_sum_change_pre_post_sd,  
        n1 = fas_stats_intervention_b$n,  
        n2 = fas_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Functionality appreciation pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = fas_stats_intervention_b$b_fas_sum_mean, 
            m2 = fas_stats_intervention_b$f_fas_sum_mean, 
            sd1 = fas_stats_intervention_b$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_b$f_fas_sum_sd, 
            n = fas_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = fas_stats_control_b$b_fas_sum_mean, 
            m2 = fas_stats_control_b$f_fas_sum_mean, 
            sd1 = fas_stats_control_b$b_fas_sum_sd, 
            sd2 = fas_stats_control_b$f_fas_sum_sd, 
            n = fas_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = fas_stats_intervention_b$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_intervention_b$fas_sum_change_pre_followup_sd,
             n = fas_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = fas_stats_control_b$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_control_b$fas_sum_change_pre_followup_sd,
             n = fas_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = fas_stats_intervention_b$fas_sum_change_pre_followup_mean,  
        m2 = fas_stats_control_b$fas_sum_change_pre_followup_mean,  
        sd1 = fas_stats_intervention_b$fas_sum_change_pre_followup_sd,  
        sd2 = fas_stats_control_b$fas_sum_change_pre_followup_sd,  
        n1 = fas_stats_intervention_b$n,  
        n2 = fas_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Body image flexibility descriptives

##Descriptives for intervention
biaaq_stats_intervention_b <- imputed_completer_baseline_quant_intervention %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biaaq_stats_control_b <- imputed_completer_baseline_quant_control %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image flexibility pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = biaaq_stats_intervention_b$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_b$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_b$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_b$pi_biaaq_sum_sd, 
            n = biaaq_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biaaq_stats_control_b$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_b$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_b$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_b$pi_biaaq_sum_sd, 
            n = biaaq_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biaaq_stats_intervention_b$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_intervention_b$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biaaq_stats_control_b$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_control_b$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biaaq_stats_intervention_b$biaaq_sum_change_pre_post_mean,  
        m2 = biaaq_stats_control_b$biaaq_sum_change_pre_post_mean,  
        sd1 = biaaq_stats_intervention_b$biaaq_sum_change_pre_post_sd,  
        sd2 = biaaq_stats_control_b$biaaq_sum_change_pre_post_sd,  
        n1 = biaaq_stats_intervention_b$n,  
        n2 = biaaq_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image flexibility pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = biaaq_stats_intervention_b$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_b$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_b$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_b$f_biaaq_sum_sd, 
            n = biaaq_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biaaq_stats_control_b$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_b$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_b$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_b$f_biaaq_sum_sd, 
            n = biaaq_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biaaq_stats_intervention_b$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_intervention_b$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biaaq_stats_control_b$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_control_b$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biaaq_stats_intervention_b$biaaq_sum_change_pre_followup_mean,  
        m2 = biaaq_stats_control_b$biaaq_sum_change_pre_followup_mean,  
        sd1 = biaaq_stats_intervention_b$biaaq_sum_change_pre_followup_sd,  
        sd2 = biaaq_stats_control_b$biaaq_sum_change_pre_followup_sd,  
        n1 = biaaq_stats_intervention_b$n,  
        n2 = biaaq_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness descriptives

##Descriptives for intervention
chime_stats_intervention_b <- imputed_completer_baseline_quant_intervention %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
chime_stats_control_b <- imputed_completer_baseline_quant_control %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body-related mindfulness pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = chime_stats_intervention_b$b_chime_sum_mean, 
            m2 = chime_stats_intervention_b$pi_chime_sum_mean, 
            sd1 = chime_stats_intervention_b$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_b$pi_chime_sum_sd, 
            n = chime_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = chime_stats_control_b$b_chime_sum_mean, 
            m2 = chime_stats_control_b$pi_chime_sum_mean, 
            sd1 = chime_stats_control_b$b_chime_sum_sd, 
            sd2 = chime_stats_control_b$pi_chime_sum_sd, 
            n = chime_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = chime_stats_intervention_b$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_intervention_b$chime_sum_change_pre_post_sd,
             n = chime_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = chime_stats_control_b$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_control_b$chime_sum_change_pre_post_sd,
             n = chime_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = chime_stats_intervention_b$chime_sum_change_pre_post_mean,  
        m2 = chime_stats_control_b$chime_sum_change_pre_post_mean,  
        sd1 = chime_stats_intervention_b$chime_sum_change_pre_post_sd,  
        sd2 = chime_stats_control_b$chime_sum_change_pre_post_sd,  
        n1 = chime_stats_intervention_b$n,  
        n2 = chime_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = chime_stats_intervention_b$b_chime_sum_mean, 
            m2 = chime_stats_intervention_b$f_chime_sum_mean, 
            sd1 = chime_stats_intervention_b$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_b$f_chime_sum_sd, 
            n = chime_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = chime_stats_control_b$b_chime_sum_mean, 
            m2 = chime_stats_control_b$f_chime_sum_mean, 
            sd1 = chime_stats_control_b$b_chime_sum_sd, 
            sd2 = chime_stats_control_b$f_chime_sum_sd, 
            n = chime_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = chime_stats_intervention_b$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_intervention_b$chime_sum_change_pre_followup_sd,
             n = chime_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = chime_stats_control_b$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_control_b$chime_sum_change_pre_followup_sd,
             n = chime_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = chime_stats_intervention_b$chime_sum_change_pre_followup_mean,  
        m2 = chime_stats_control_b$chime_sum_change_pre_followup_mean,  
        sd1 = chime_stats_intervention_b$chime_sum_change_pre_followup_sd,  
        sd2 = chime_stats_control_b$chime_sum_change_pre_followup_sd,  
        n1 = chime_stats_intervention_b$n,  
        n2 = chime_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Depression symptoms descriptives

##Descriptives for intervention
mfq_stats_intervention_b <- imputed_completer_baseline_quant_intervention %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mfq_stats_control_b <- imputed_completer_baseline_quant_control %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Depression symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = mfq_stats_intervention_b$b_mfq_sum_mean, 
            m2 = mfq_stats_intervention_b$f_mfq_sum_mean, 
            sd1 = mfq_stats_intervention_b$b_mfq_sum_sd, 
            sd2 = mfq_stats_intervention_b$f_mfq_sum_sd, 
            n = mfq_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = mfq_stats_control_b$b_mfq_sum_mean, 
            m2 = mfq_stats_control_b$f_mfq_sum_mean, 
            sd1 = mfq_stats_control_b$b_mfq_sum_sd, 
            sd2 = mfq_stats_control_b$f_mfq_sum_sd, 
            n = mfq_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = mfq_stats_intervention_b$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_intervention_b$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = mfq_stats_control_b$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_control_b$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = mfq_stats_intervention_b$mfq_sum_change_pre_followup_mean,  
        m2 = mfq_stats_control_b$mfq_sum_change_pre_followup_mean,  
        sd1 = mfq_stats_intervention_b$mfq_sum_change_pre_followup_sd,  
        sd2 = mfq_stats_control_b$mfq_sum_change_pre_followup_sd,  
        n1 = mfq_stats_intervention_b$n,  
        n2 = mfq_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Eating disorder symptoms descriptives

##Descriptives for intervention
edeq_stats_intervention_b <- imputed_completer_baseline_quant_intervention %>%
  select(b_edeq_sum, f_edeq_sum) %>%
  mutate(edeq_sum_change_pre_followup = f_edeq_sum - b_edeq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
edeq_stats_control_b <- imputed_completer_baseline_quant_control %>%
  select(b_edeq_sum, f_edeq_sum) %>%
  mutate(edeq_sum_change_pre_followup = f_edeq_sum - b_edeq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Eating disorder symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = edeq_stats_intervention_b$b_edeq_sum_mean, 
            m2 = edeq_stats_intervention_b$f_edeq_sum_mean, 
            sd1 = edeq_stats_intervention_b$b_edeq_sum_sd, 
            sd2 = edeq_stats_intervention_b$f_edeq_sum_sd, 
            n = edeq_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = edeq_stats_control_b$b_edeq_sum_mean, 
            m2 = edeq_stats_control_b$f_edeq_sum_mean, 
            sd1 = edeq_stats_control_b$b_edeq_sum_sd, 
            sd2 = edeq_stats_control_b$f_edeq_sum_sd, 
            n = edeq_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = edeq_stats_intervention_b$edeq_sum_change_pre_followup_mean,
             sddiff = edeq_stats_intervention_b$edeq_sum_change_pre_followup_sd,
             n = edeq_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = edeq_stats_control_b$edeq_sum_change_pre_followup_mean,
             sddiff = edeq_stats_control_b$edeq_sum_change_pre_followup_sd,
             n = edeq_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = edeq_stats_intervention_b$edeq_sum_change_pre_followup_mean,  
        m2 = edeq_stats_control_b$edeq_sum_change_pre_followup_mean,  
        sd1 = edeq_stats_intervention_b$edeq_sum_change_pre_followup_sd,  
        sd2 = edeq_stats_control_b$edeq_sum_change_pre_followup_sd,  
        n1 = edeq_stats_intervention_b$n,  
        n2 = edeq_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")

#Muscle dysmorphia symptoms descriptives

##Descriptives for intervention
mddi_stats_intervention_b <- imputed_completer_baseline_quant_intervention %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mddi_stats_control_b <- imputed_completer_baseline_quant_control %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Muscle dysmorphia symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = mddi_stats_intervention_b$b_mddi_sum_mean, 
            m2 = mddi_stats_intervention_b$f_mddi_sum_mean, 
            sd1 = mddi_stats_intervention_b$b_mddi_sum_sd, 
            sd2 = mddi_stats_intervention_b$f_mddi_sum_sd, 
            n = mddi_stats_intervention_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = mddi_stats_control_b$b_mddi_sum_mean, 
            m2 = mddi_stats_control_b$f_mddi_sum_mean, 
            sd1 = mddi_stats_control_b$b_mddi_sum_sd, 
            sd2 = mddi_stats_control_b$f_mddi_sum_sd, 
            n = mddi_stats_control_b$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = mddi_stats_intervention_b$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_intervention_b$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_intervention_b$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = mddi_stats_control_b$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_control_b$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_control_b$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = mddi_stats_intervention_b$mddi_sum_change_pre_followup_mean,  
        m2 = mddi_stats_control_b$mddi_sum_change_pre_followup_mean,  
        sd1 = mddi_stats_intervention_b$mddi_sum_change_pre_followup_sd,  
        sd2 = mddi_stats_control_b$mddi_sum_change_pre_followup_sd,  
        n1 = mddi_stats_intervention_b$n,  
        n2 = mddi_stats_control_b$n,  
        a = 0.05) %>%
  pluck("estimate")
```

```{r effect sizes - followup completers}
#Make new dataframes to separate Intervention and Control folks (no imputation)
completer_followup_quant_intervention <- completer_followup_quant %>% 
  filter(treatment_group == "Intervention")

completer_followup_quant_control <- completer_followup_quant %>% 
  filter(treatment_group == "Control")

#Hopelessness descriptives

##Descriptives for intervention
bhs_stats_intervention_f <- completer_followup_quant_intervention %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
bhs_stats_control_f <- completer_followup_quant_control %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Hopelessness pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = bhs_stats_intervention_f$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_f$pi_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_f$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_f$pi_bhs_sum_sd, 
            n = bhs_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = bhs_stats_control_f$b_bhs_sum_mean, 
            m2 = bhs_stats_control_f$pi_bhs_sum_mean, 
            sd1 = bhs_stats_control_f$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_f$pi_bhs_sum_sd, 
            n = bhs_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = bhs_stats_intervention_f$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_intervention_f$bhs_sum_change_pre_post_sd,
             n = bhs_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = bhs_stats_control_f$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_control_f$bhs_sum_change_pre_post_sd,
             n = bhs_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = bhs_stats_intervention_f$bhs_sum_change_pre_post_mean,  
        m2 = bhs_stats_control_f$bhs_sum_change_pre_post_mean,  
        sd1 = bhs_stats_intervention_f$bhs_sum_change_pre_post_sd,  
        sd2 = bhs_stats_control_f$bhs_sum_change_pre_post_sd,  
        n1 = bhs_stats_intervention_f$n,  
        n2 = bhs_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Hopelessness pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = bhs_stats_intervention_f$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_f$f_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_f$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_f$f_bhs_sum_sd, 
            n = bhs_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = bhs_stats_control_f$b_bhs_sum_mean, 
            m2 = bhs_stats_control_f$f_bhs_sum_mean, 
            sd1 = bhs_stats_control_f$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_f$f_bhs_sum_sd, 
            n = bhs_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = bhs_stats_intervention_f$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_intervention_f$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = bhs_stats_control_f$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_control_f$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = bhs_stats_intervention_f$bhs_sum_change_pre_followup_mean,  
        m2 = bhs_stats_control_f$bhs_sum_change_pre_followup_mean,  
        sd1 = bhs_stats_intervention_f$bhs_sum_change_pre_followup_sd,  
        sd2 = bhs_stats_control_f$bhs_sum_change_pre_followup_sd,  
        n1 = bhs_stats_intervention_f$n,  
        n2 = bhs_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency descriptives

##Descriptives for intervention
shs_agency_stats_intervention_f <- completer_followup_quant_intervention %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
shs_agency_stats_control_f <- completer_followup_quant_control %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Agency pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = shs_agency_stats_intervention_f$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_f$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_f$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_f$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = shs_agency_stats_control_f$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_f$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_f$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_f$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = shs_agency_stats_intervention_f$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_intervention_f$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = shs_agency_stats_control_f$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_control_f$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = shs_agency_stats_intervention_f$shs_agency_sum_change_pre_post_mean,  
        m2 = shs_agency_stats_control_f$shs_agency_sum_change_pre_post_mean,  
        sd1 = shs_agency_stats_intervention_f$shs_agency_sum_change_pre_post_sd,  
        sd2 = shs_agency_stats_control_f$shs_agency_sum_change_pre_post_sd,  
        n1 = shs_agency_stats_intervention_f$n,  
        n2 = shs_agency_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = shs_agency_stats_intervention_f$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_f$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_f$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_f$f_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = shs_agency_stats_control_f$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_f$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_f$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_f$f_shs_agency_sum_sd, 
            n = shs_agency_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = shs_agency_stats_intervention_f$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_intervention_f$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = shs_agency_stats_control_f$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_control_f$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = shs_agency_stats_intervention_f$shs_agency_sum_change_pre_followup_mean,  
        m2 = shs_agency_stats_control_f$shs_agency_sum_change_pre_followup_mean,  
        sd1 = shs_agency_stats_intervention_f$shs_agency_sum_change_pre_followup_sd,  
        sd2 = shs_agency_stats_control_f$shs_agency_sum_change_pre_followup_sd,  
        n1 = shs_agency_stats_intervention_f$n,  
        n2 = shs_agency_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state descriptives

##Descriptives for intervention
biss_stats_intervention_f <- completer_followup_quant_intervention %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biss_stats_control_f <- completer_followup_quant_control %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image state pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = biss_stats_intervention_f$b_biss_sum_mean, 
            m2 = biss_stats_intervention_f$pi_biss_sum_mean, 
            sd1 = biss_stats_intervention_f$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_f$pi_biss_sum_sd, 
            n = biss_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biss_stats_control_f$b_biss_sum_mean, 
            m2 = biss_stats_control_f$pi_biss_sum_mean, 
            sd1 = biss_stats_control_f$b_biss_sum_sd, 
            sd2 = biss_stats_control_f$pi_biss_sum_sd, 
            n = biss_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biss_stats_intervention_f$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_intervention_f$biss_sum_change_pre_post_sd,
             n = biss_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biss_stats_control_f$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_control_f$biss_sum_change_pre_post_sd,
             n = biss_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biss_stats_intervention_f$biss_sum_change_pre_post_mean,  
        m2 = biss_stats_control_f$biss_sum_change_pre_post_mean,  
        sd1 = biss_stats_intervention_f$biss_sum_change_pre_post_sd,  
        sd2 = biss_stats_control_f$biss_sum_change_pre_post_sd,  
        n1 = biss_stats_intervention_f$n,  
        n2 = biss_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = biss_stats_intervention_f$b_biss_sum_mean, 
            m2 = biss_stats_intervention_f$f_biss_sum_mean, 
            sd1 = biss_stats_intervention_f$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_f$f_biss_sum_sd, 
            n = biss_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biss_stats_control_f$b_biss_sum_mean, 
            m2 = biss_stats_control_f$f_biss_sum_mean, 
            sd1 = biss_stats_control_f$b_biss_sum_sd, 
            sd2 = biss_stats_control_f$f_biss_sum_sd, 
            n = biss_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biss_stats_intervention_f$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_intervention_f$biss_sum_change_pre_followup_sd,
             n = biss_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biss_stats_control_f$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_control_f$biss_sum_change_pre_followup_sd,
             n = biss_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biss_stats_intervention_f$biss_sum_change_pre_followup_mean,  
        m2 = biss_stats_control_f$biss_sum_change_pre_followup_mean,  
        sd1 = biss_stats_intervention_f$biss_sum_change_pre_followup_sd,  
        sd2 = biss_stats_control_f$biss_sum_change_pre_followup_sd,  
        n1 = biss_stats_intervention_f$n,  
        n2 = biss_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")   
  
#Functionality appreciation descriptives

##Descriptives for intervention
fas_stats_intervention_f <- completer_followup_quant_intervention %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
fas_stats_control_f <- completer_followup_quant_control %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Functionality appreciation pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = fas_stats_intervention_f$b_fas_sum_mean, 
            m2 = fas_stats_intervention_f$pi_fas_sum_mean, 
            sd1 = fas_stats_intervention_f$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_f$pi_fas_sum_sd, 
            n = fas_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = fas_stats_control_f$b_fas_sum_mean, 
            m2 = fas_stats_control_f$pi_fas_sum_mean, 
            sd1 = fas_stats_control_f$b_fas_sum_sd, 
            sd2 = fas_stats_control_f$pi_fas_sum_sd, 
            n = fas_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = fas_stats_intervention_f$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_intervention_f$fas_sum_change_pre_post_sd,
             n = fas_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = fas_stats_control_f$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_control_f$fas_sum_change_pre_post_sd,
             n = fas_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = fas_stats_intervention_f$fas_sum_change_pre_post_mean,  
        m2 = fas_stats_control_f$fas_sum_change_pre_post_mean,  
        sd1 = fas_stats_intervention_f$fas_sum_change_pre_post_sd,  
        sd2 = fas_stats_control_f$fas_sum_change_pre_post_sd,  
        n1 = fas_stats_intervention_f$n,  
        n2 = fas_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Functionality appreciation pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = fas_stats_intervention_f$b_fas_sum_mean, 
            m2 = fas_stats_intervention_f$f_fas_sum_mean, 
            sd1 = fas_stats_intervention_f$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_f$f_fas_sum_sd, 
            n = fas_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = fas_stats_control_f$b_fas_sum_mean, 
            m2 = fas_stats_control_f$f_fas_sum_mean, 
            sd1 = fas_stats_control_f$b_fas_sum_sd, 
            sd2 = fas_stats_control_f$f_fas_sum_sd, 
            n = fas_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = fas_stats_intervention_f$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_intervention_f$fas_sum_change_pre_followup_sd,
             n = fas_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = fas_stats_control_f$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_control_f$fas_sum_change_pre_followup_sd,
             n = fas_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = fas_stats_intervention_f$fas_sum_change_pre_followup_mean,  
        m2 = fas_stats_control_f$fas_sum_change_pre_followup_mean,  
        sd1 = fas_stats_intervention_f$fas_sum_change_pre_followup_sd,  
        sd2 = fas_stats_control_f$fas_sum_change_pre_followup_sd,  
        n1 = fas_stats_intervention_f$n,  
        n2 = fas_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Body image flexibility descriptives

##Descriptives for intervention
biaaq_stats_intervention_f <- completer_followup_quant_intervention %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biaaq_stats_control_f <- completer_followup_quant_control %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image flexibility pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = biaaq_stats_intervention_f$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_f$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_f$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_f$pi_biaaq_sum_sd, 
            n = biaaq_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biaaq_stats_control_f$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_f$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_f$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_f$pi_biaaq_sum_sd, 
            n = biaaq_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biaaq_stats_intervention_f$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_intervention_f$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biaaq_stats_control_f$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_control_f$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biaaq_stats_intervention_f$biaaq_sum_change_pre_post_mean,  
        m2 = biaaq_stats_control_f$biaaq_sum_change_pre_post_mean,  
        sd1 = biaaq_stats_intervention_f$biaaq_sum_change_pre_post_sd,  
        sd2 = biaaq_stats_control_f$biaaq_sum_change_pre_post_sd,  
        n1 = biaaq_stats_intervention_f$n,  
        n2 = biaaq_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image flexibility pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = biaaq_stats_intervention_f$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_f$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_f$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_f$f_biaaq_sum_sd, 
            n = biaaq_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = biaaq_stats_control_f$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_f$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_f$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_f$f_biaaq_sum_sd, 
            n = biaaq_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = biaaq_stats_intervention_f$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_intervention_f$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = biaaq_stats_control_f$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_control_f$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = biaaq_stats_intervention_f$biaaq_sum_change_pre_followup_mean,  
        m2 = biaaq_stats_control_f$biaaq_sum_change_pre_followup_mean,  
        sd1 = biaaq_stats_intervention_f$biaaq_sum_change_pre_followup_sd,  
        sd2 = biaaq_stats_control_f$biaaq_sum_change_pre_followup_sd,  
        n1 = biaaq_stats_intervention_f$n,  
        n2 = biaaq_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness descriptives

##Descriptives for intervention
chime_stats_intervention_f <- completer_followup_quant_intervention %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
chime_stats_control_f <- completer_followup_quant_control %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body-related mindfulness pre-post

##within-in person d(av) for intervention
d.dep.t.avg(m1 = chime_stats_intervention_f$b_chime_sum_mean, 
            m2 = chime_stats_intervention_f$pi_chime_sum_mean, 
            sd1 = chime_stats_intervention_f$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_f$pi_chime_sum_sd, 
            n = chime_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = chime_stats_control_f$b_chime_sum_mean, 
            m2 = chime_stats_control_f$pi_chime_sum_mean, 
            sd1 = chime_stats_control_f$b_chime_sum_sd, 
            sd2 = chime_stats_control_f$pi_chime_sum_sd, 
            n = chime_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = chime_stats_intervention_f$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_intervention_f$chime_sum_change_pre_post_sd,
             n = chime_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = chime_stats_control_f$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_control_f$chime_sum_change_pre_post_sd,
             n = chime_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = chime_stats_intervention_f$chime_sum_change_pre_post_mean,  
        m2 = chime_stats_control_f$chime_sum_change_pre_post_mean,  
        sd1 = chime_stats_intervention_f$chime_sum_change_pre_post_sd,  
        sd2 = chime_stats_control_f$chime_sum_change_pre_post_sd,  
        n1 = chime_stats_intervention_f$n,  
        n2 = chime_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = chime_stats_intervention_f$b_chime_sum_mean, 
            m2 = chime_stats_intervention_f$f_chime_sum_mean, 
            sd1 = chime_stats_intervention_f$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_f$f_chime_sum_sd, 
            n = chime_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = chime_stats_control_f$b_chime_sum_mean, 
            m2 = chime_stats_control_f$f_chime_sum_mean, 
            sd1 = chime_stats_control_f$b_chime_sum_sd, 
            sd2 = chime_stats_control_f$f_chime_sum_sd, 
            n = chime_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = chime_stats_intervention_f$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_intervention_f$chime_sum_change_pre_followup_sd,
             n = chime_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = chime_stats_control_f$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_control_f$chime_sum_change_pre_followup_sd,
             n = chime_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = chime_stats_intervention_f$chime_sum_change_pre_followup_mean,  
        m2 = chime_stats_control_f$chime_sum_change_pre_followup_mean,  
        sd1 = chime_stats_intervention_f$chime_sum_change_pre_followup_sd,  
        sd2 = chime_stats_control_f$chime_sum_change_pre_followup_sd,  
        n1 = chime_stats_intervention_f$n,  
        n2 = chime_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Depression symptoms descriptives

##Descriptives for intervention
mfq_stats_intervention_f <- completer_followup_quant_intervention %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mfq_stats_control_f <- completer_followup_quant_control %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Depression symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = mfq_stats_intervention_f$b_mfq_sum_mean, 
            m2 = mfq_stats_intervention_f$f_mfq_sum_mean, 
            sd1 = mfq_stats_intervention_f$b_mfq_sum_sd, 
            sd2 = mfq_stats_intervention_f$f_mfq_sum_sd, 
            n = mfq_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = mfq_stats_control_f$b_mfq_sum_mean, 
            m2 = mfq_stats_control_f$f_mfq_sum_mean, 
            sd1 = mfq_stats_control_f$b_mfq_sum_sd, 
            sd2 = mfq_stats_control_f$f_mfq_sum_sd, 
            n = mfq_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = mfq_stats_intervention_f$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_intervention_f$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = mfq_stats_control_f$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_control_f$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = mfq_stats_intervention_f$mfq_sum_change_pre_followup_mean,  
        m2 = mfq_stats_control_f$mfq_sum_change_pre_followup_mean,  
        sd1 = mfq_stats_intervention_f$mfq_sum_change_pre_followup_sd,  
        sd2 = mfq_stats_control_f$mfq_sum_change_pre_followup_sd,  
        n1 = mfq_stats_intervention_f$n,  
        n2 = mfq_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Eating disorder symptoms descriptives

##Descriptives for intervention
edeq_stats_intervention_f <- completer_followup_quant_intervention %>%
  select(b_edeq_sum, f_edeq_sum) %>%
  mutate(edeq_sum_change_pre_followup = f_edeq_sum - b_edeq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
edeq_stats_control_f <- completer_followup_quant_control %>%
  select(b_edeq_sum, f_edeq_sum) %>%
  mutate(edeq_sum_change_pre_followup = f_edeq_sum - b_edeq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Eating disorder symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = edeq_stats_intervention_f$b_edeq_sum_mean, 
            m2 = edeq_stats_intervention_f$f_edeq_sum_mean, 
            sd1 = edeq_stats_intervention_f$b_edeq_sum_sd, 
            sd2 = edeq_stats_intervention_f$f_edeq_sum_sd, 
            n = edeq_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = edeq_stats_control_f$b_edeq_sum_mean, 
            m2 = edeq_stats_control_f$f_edeq_sum_mean, 
            sd1 = edeq_stats_control_f$b_edeq_sum_sd, 
            sd2 = edeq_stats_control_f$f_edeq_sum_sd, 
            n = edeq_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = edeq_stats_intervention_f$edeq_sum_change_pre_followup_mean,
             sddiff = edeq_stats_intervention_f$edeq_sum_change_pre_followup_sd,
             n = edeq_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = edeq_stats_control_f$edeq_sum_change_pre_followup_mean,
             sddiff = edeq_stats_control_f$edeq_sum_change_pre_followup_sd,
             n = edeq_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = edeq_stats_intervention_f$edeq_sum_change_pre_followup_mean,  
        m2 = edeq_stats_control_f$edeq_sum_change_pre_followup_mean,  
        sd1 = edeq_stats_intervention_f$edeq_sum_change_pre_followup_sd,  
        sd2 = edeq_stats_control_f$edeq_sum_change_pre_followup_sd,  
        n1 = edeq_stats_intervention_f$n,  
        n2 = edeq_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")

#Muscle dysmorphia symptoms descriptives

##Descriptives for intervention
mddi_stats_intervention_f <- completer_followup_quant_intervention %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mddi_stats_control_f <- completer_followup_quant_control %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Muscle dysmorphia symptoms pre-followup

##within-person d(av) for intervention
d.dep.t.avg(m1 = mddi_stats_intervention_f$b_mddi_sum_mean, 
            m2 = mddi_stats_intervention_f$f_mddi_sum_mean, 
            sd1 = mddi_stats_intervention_f$b_mddi_sum_sd, 
            sd2 = mddi_stats_intervention_f$f_mddi_sum_sd, 
            n = mddi_stats_intervention_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
d.dep.t.avg(m1 = mddi_stats_control_f$b_mddi_sum_mean, 
            m2 = mddi_stats_control_f$f_mddi_sum_mean, 
            sd1 = mddi_stats_control_f$b_mddi_sum_sd, 
            sd2 = mddi_stats_control_f$f_mddi_sum_sd, 
            n = mddi_stats_control_f$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
d.dep.t.diff(mdiff = mddi_stats_intervention_f$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_intervention_f$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_intervention_f$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
d.dep.t.diff(mdiff = mddi_stats_control_f$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_control_f$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_control_f$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
d.ind.t(m1 = mddi_stats_intervention_f$mddi_sum_change_pre_followup_mean,  
        m2 = mddi_stats_control_f$mddi_sum_change_pre_followup_mean,  
        sd1 = mddi_stats_intervention_f$mddi_sum_change_pre_followup_sd,  
        sd2 = mddi_stats_control_f$mddi_sum_change_pre_followup_sd,  
        n1 = mddi_stats_intervention_f$n,  
        n2 = mddi_stats_control_f$n,  
        a = 0.05) %>%
  pluck("estimate")
```

```{r acceptability using intervention completers with PFS data}
#Check if there are differences in total PFS
t.test(randomized_intervention_pfs_complete$pi_pfs_sum,  randomized_control_pfs_complete$pi_pfs_sum)
#Significant differences in favor of PBN

#Overall score for intervention participants
randomized_intervention_pfs_complete %>%
    summarize(mean = mean(pi_pfs_sum), 
              sd = sd(pi_pfs_sum))

#Overall score for control participants
randomized_control_pfs_complete %>%
    summarize(mean = mean(pi_pfs_sum), 
              sd = sd(pi_pfs_sum))

#Individual items for intervention participants
randomized_intervention_pfs_complete %>%
  select(pi_pfs_1:pi_pfs_7) %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  summarize(mean = mean(value), 
            sd = sd(value))

#Individual items for control participants
randomized_control_pfs_complete %>%
  select(pi_pfs_1:pi_pfs_7) %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  summarize(mean = mean(value), 
            sd = sd(value))

#N and percent of intervention participants with sum score >3 (selects Agree and Strongly Agree only),  reflect overall perceived SSI acceptability
randomized_intervention_pfs_complete %>%
  mutate(pi_pfs_sum_scores = pi_pfs_sum / 7,  
         pi_pfs_sum_scores_acceptable = pi_pfs_sum_scores > 3) %>%
  summarise(pi_pfs_sum_scores_acceptable_percent = scales::percent(mean(pi_pfs_sum_scores_acceptable)))

#N and percent of control participants with sum score >3 (selects Agree and Strongly Agree only),  reflect overall perceived SSI acceptability
randomized_control_pfs_complete %>%
  mutate(pi_pfs_sum_scores = pi_pfs_sum / 7,  
         pi_pfs_sum_scores_acceptable = pi_pfs_sum_scores > 3) %>%
  summarise(pi_pfs_sum_scores_acceptable_percent = scales::percent(mean(pi_pfs_sum_scores_acceptable)))
```