---
title: "PBN RCT"
author: "Arielle Smith"
date: "2024-04-24"
output:
  html_document: default
  pdf_document: default
---

```{r working-directory}
# knitr::opts_knit$set(root.dir = "/Volumes/fsmresfiles/MSS/Schleider_Lab/jslab/Project Body Neutrality/RCT/Data/Full Sample (Baseline and Follow-Up)")
setwd("A:\\")
```

```{r load-packages-and-data}
#Load required packages
if(!require(tidyverse)){install.packages('tidyverse')}
library(tidyverse)
if(!require(lmtest)){install.packages('lmtest')}
library(lmtest)
if(!require(car)){install.packages('car')}
library(car)
if(!require(olsrr)){install.packages('olsrr')}
library(olsrr)
if(!require(sandwich)){install.packages('sandwich')}
library(sandwich)
if(!require(MOTE)){install.packages('MOTE')}
library(MOTE)
if(!require(openxlsx)){install.packages('openxlsx')}
library(openxlsx)
if(!require(missForest)){install.packages('missForest')}
library(missForest)
if(!require(visdat)){install.packages('visdat')}
library(visdat)
if(!require(qualtRics)){install.packages('qualtRics')}
library(qualtRics)
if(!require(readxl)){install.packages('readxl')}
library(readxl)

#Load data - #Using the .cols argument because otherwise some variables that should not be numeric are imported as such (e.g.,  demographics)
original_baseline_survey_data <- read_survey("original_baseline_survey_data.csv",  col_types = cols(.default = "c"))
new_baseline_survey_data <- read_survey("new_baseline_survey_data.csv",  col_types = cols(.default = "c"))
followup_data <- read_survey("followup_survey_data.csv",  col_types = cols(.default = "c")) 
participant_database <- read.csv(
  "participant_database.csv",
  stringsAsFactors = FALSE,
  colClasses = "character"
) %>%
  select(
    Participant_ID = ï..Participant_ID,
    Include.in.Analysis,
    Compensation.Date,
    Follow.Up.Completion
  )
```

```{r merge-data}
#Merge original_baseline_survey_data (closed because of frauds) and new_baseline_survey_data

#original_baseline_survey_data has 731 columns but new_baseline_survey_data has 729. Figure out the 2 differences
cols_in_original_only <- setdiff(names(original_baseline_survey_data),  names(new_baseline_survey_data))
print(cols_in_original_only)

#Remove the 2 extra Qualtrics columns from original_baseline_survey_data (won't mess things up because they are at the end and don't have anything important)
original_baseline_survey_data <- original_baseline_survey_data %>%
  select(-Q_AmbiguousTextPresent,  -Q_AmbiguousTextQuestions)

#Now we can merge
merged_baseline_data <- bind_rows(original_baseline_survey_data,  new_baseline_survey_data)

#Drop columns with no Participant IDs (they did not get far enough to get assigned an ID) 
merged_baseline_data <- merged_baseline_data %>%
  drop_na(Participant_ID)
  
#Now, we need to make sure that the participant database gets linked to the baseline data which it draws from
merged_participant_database_baseline_data <- participant_database %>% 
  left_join(merged_baseline_data, by = "Participant_ID", relationship = "one-to-one")

#We also need to merge with the follow-up data, accounting for duplicates (people that submitted follow-ups multiple times)
followup_data <- followup_data %>%
  group_by(Participant_ID) %>%
  arrange(desc(Progress),  RecordedDate) %>%
  slice(1)

n_distinct(followup_data$Participant_ID) == nrow(followup_data)

all_data <- merged_participant_database_baseline_data %>% 
  left_join(followup_data,  by = "Participant_ID", relationship = "one-to-one", suffix = c(".baseline", ".followup"))
```

```{r transform-data}
#The gender and race/ethnicity items include all responses from the multiple-select questions in one column. I need to separate them out in order to make them factors.

#First focus on transforming gender
transforming_gender <- all_data %>% 
  select(b_dem_gender, Participant_ID) %>%
  separate_rows(b_dem_gender, sep = ",") %>%
  pivot_wider(
    names_from = b_dem_gender,
    values_from = b_dem_gender,
    values_fill = list(b_dem_gender = "0")) %>%
  mutate(across(-Participant_ID, ~ as.factor(as.numeric(. != "0")))) %>% 
  rename_with(~ str_c("b_dem_gender_", .), -Participant_ID)

#Now focus on transforming race/ethnicity
transforming_race_ethnicity <- all_data %>% 
  select(b_dem_race_ethnicity, Participant_ID) %>%
  separate_rows(b_dem_race_ethnicity, sep = ",") %>%
  pivot_wider(
    names_from = b_dem_race_ethnicity,
    values_from = b_dem_race_ethnicity,
    values_fill = list(b_dem_race_ethnicity = "0")) %>%
  mutate(across(-Participant_ID, ~ as.factor(as.numeric(. != "0")))) %>% 
  rename_with(~ str_c("b_dem_race_ethnicity_", .), -Participant_ID)

all_data <- all_data %>%
  left_join(transforming_gender, by = "Participant_ID", relationship = "one-to-one") %>%
  left_join(transforming_race_ethnicity, by = "Participant_ID", relationship = "one-to-one")

#And I need to make all necessary variables numeric
all_data <- all_data %>%
  select(-contains("text"), -contains("free"), -b_dem_gender, -b_dem_race_ethnicity) %>% #remove free text and old demographic variables
  mutate(across(c(pi_pfs_1:pi_pfs_7,  starts_with("b_dem_age"), starts_with("b_dem_saab"), starts_with("b_dem_sexuality"), starts_with("b_dem_sex"), starts_with("b_current"), starts_with("b_past"), starts_with("b_unmet"), starts_with("b_hunger"), starts_with("b_bhs"),  starts_with("b_shs_agency"), starts_with("b_biss"),  starts_with("b_fas"),  starts_with("b_biaaq"),   starts_with("b_chime"),  starts_with("b_mfq"),  starts_with("b_edeq"),  starts_with("b_mddi"),  starts_with("pi_bhs"),  starts_with("pi_shs_agency"),  starts_with("pi_biss"),  starts_with("pi_fas"),  starts_with("pi_biaaq"),  starts_with("pi_chime"),  starts_with("f_bhs"),  starts_with("f_shs_agency"),  starts_with("f_biss"),  starts_with("f_fas"),  starts_with("f_biaaq"), starts_with("f_chime"),  starts_with("f_mfq"),  starts_with("f_edeq"),  starts_with("f_mddi"), starts_with("f_new_support")),  
                as.numeric))
```

```{r create-sum-scores}
#All relevant items are already reverse-scored in Qualtrics
all_data <- all_data %>%
  mutate(b_bhs_sum = b_bhs_1 + b_bhs_2 + b_bhs_3 + b_bhs_4, 
         pi_bhs_sum = pi_bhs_1 + pi_bhs_2 + pi_bhs_3 + pi_bhs_4, 
         f_bhs_sum = f_bhs_1 + f_bhs_2 + f_bhs_3 + f_bhs_4, 
         b_shs_agency_sum = b_shs_agency_1 + b_shs_agency_2 + b_shs_agency_3, 
         pi_shs_agency_sum = pi_shs_agency_1 + pi_shs_agency_2 + pi_shs_agency_3, 
         f_shs_agency_sum = f_shs_agency_1 + f_shs_agency_2 + f_shs_agency_3, 
         b_biss_sum = b_biss_1 + b_biss_2 + b_biss_3 + b_biss_4 +  b_biss_5 + b_biss_6, 
         pi_biss_sum = pi_biss_1 + pi_biss_2 + pi_biss_3 + pi_biss_4 +  pi_biss_5 + pi_biss_6, 
         f_biss_sum = f_biss_1 + f_biss_2 + f_biss_3 + f_biss_4 +  f_biss_5 + f_biss_6, 
         b_fas_sum = b_fas_1 + b_fas_2 + b_fas_3 + b_fas_4 + b_fas_5 + b_fas_6 + b_fas_7, 
         pi_fas_sum = pi_fas_1 + pi_fas_2 + pi_fas_3 + pi_fas_4 + pi_fas_5 + pi_fas_6 + pi_fas_7, 
         f_fas_sum = f_fas_1 + f_fas_2 + f_fas_3 + f_fas_4 + f_fas_5 + f_fas_6 + f_fas_7, 
         b_biaaq_sum = b_biaaq_1 + b_biaaq_2 + b_biaaq_3 + b_biaaq_4 + b_biaaq_5 + b_biaaq_6 + b_biaaq_7 + b_biaaq_8 + b_biaaq_9 + b_biaaq_10 + b_biaaq_11 + b_biaaq_12, 
         pi_biaaq_sum = pi_biaaq_1 + pi_biaaq_2 + pi_biaaq_3 + pi_biaaq_4 + pi_biaaq_5 + pi_biaaq_6 + pi_biaaq_7 + pi_biaaq_8 + pi_biaaq_9 + pi_biaaq_10 + pi_biaaq_11 + pi_biaaq_12,  
        f_biaaq_sum = f_biaaq_1 + f_biaaq_2 + f_biaaq_3 + f_biaaq_4 + f_biaaq_5 + f_biaaq_6 + f_biaaq_7 + f_biaaq_8 + f_biaaq_9 + f_biaaq_10 + f_biaaq_11 + f_biaaq_12, 
         b_chime_sum = b_chime_1 + b_chime_2 + b_chime_3, 
         pi_chime_sum = pi_chime_1 + pi_chime_2 + pi_chime_3, 
         f_chime_sum = f_chime_1 + f_chime_2 + f_chime_3, 
         pi_pfs_sum = pi_pfs_1 + pi_pfs_2 + pi_pfs_3 + pi_pfs_4 + pi_pfs_5 + pi_pfs_6 + pi_pfs_7, 
         b_mfq_sum = b_mfq_1 + b_mfq_2 + b_mfq_3 + b_mfq_4 + b_mfq_5 + b_mfq_6 + b_mfq_7 + b_mfq_8 + b_mfq_9 + b_mfq_10 + b_mfq_11 + b_mfq_12 + b_mfq_13,  
         f_mfq_sum = f_mfq_1 + f_mfq_2 + f_mfq_3 + f_mfq_4 + f_mfq_5 + f_mfq_6 + f_mfq_7 + f_mfq_8 + f_mfq_9 + f_mfq_10 + f_mfq_11 + f_mfq_12 + f_mfq_13, 
        b_edeq_dietary_restraint = (b_edeq_1 + b_edeq_2 + b_edeq_3) / 3,
        b_edeq_body_dissatisfaction = (b_edeq_4 + b_edeq_5 + b_edeq_6) / 3,
        b_edeq_overvaluation = (b_edeq_7 + b_edeq_8 + b_edeq_9 + b_edeq_10) / 4,
        b_edeq_global = (b_edeq_dietary_restraint + b_edeq_body_dissatisfaction + b_edeq_overvaluation) / 3,
        f_edeq_dietary_restraint = (f_edeq_1 + f_edeq_2 + f_edeq_3) / 3,
        f_edeq_body_dissatisfaction = (f_edeq_4 + f_edeq_5 + f_edeq_6) / 3,
        f_edeq_overvaluation = (f_edeq_7 + f_edeq_8 + f_edeq_9 + f_edeq_10) / 4,
        f_edeq_global = (f_edeq_dietary_restraint + f_edeq_body_dissatisfaction + f_edeq_overvaluation) / 3,
         b_mddi_sum = b_mddi_1 + b_mddi_2 + b_mddi_3 + b_mddi_4 + b_mddi_5 + b_mddi_6 + b_mddi_7 + b_mddi_8 + b_mddi_9 + b_mddi_10 + b_mddi_11 + b_mddi_12 + b_mddi_13, 
         f_mddi_sum = f_mddi_1 + f_mddi_2 + f_mddi_3 + f_mddi_4 + f_mddi_5 + f_mddi_6 + f_mddi_7 + f_mddi_8 + f_mddi_9 + f_mddi_10 + f_mddi_11 + f_mddi_12 + f_mddi_13)
         #b_edeq_sum = b_edeq_1 + b_edeq_2 + b_edeq_3 + b_edeq_4 + b_edeq_5 + b_edeq_6 + b_edeq_7 + b_edeq_8 + b_edeq_9 + b_edeq_10, #for testing only 
         #f_edeq_sum = f_edeq_1 + f_edeq_2 + f_edeq_3 + f_edeq_4 + f_edeq_5 + f_edeq_6 + f_edeq_7 + f_edeq_8 + f_edeq_9 + f_edeq_10) #for testing only 
```


```{r comparing-edeq-scoring}
#Originally, I used EDE-Q global sum scores instead of means. This could explain differences in EDE-Q results between rct-7 and this branch, if the correlation between the sums and means is not 1. 

#Sum like I› did earlier
test <- all_data %>% 
   mutate(b_edeq_sum = b_edeq_1 + b_edeq_2 + b_edeq_3 + b_edeq_4 + b_edeq_5 + b_edeq_6 + b_edeq_7 + b_edeq_8 + b_edeq_9 + b_edeq_10, 
         f_edeq_sum = f_edeq_1 + f_edeq_2 + f_edeq_3 + f_edeq_4 + f_edeq_5 + f_edeq_6 + f_edeq_7 + f_edeq_8 + f_edeq_9 + f_edeq_10)

cor(test$b_edeq_sum, test$b_edeq_global, use = "complete.obs")
cor(test$f_edeq_sum, test$f_edeq_global, use = "complete.obs")
#Even with NAs excluded, there is a slight difference between the simple sum score and the global EDE-Q mean, I think because of the different weighting for the EDE-Q overvaluation subscale
```

```{r prepare-randomized-sample}
#Extract all randomized participants who passed data integrity checks
all_data_real <- all_data %>% 
  filter(Include.in.Analysis == "Yes")

#Create variables to identify completion of different stages
all_data_real <- all_data_real %>%
  mutate(
    
  #Treatment group (Data integrity checks + randomization completed)
    treatment_group = factor(
      Condition == "Intervention",
      levels = c(FALSE, TRUE),
      labels = c("Control", "Intervention")
    ),
    
  #Intervention completed (regardless of randomization)
    completer_intervention_assignment = case_when(
      treatment_group == "Intervention" & `Intervention Completed` == "Intervention Completed" ~ TRUE,
      treatment_group == "Control" & `Control Completed` == "Control Completed" ~ TRUE,
      treatment_group == "Intervention" & is.na(`Intervention Completed`) ~ FALSE,
      treatment_group == "Control" & is.na(`Control Completed`) ~ FALSE
    ) %>%
      factor(
        levels = c(TRUE, FALSE),
        labels = c("Completed", "Not Completed")
      ),
  
  #Baseline completed
    completer_baseline = case_when(
      `Measures Completed.baseline` == "Measures Completed" ~ TRUE,
      is.na(`Measures Completed.baseline`) ~ FALSE
    ) %>%
      factor(
        levels = c(TRUE, FALSE),
        labels = c("Completed", "Not Completed")
    ),
  
  #Program feedback completed
    completer_pfs = case_when(
      !is.na(pi_pfs_sum) ~ TRUE,
      is.na(pi_pfs_sum) ~ FALSE
    ) %>% 
    factor(
        levels = c(TRUE, FALSE),
        labels = c("Completed", "Not Completed")
    ),
  
  #Follow-up completed 
    completer_followup = case_when(
      `Measures Completed.followup` == "Measures Completed" ~ TRUE,
      is.na(`Measures Completed.followup`) ~ FALSE
    ) %>%
      factor(
        levels = c(TRUE, FALSE),
        labels = c("Completed", "Not Completed")
        ))
```

```{r handling-missing-data}
#Identify participants with greater than 5% missing baseline primary outcomes data
#For each participant,  add a new column that calculates the percent missing of baseline primary outcome items
all_data_real <- all_data_real %>%
  mutate(percent_missing = rowMeans(
    is.na(select(.,  b_mfq_1,  b_mfq_2,  b_mfq_3,  b_mfq_4,  b_mfq_5,  b_mfq_6,  b_mfq_7,  b_mfq_8,  b_mfq_9,  b_mfq_10,  b_mfq_11,  b_mfq_12,  b_mfq_13,  b_edeq_1,  b_edeq_2,  b_edeq_3,  b_edeq_4,  b_edeq_5,  b_edeq_6,  b_edeq_7,  b_edeq_8,  b_edeq_9,  b_edeq_10)),
    na.rm = TRUE)) %>%
  mutate(percent_missing = percent_missing * 100)

#Make a new variable that identifies participants with more than 5% missing data (those with more than 5% missing are TRUE)
all_data_real <- all_data_real %>%
  mutate(more_than_5_percent_missing = percent_missing > 5)
#Remove participants where more_than_5_percent_missing is TRUE
missingness_handled <- all_data_real %>%
  filter(!more_than_5_percent_missing)
```

```{r make-seperate-dataframe-for-quant-data-imputation}
imputation_ready_with_IDs <- missingness_handled %>%
   select(Participant_ID, treatment_group,  completer_intervention_assignment, completer_baseline, completer_pfs, completer_followup, starts_with(c("b_dem",  "b_current",  "b_past",  "b_unmet",  "b_hunger",  "b_bhs",  "b_shs_agency",  "b_biss",  "b_fas",  "b_biaaq",  "b_chime",  "b_mfq",  "b_edeq",  "b_mddi",  "pi_pfs",  "pi_bhs",  "pi_shs_agency",  "pi_biss",  "pi_fas",  "pi_biaaq",  "pi_chime",  "f_new",  "f_bhs",  "f_shs_agency",  "f_biss",  "f_fas",  "f_biaaq",  "f_chime",  "f_mfq",  "f_edeq",  "f_mddi"))) %>%
  select(-contains("free"),  -contains("TEXT"),  -contains("_tim_"),  -contains("pfs_like"),  -contains("pfs_change"),  -contains("pfs_other"), -contains("percent_missing")) 

#Store Participant IDs to add back after imputation (don't want them to be recognized as numbers that mean something)
participant_ids <- imputation_ready_with_IDs$Participant_ID

#Drop participant IDs for imputation
imputation_ready_no_IDs <- imputation_ready_with_IDs %>% 
  select(-Participant_ID)
```

```{r imputation}
set.seed(12345) #use the same seed number each time to make the code reproducible (the seed number is just the starting point used in the generation of a sequence of random numbers in the random forest)

missForest_output <- missForest(imputation_ready_no_IDs)
imputed_data_error <- missForest_output$OOBerror
imputed_data <- as.data.frame(missForest_output$ximp)
imputed_data <- bind_cols(Participant_ID = participant_ids, imputed_data) #add back participant IDs
# imputed_data <- round(imputed_data) #TBD if we should round, it currently doesn't run with rounding
write.csv(imputed_data,file='imputed_data.csv')
```

```{r modifying-imputation-tests}
#In rct-7, even though I broke the data into seperate dataframes for each analysis before imputation (which is not correct), the imputation I had done for the ITT dataframe would be same as what is done here, because here, the ITT dataframe is the basis for all of the imputation. See if the original ITT imputation model I used (without some of the extra predictors that were not pre-registered, makes a difference with my EDE-Q outcome)

#imputation_ready_test <- missingness_handled %>%
#    select(treatment_group, completer_intervention_assignment, #called intervention_completed in rct-7
#           starts_with(c("b_dem",  "b_current",  "b_past",  "b_unmet",  "b_hunger",  "b_bhs",  "b_shs_agency",  "b_biss",  "b_fas",  "b_biaaq",  "b_chime",  "b_mfq",  "b_edeq",  "b_mddi",  "pi_pfs",  "pi_bhs",  "pi_shs_agency",  "pi_biss",  "pi_fas",  "pi_biaaq",  "pi_chime",  "f_new",  "f_bhs",  "f_shs_agency",  "f_biss",  "f_fas",  "f_biaaq",  "f_chime",  "f_mfq",  "f_edeq",  "f_mddi"))) %>%
 # select(-contains("free"),  -contains("TEXT"),  -contains("_tim_"),  -contains("pfs_like"),  -contains("pfs_change"),  -contains("pfs_other"), -contains("percent_missing")) 

#set.seed(12345) #use the same seed number each time to make the code reproducible (the seed number is just the starting point used in the generation of a sequence of random numbers in the random forest)

#imputed_data_test <- missForest(imputation_ready_test)
#imputed_data_test <- as.data.frame(imputed_data_test$ximp)

#NOTE Requires swapping sum for mean scores in the create-sum-scores chunk
#lm_edeq_itt_test_1 <- lm(f_edeq_global ~ b_edeq_global + treatment_group,  data = imputed_data_test)
#summary(lm_edeq_itt_test_1)
#coefci(lm_edeq_itt_test_1,  vcov = sandwich)
#p value is larger (0.099)

#See if I can reproduce the original EDE-Q p-value I got using sum scores (with the original imputation method) to see if the change to means is what is at the bottom of the issue. NOTE Requires swapping means for sum scores in the create-sum-scores chunk
#lm_edeq_itt_test_2 <- lm(f_edeq_sum ~ b_edeq_sum + treatment_group,  data = imputed_data_test)
#summary(lm_edeq_itt_test_2)
#coefci(lm_edeq_itt_test_2,  vcov = sandwich)
#p value is 0.0537 which isn't exactly what I had before but is close. These small changes really do make a difference.
```

```{r load-imputed-data}
imputed_data <- read.csv("imputed_data.csv")
```

```{r subset-data}
#Randomized (imputed)
df_randomized_imputed <- imputed_data #no filtering needed

#Completed intervention (regardless of randomization; imputed)
df_completer_intervention_imputed <- imputed_data %>% 
  filter(completer_intervention_assignment == "Completed")

#Completed baseline (imputed)
df_completer_baseline_imputed <- imputed_data %>% 
  filter(completer_baseline == "Completed")

#Completed PFS (nonimputed) - need non-imputed for qual analyses
df_completer_pfs_nonimputed <- imputation_ready_with_IDs %>%
  filter(completer_pfs == "Completed")

#Completed followup (nonimputed) - full completers
df_completer_followup_nonimputed <- imputation_ready_with_IDs %>%
  filter(completer_followup == "Completed")
```

```{r extract-data-for-qual-analysis}
#Dataframe for qualitative analysis (intervention completers with PFS data)
qual_data_intervention <- missingness_handled %>% 
  filter(completer_pfs == "Completed" & treatment_group == "Intervention") %>% 
  select(Participant_ID, pi_pfs_like, pi_pfs_change, pi_pfs_other)  
qual_data_control <- missingness_handled %>% 
  filter(completer_pfs == "Completed" & treatment_group == "Control") %>% 
  select(Participant_ID, pi_pfs_like, pi_pfs_change, pi_pfs_other)  

#Table export (only run again if file gets deleted)
#flextable::flextable(qual_data_intervention,  cwidth = c(0.5, 7, 0.5))
#write.xlsx(qual_data_intervention,  "pfs_qual_intervention.xlsx")
#flextable::flextable(qual_data_control,  cwidth = c(0.5, 7, 0.5))
#write.xlsx(qual_data_control,  "pfs_qual_control.xlsx")
```

```{r descriptives-of-outcomes}
descriptives <- df_randomized_imputed %>%
  group_by(treatment_group) %>%
  summarize(across(c(b_bhs_sum,  pi_bhs_sum,  f_bhs_sum, b_shs_agency_sum,  pi_shs_agency_sum,  f_shs_agency_sum, b_biss_sum,  pi_biss_sum, f_biss_sum,  b_fas_sum,  pi_fas_sum,  f_fas_sum, b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum, b_chime_sum,  pi_chime_sum,  f_chime_sum, b_mfq_sum, f_mfq_sum, b_edeq_global, f_edeq_global, b_mddi_sum, f_mddi_sum),  
                   list(mean = mean,  sd = sd)))
print(descriptives)
```

```{r primary-analysis-1-ITT}
#Hopelessness pre-post
library(broom)

lm_bhs_itt_1 <- lm(pi_bhs_sum ~ b_bhs_sum + treatment_group,  data = df_randomized_imputed) 
tidy(lm_bhs_itt_1, conf.int = T)

library(lmtest)
library(sandwich)
lm_bhs_itt_1_robust <- coeftest(
  x = lm_bhs_itt_1,
  vcov = vcovHC(lm_bhs_itt_1, type = "HC0")
)

tidy(lm_bhs_itt_1_robust, conf.int = T)

p_value_bhs_itt_1 <- lm_bhs_itt_1 %>%
  tidy() %>%
  filter(term == "treatment_groupIntervention") %>%
  pull(p.value)

#Hopelessness pre-followup
lm_bhs_itt_2 <- lm(f_bhs_sum ~ b_bhs_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_bhs_itt_2)
coefci(lm_bhs_itt_2, vcov = sandwich)
p_value_bhs_itt_2 <- summary(lm_bhs_itt_2)$coefficients[3,4]

#Agency pre-post
lm_shs_agency_itt_1 <- lm(pi_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_shs_agency_itt_1)
coefci(lm_shs_agency_itt_1,  vcov = sandwich)
p_value_shs_agency_itt_1 <- summary(lm_shs_agency_itt_1)$coefficients[3,4]

#Agency pre-followup
lm_shs_agency_itt_2 <- lm(f_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_shs_agency_itt_2)
coefci(lm_shs_agency_itt_2,  vcov = sandwich)
p_value_shs_agency_itt_2 <- summary(lm_shs_agency_itt_2)$coefficients[3,4]

#Body image state pre-post
lm_biss_itt_1 <- lm(pi_biss_sum ~ b_biss_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_biss_itt_1)
coefci(lm_biss_itt_1,  vcov = sandwich)
p_value_biss_itt_1 <- summary(lm_biss_itt_1)$coefficients[3,4]

#Body image state pre-followup
lm_biss_itt_2 <- lm(f_biss_sum ~ b_biss_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_biss_itt_2)
coefci(lm_biss_itt_2,  vcov = sandwich)
p_value_biss_itt_2 <- summary(lm_biss_itt_2)$coefficients[3,4]

#Functionality appreciation pre-post
lm_fas_itt_1 <- lm(pi_fas_sum ~ b_fas_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_fas_itt_1)
coefci(lm_fas_itt_1,  vcov = sandwich)
p_value_fas_itt_1 <- summary(lm_fas_itt_1)$coefficients[3,4]

#Functionality appreciation pre-followup
lm_fas_itt_2 <- lm(f_fas_sum ~ b_fas_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_fas_itt_2)
coefci(lm_fas_itt_2,  vcov = sandwich)
p_value_fas_itt_2 <- summary(lm_fas_itt_2)$coefficients[3,4]

#Body image flexibility pre-post - EXPLORATORY
lm_biaaq_itt_1 <- lm(pi_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_biaaq_itt_1)
coefci(lm_biaaq_itt_1,  vcov = sandwich)
p_value_biaaq_itt_1 <- summary(lm_biaaq_itt_1)$coefficients[3,4]

#Body image flexibility pre-followup - EXPLORATORY
lm_biaaq_itt_2 <- lm(f_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_biaaq_itt_2)
coefci(lm_biaaq_itt_2,  vcov = sandwich)
p_value_biaaq_itt_2 <- summary(lm_biaaq_itt_2)$coefficients[3,4]

#Body-related mindfulness pre-post - EXPLORATORY
lm_chime_itt_1 <- lm(pi_chime_sum ~ b_chime_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_chime_itt_1)
coefci(lm_chime_itt_1,  vcov = sandwich)
p_value_chime_itt_1 <- summary(lm_chime_itt_1)$coefficients[3,4]

#Body-related mindfulness pre-followup - EXPLORATORY
lm_chime_itt_2 <- lm(f_chime_sum ~ b_chime_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_chime_itt_2)
coefci(lm_chime_itt_2,  vcov = sandwich)
p_value_chime_itt_2 <- summary(lm_chime_itt_2)$coefficients[3,4]

#Depression symptoms pre-followup
lm_mfq_itt <- lm(f_mfq_sum ~ b_mfq_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_mfq_itt)
coefci(lm_mfq_itt,  vcov = sandwich)
p_value_mfq_itt <- summary(lm_mfq_itt)$coefficients[3,4]

#Eating disorder symptoms pre-followup
lm_edeq_itt <- lm(f_edeq_global ~ b_edeq_global + treatment_group,  data = df_randomized_imputed)
summary(lm_edeq_itt)
coefci(lm_edeq_itt,  vcov = sandwich)
p_value_edeq_itt <- summary(lm_edeq_itt)$coefficients[3,4]

#Muscle dysmorphia symptoms pre-followup - EXPLORATORY
lm_mddi_itt <- lm(f_mddi_sum ~ b_mddi_sum + treatment_group,  data = df_randomized_imputed)
summary(lm_mddi_itt)
coefci(lm_mddi_itt,  vcov = sandwich)
p_value_mddi_itt <- summary(lm_mddi_itt)$coefficients[3,4]

```

```{r primary-analysis-2-TOT}
#Hopelessness pre-post
lm_bhs_tot_1 <- lm(pi_bhs_sum ~ b_bhs_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_bhs_tot_1)
coefci(lm_bhs_tot_1)
p_value_bhs_tot_1 <- summary(lm_bhs_tot_1)$coefficients[3,4]

#Hopelessness pre-followup
lm_bhs_tot_2 <- lm(f_bhs_sum ~ b_bhs_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_bhs_tot_2)
coefci(lm_bhs_tot_2)
p_value_bhs_tot_2 <- summary(lm_bhs_tot_2)$coefficients[3,4]

#Agency pre-post
lm_shs_agency_tot_1 <- lm(pi_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_shs_agency_tot_1)
coefci(lm_shs_agency_tot_1,  vcov = sandwich)
p_value_shs_agency_tot_1 <- summary(lm_shs_agency_tot_1)$coefficients[3,4]

#Agency pre-followup
lm_shs_agency_tot_2 <- lm(f_shs_agency_sum ~ b_shs_agency_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_shs_agency_tot_2)
coefci(lm_shs_agency_tot_2,  vcov = sandwich)
p_value_shs_agency_tot_2 <- summary(lm_shs_agency_tot_2)$coefficients[3,4]

#Body image state pre-post
lm_biss_tot_1 <- lm(pi_biss_sum ~ b_biss_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_biss_tot_1)
coefci(lm_biss_tot_1,  vcov = sandwich)
p_value_biss_tot_1 <- summary(lm_biss_tot_1)$coefficients[3,4]

#Body image state pre-followup
lm_biss_tot_2 <- lm(f_biss_sum ~ b_biss_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_biss_tot_2)
coefci(lm_biss_tot_2,  vcov = sandwich)
p_value_biss_tot_2 <- summary(lm_biss_tot_2)$coefficients[3,4]

#Functionality appreciation pre-post
lm_fas_tot_1 <- lm(pi_fas_sum ~ b_fas_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_fas_tot_1)
coefci(lm_fas_tot_1,  vcov = sandwich)
p_value_fas_tot_1 <- summary(lm_fas_tot_1)$coefficients[3,4]

#Functionality appreciation pre-followup
lm_fas_tot_2 <- lm(f_fas_sum ~ b_fas_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_fas_tot_2)
coefci(lm_fas_tot_2,  vcov = sandwich)
p_value_fas_tot_2 <- summary(lm_fas_tot_2)$coefficients[3,4]

#Body image flexibility pre-post - EXPLORATORY
lm_biaaq_tot_1 <- lm(pi_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_biaaq_tot_1)
coefci(lm_biaaq_tot_1,  vcov = sandwich)
p_value_biaaq_tot_1 <- summary(lm_biaaq_tot_1)$coefficients[3,4]

#Body image flexibility pre-followup - EXPLORATORY
lm_biaaq_tot_2 <- lm(f_biaaq_sum ~ b_biaaq_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_biaaq_tot_2)
coefci(lm_biaaq_tot_2,  vcov = sandwich)
p_value_biaaq_tot_2 <- summary(lm_biaaq_tot_2)$coefficients[3,4]

#Body-related mindfulness pre-post - EXPLORATORY
lm_chime_tot_1 <- lm(pi_chime_sum ~ b_chime_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_chime_tot_1)
coefci(lm_chime_tot_1,  vcov = sandwich)
p_value_chime_tot_1 <- summary(lm_chime_tot_1)$coefficients[3,4]

#Body-related mindfulness pre-followup - EXPLORATORY
lm_chime_tot_2 <- lm(f_chime_sum ~ b_chime_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_chime_tot_2)
coefci(lm_chime_tot_2,  vcov = sandwich)
p_value_chime_tot_2 <- summary(lm_chime_tot_2)$coefficients[3,4]

#Depression symptoms pre-followup
lm_mfq_tot <- lm(f_mfq_sum ~ b_mfq_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_mfq_tot)
coefci(lm_mfq_tot,  vcov = sandwich)
p_value_mfq_tot <- summary(lm_mfq_tot)$coefficients[3,4]

#Eating disorder symptoms pre-followup
lm_edeq_tot <- lm(f_edeq_global ~ b_edeq_global + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_edeq_tot)
coefci(lm_edeq_tot,  vcov = sandwich)
p_value_edeq_tot <- summary(lm_edeq_tot)$coefficients[3,4]

#Muscle dysmorphia symptoms pre-followup - EXPLORATORY
lm_mddi_tot <- lm(f_mddi_sum ~ b_mddi_sum + treatment_group,  data = df_completer_intervention_imputed)
summary(lm_mddi_tot)
coefci(lm_mddi_tot,  vcov = sandwich)
p_value_mddi_tot <- summary(lm_mddi_tot)$coefficients[3,4]
```

```{r regression-assumptions-ITT}
#Check ITT pre-post

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_itt_1))
sqrt(vif(lm_shs_agency_itt_1))
sqrt(vif(lm_biss_itt_1))
sqrt(vif(lm_fas_itt_1))
sqrt(vif(lm_biaaq_itt_1))
sqrt(vif(lm_chime_itt_1))

##Linearity of data
plot(lm_bhs_itt_1, 1)
plot(lm_shs_agency_itt_1,  1)
plot(lm_biss_itt_1,  1)
plot(lm_fas_itt_1,  1)
plot(lm_biaaq_itt_1,  1)
plot(lm_chime_itt_1,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_itt_1)
durbinWatsonTest(lm_shs_agency_itt_1)
durbinWatsonTest(lm_biss_itt_1)
durbinWatsonTest(lm_fas_itt_1) 
durbinWatsonTest(lm_biaaq_itt_1)
durbinWatsonTest(lm_chime_itt_1) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_itt_1,  3) 
plot(lm_shs_agency_itt_1,  3)
plot(lm_biss_itt_1,  3) 
plot(lm_fas_itt_1,  3)
plot(lm_biaaq_itt_1,  3)
plot(lm_chime_itt_1,  3)
ncvTest(lm_bhs_itt_1) 
ncvTest(lm_shs_agency_itt_1)
ncvTest(lm_biss_itt_1)
ncvTest(lm_fas_itt_1) 
ncvTest(lm_biaaq_itt_1)
ncvTest(lm_chime_itt_1)
bptest(lm_bhs_itt_1)
bptest(lm_shs_agency_itt_1)
bptest(lm_biss_itt_1)
bptest(lm_fas_itt_1) 
bptest(lm_biaaq_itt_1)
bptest(lm_chime_itt_1)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_itt_1)
ols_plot_resid_qq(lm_shs_agency_itt_1) 
ols_plot_resid_qq(lm_biss_itt_1)
ols_plot_resid_qq(lm_fas_itt_1)
ols_plot_resid_qq(lm_biaaq_itt_1)
ols_plot_resid_qq(lm_chime_itt_1)

#Check ITT pre-followup

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_itt_2))
sqrt(vif(lm_shs_agency_itt_2))
sqrt(vif(lm_biss_itt_2))
sqrt(vif(lm_fas_itt_2))
sqrt(vif(lm_biaaq_itt_2))
sqrt(vif(lm_chime_itt_2))

##Linearity of data
plot(lm_bhs_itt_2,  1)
plot(lm_shs_agency_itt_2,  1)
plot(lm_biss_itt_2,  1)
plot(lm_fas_itt_2,  1)
plot(lm_biaaq_itt_2,  1)
plot(lm_chime_itt_2,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_itt_2)
durbinWatsonTest(lm_shs_agency_itt_2)
durbinWatsonTest(lm_biss_itt_2)
durbinWatsonTest(lm_fas_itt_2) 
durbinWatsonTest(lm_biaaq_itt_2)
durbinWatsonTest(lm_chime_itt_2) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_itt_2,  3) 
plot(lm_shs_agency_itt_2,  3)
plot(lm_biss_itt_2,  3) 
plot(lm_fas_itt_2,  3)
plot(lm_biaaq_itt_2,  3)
plot(lm_chime_itt_2,  3)
ncvTest(lm_bhs_itt_2) 
ncvTest(lm_shs_agency_itt_2)
ncvTest(lm_biss_itt_2)
ncvTest(lm_fas_itt_2) 
ncvTest(lm_biaaq_itt_2)
ncvTest(lm_chime_itt_2)
bptest(lm_bhs_itt_2)
bptest(lm_shs_agency_itt_2)
bptest(lm_biss_itt_2)
bptest(lm_fas_itt_2) 
bptest(lm_biaaq_itt_2)
bptest(lm_chime_itt_2)

##Normality of residual errors
hist(resid(lm_bhs_itt_2))

ols_plot_resid_qq(lm_bhs_itt_2)
ols_plot_resid_qq(lm_shs_agency_itt_2) 
ols_plot_resid_qq(lm_biss_itt_2)
ols_plot_resid_qq(lm_fas_itt_2)
ols_plot_resid_qq(lm_biaaq_itt_2)
ols_plot_resid_qq(lm_chime_itt_2)
```

```{r regression-assumptions-TOT}
#Check TOT pre-post

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_tot_1))
sqrt(vif(lm_shs_agency_tot_1))
sqrt(vif(lm_biss_tot_1))
sqrt(vif(lm_fas_tot_1))
sqrt(vif(lm_biaaq_tot_1))
sqrt(vif(lm_chime_tot_1))

##Linearity of data
plot(lm_bhs_tot_1,  1)
plot(lm_shs_agency_tot_1,  1)
plot(lm_biss_tot_1,  1)
plot(lm_fas_tot_1,  1)
plot(lm_biaaq_tot_1,  1)
plot(lm_chime_tot_1,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_tot_1)
durbinWatsonTest(lm_shs_agency_tot_1)
durbinWatsonTest(lm_biss_tot_1)
durbinWatsonTest(lm_fas_tot_1) 
durbinWatsonTest(lm_biaaq_tot_1)
durbinWatsonTest(lm_chime_tot_1) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_tot_1,  3) 
plot(lm_shs_agency_tot_1,  3)
plot(lm_biss_tot_1,  3) 
plot(lm_fas_tot_1,  3)
plot(lm_biaaq_tot_1,  3)
plot(lm_chime_tot_1,  3)
ncvTest(lm_bhs_tot_1) 
ncvTest(lm_shs_agency_tot_1)
ncvTest(lm_biss_tot_1)
ncvTest(lm_fas_tot_1) 
ncvTest(lm_biaaq_tot_1)
ncvTest(lm_chime_tot_1)
bptest(lm_bhs_tot_1)
bptest(lm_shs_agency_tot_1)
bptest(lm_biss_tot_1)
bptest(lm_fas_tot_1) 
bptest(lm_biaaq_tot_1)
bptest(lm_chime_tot_1)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_tot_1)
ols_plot_resid_qq(lm_shs_agency_tot_1) 
ols_plot_resid_qq(lm_biss_tot_1)
ols_plot_resid_qq(lm_fas_tot_1)
ols_plot_resid_qq(lm_biaaq_tot_1)
ols_plot_resid_qq(lm_chime_tot_1)

#Check TOT pre-followup

##Multicollinearity - sqrt should be <2
sqrt(vif(lm_bhs_tot_2))
sqrt(vif(lm_shs_agency_tot_2))
sqrt(vif(lm_biss_tot_2))
sqrt(vif(lm_fas_tot_2))
sqrt(vif(lm_biaaq_tot_2))
sqrt(vif(lm_chime_tot_2))

##Linearity of data
plot(lm_bhs_tot_2,  1)
plot(lm_shs_agency_tot_2,  1)
plot(lm_biss_tot_2,  1)
plot(lm_fas_tot_2,  1)
plot(lm_biaaq_tot_2,  1)
plot(lm_chime_tot_2,  1)

##Independence of predictors - p should be > 0.05
durbinWatsonTest(lm_bhs_tot_2)
durbinWatsonTest(lm_shs_agency_tot_2)
durbinWatsonTest(lm_biss_tot_2)
durbinWatsonTest(lm_fas_tot_2) 
durbinWatsonTest(lm_biaaq_tot_2)
durbinWatsonTest(lm_chime_tot_2) 

##Homoscedasticity - p should be > 0.05 for ncv and bp
plot(lm_bhs_tot_2,  3) 
plot(lm_shs_agency_tot_2,  3)
plot(lm_biss_tot_2,  3) 
plot(lm_fas_tot_2,  3)
plot(lm_biaaq_tot_2,  3)
plot(lm_chime_tot_2,  3)
ncvTest(lm_bhs_tot_2) 
ncvTest(lm_shs_agency_tot_2)
ncvTest(lm_biss_tot_2)
ncvTest(lm_fas_tot_2) 
ncvTest(lm_biaaq_tot_2)
ncvTest(lm_chime_tot_2)
bptest(lm_bhs_tot_2)
bptest(lm_shs_agency_tot_2)
bptest(lm_biss_tot_2)
bptest(lm_fas_tot_2) 
bptest(lm_biaaq_tot_2)
bptest(lm_chime_tot_2)

##Normality of residual errors
ols_plot_resid_qq(lm_bhs_tot_2)
ols_plot_resid_qq(lm_shs_agency_tot_2) 
ols_plot_resid_qq(lm_biss_tot_2)
ols_plot_resid_qq(lm_fas_tot_2)
ols_plot_resid_qq(lm_biaaq_tot_2)
ols_plot_resid_qq(lm_chime_tot_2)
```

```{r effect-sizes-ITT}
#Make new dataframes to separate Intervention and Control folks (with imputed data)
df_randomized_imputed_intervention <- df_randomized_imputed %>% 
  filter(treatment_group == "Intervention")

df_randomized_imputed_control <- df_randomized_imputed %>% 
  filter(treatment_group == "Control")

#Hopelessness descriptives

##Descriptives for intervention
bhs_stats_intervention_itt <- df_randomized_imputed_intervention %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
bhs_stats_control_itt <- df_randomized_imputed_control %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Hopelessness pre-post

##within-in person d(av) for intervention
dav_intervention_bhs_itt_1 <- d.dep.t.avg(m1 = bhs_stats_intervention_itt$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_itt$pi_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_itt$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_itt$pi_bhs_sum_sd, 
            n = bhs_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_bhs_itt_1 <- d.dep.t.avg(m1 = bhs_stats_control_itt$b_bhs_sum_mean, 
            m2 = bhs_stats_control_itt$pi_bhs_sum_mean, 
            sd1 = bhs_stats_control_itt$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_itt$pi_bhs_sum_sd, 
            n = bhs_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_bhs_itt_1 <- d.dep.t.diff(mdiff = bhs_stats_intervention_itt$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_intervention_itt$bhs_sum_change_pre_post_sd,
             n = bhs_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_bhs_itt_1 <- d.dep.t.diff(mdiff = bhs_stats_control_itt$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_control_itt$bhs_sum_change_pre_post_sd,
             n = bhs_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_bhs_itt_1 <- d.ind.t(m1 = bhs_stats_intervention_itt$bhs_sum_change_pre_post_mean,  
        m2 = bhs_stats_control_itt$bhs_sum_change_pre_post_mean,  
        sd1 = bhs_stats_intervention_itt$bhs_sum_change_pre_post_sd,  
        sd2 = bhs_stats_control_itt$bhs_sum_change_pre_post_sd,  
        n1 = bhs_stats_intervention_itt$n,  
        n2 = bhs_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Hopelessness pre-followup

##within-person d(av) for intervention
dav_intervention_bhs_itt_2 <- d.dep.t.avg(m1 = bhs_stats_intervention_itt$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_itt$f_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_itt$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_itt$f_bhs_sum_sd, 
            n = bhs_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_bhs_itt_2 <- d.dep.t.avg(m1 = bhs_stats_control_itt$b_bhs_sum_mean, 
            m2 = bhs_stats_control_itt$f_bhs_sum_mean, 
            sd1 = bhs_stats_control_itt$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_itt$f_bhs_sum_sd, 
            n = bhs_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_bhs_itt_2 <- d.dep.t.diff(mdiff = bhs_stats_intervention_itt$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_intervention_itt$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_bhs_itt_2 <- d.dep.t.diff(mdiff = bhs_stats_control_itt$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_control_itt$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_bhs_itt_2 <- d.ind.t(m1 = bhs_stats_intervention_itt$bhs_sum_change_pre_followup_mean,  
        m2 = bhs_stats_control_itt$bhs_sum_change_pre_followup_mean,  
        sd1 = bhs_stats_intervention_itt$bhs_sum_change_pre_followup_sd,  
        sd2 = bhs_stats_control_itt$bhs_sum_change_pre_followup_sd,  
        n1 = bhs_stats_intervention_itt$n,  
        n2 = bhs_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency descriptives

##Descriptives for intervention
shs_agency_stats_intervention_itt <- df_randomized_imputed_intervention %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
shs_agency_stats_control_itt <- df_randomized_imputed_control  %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Agency pre-post

##within-in person d(av) for intervention
dav_intervention_shs_agency_itt_1 <- d.dep.t.avg(m1 = shs_agency_stats_intervention_itt$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_itt$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_itt$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_itt$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_shs_agency_itt_1 <- d.dep.t.avg(m1 = shs_agency_stats_control_itt$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_itt$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_itt$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_itt$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_shs_agency_itt_1 <- d.dep.t.diff(mdiff = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_shs_agency_itt_1 <- d.dep.t.diff(mdiff = shs_agency_stats_control_itt$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_control_itt$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_shs_agency_itt_1 <- d.ind.t(m1 = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_post_mean,  
        m2 = shs_agency_stats_control_itt$shs_agency_sum_change_pre_post_mean,  
        sd1 = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_post_sd,  
        sd2 = shs_agency_stats_control_itt$shs_agency_sum_change_pre_post_sd,  
        n1 = shs_agency_stats_intervention_itt$n,  
        n2 = shs_agency_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency pre-followup

##within-person d(av) for intervention
dav_intervention_shs_agency_itt_2 <- d.dep.t.avg(m1 = shs_agency_stats_intervention_itt$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_itt$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_itt$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_itt$f_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_shs_agency_itt_2 <- d.dep.t.avg(m1 = shs_agency_stats_control_itt$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_itt$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_itt$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_itt$f_shs_agency_sum_sd, 
            n = shs_agency_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_shs_agency_itt_2 <- d.dep.t.diff(mdiff = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_shs_agency_itt_2 <- d.dep.t.diff(mdiff = shs_agency_stats_control_itt$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_control_itt$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_shs_agency_itt_2 <- d.ind.t(m1 = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_followup_mean,  
        m2 = shs_agency_stats_control_itt$shs_agency_sum_change_pre_followup_mean,  
        sd1 = shs_agency_stats_intervention_itt$shs_agency_sum_change_pre_followup_sd,  
        sd2 = shs_agency_stats_control_itt$shs_agency_sum_change_pre_followup_sd,  
        n1 = shs_agency_stats_intervention_itt$n,  
        n2 = shs_agency_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state descriptives

##Descriptives for intervention
biss_stats_intervention_itt <- df_randomized_imputed_intervention %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biss_stats_control_itt <- df_randomized_imputed_control  %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image state pre-post

##within-in person d(av) for intervention
dav_intervention_biss_itt_1 <- d.dep.t.avg(m1 = biss_stats_intervention_itt$b_biss_sum_mean, 
            m2 = biss_stats_intervention_itt$pi_biss_sum_mean, 
            sd1 = biss_stats_intervention_itt$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_itt$pi_biss_sum_sd, 
            n = biss_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_biss_itt_1 <- d.dep.t.avg(m1 = biss_stats_control_itt$b_biss_sum_mean, 
            m2 = biss_stats_control_itt$pi_biss_sum_mean, 
            sd1 = biss_stats_control_itt$b_biss_sum_sd, 
            sd2 = biss_stats_control_itt$pi_biss_sum_sd, 
            n = biss_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_biss_itt_1 <- d.dep.t.diff(mdiff = biss_stats_intervention_itt$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_intervention_itt$biss_sum_change_pre_post_sd,
             n = biss_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_biss_itt_1 <- d.dep.t.diff(mdiff = biss_stats_control_itt$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_control_itt$biss_sum_change_pre_post_sd,
             n = biss_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_biss_itt_1 <- d.ind.t(m1 = biss_stats_intervention_itt$biss_sum_change_pre_post_mean,  
        m2 = biss_stats_control_itt$biss_sum_change_pre_post_mean,  
        sd1 = biss_stats_intervention_itt$biss_sum_change_pre_post_sd,  
        sd2 = biss_stats_control_itt$biss_sum_change_pre_post_sd,  
        n1 = biss_stats_intervention_itt$n,  
        n2 = biss_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state pre-followup

##within-person d(av) for intervention
dav_intervention_biss_itt_2 <- d.dep.t.avg(m1 = biss_stats_intervention_itt$b_biss_sum_mean, 
            m2 = biss_stats_intervention_itt$f_biss_sum_mean, 
            sd1 = biss_stats_intervention_itt$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_itt$f_biss_sum_sd, 
            n = biss_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_biss_itt_2 <- d.dep.t.avg(m1 = biss_stats_control_itt$b_biss_sum_mean, 
            m2 = biss_stats_control_itt$f_biss_sum_mean, 
            sd1 = biss_stats_control_itt$b_biss_sum_sd, 
            sd2 = biss_stats_control_itt$f_biss_sum_sd, 
            n = biss_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_biss_itt_2 <- d.dep.t.diff(mdiff = biss_stats_intervention_itt$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_intervention_itt$biss_sum_change_pre_followup_sd,
             n = biss_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_biss_itt_2 <- d.dep.t.diff(mdiff = biss_stats_control_itt$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_control_itt$biss_sum_change_pre_followup_sd,
             n = biss_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_biss_itt_2 <- d.ind.t(m1 = biss_stats_intervention_itt$biss_sum_change_pre_followup_mean,  
        m2 = biss_stats_control_itt$biss_sum_change_pre_followup_mean,  
        sd1 = biss_stats_intervention_itt$biss_sum_change_pre_followup_sd,  
        sd2 = biss_stats_control_itt$biss_sum_change_pre_followup_sd,  
        n1 = biss_stats_intervention_itt$n,  
        n2 = biss_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")   
  
#Functionality appreciation descriptives

##Descriptives for intervention
fas_stats_intervention_itt <- df_randomized_imputed_intervention %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
fas_stats_control_itt <- df_randomized_imputed_control  %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Functionality appreciation pre-post

##within-in person d(av) for intervention
dav_intervention_fas_itt_1 <- d.dep.t.avg(m1 = fas_stats_intervention_itt$b_fas_sum_mean, 
            m2 = fas_stats_intervention_itt$pi_fas_sum_mean, 
            sd1 = fas_stats_intervention_itt$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_itt$pi_fas_sum_sd, 
            n = fas_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_fas_itt_1 <- d.dep.t.avg(m1 = fas_stats_control_itt$b_fas_sum_mean, 
            m2 = fas_stats_control_itt$pi_fas_sum_mean, 
            sd1 = fas_stats_control_itt$b_fas_sum_sd, 
            sd2 = fas_stats_control_itt$pi_fas_sum_sd, 
            n = fas_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_fas_itt_1 <- d.dep.t.diff(mdiff = fas_stats_intervention_itt$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_intervention_itt$fas_sum_change_pre_post_sd,
             n = fas_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_fas_itt_1 <- d.dep.t.diff(mdiff = fas_stats_control_itt$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_control_itt$fas_sum_change_pre_post_sd,
             n = fas_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_fas_itt_1 <- d.ind.t(m1 = fas_stats_intervention_itt$fas_sum_change_pre_post_mean,  
        m2 = fas_stats_control_itt$fas_sum_change_pre_post_mean,  
        sd1 = fas_stats_intervention_itt$fas_sum_change_pre_post_sd,  
        sd2 = fas_stats_control_itt$fas_sum_change_pre_post_sd,  
        n1 = fas_stats_intervention_itt$n,  
        n2 = fas_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Functionality appreciation pre-followup

##within-person d(av) for intervention
dav_intervention_fas_itt_2 <- d.dep.t.avg(m1 = fas_stats_intervention_itt$b_fas_sum_mean, 
            m2 = fas_stats_intervention_itt$f_fas_sum_mean, 
            sd1 = fas_stats_intervention_itt$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_itt$f_fas_sum_sd, 
            n = fas_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_fas_itt_2 <- d.dep.t.avg(m1 = fas_stats_control_itt$b_fas_sum_mean, 
            m2 = fas_stats_control_itt$f_fas_sum_mean, 
            sd1 = fas_stats_control_itt$b_fas_sum_sd, 
            sd2 = fas_stats_control_itt$f_fas_sum_sd, 
            n = fas_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_fas_itt_2 <- d.dep.t.diff(mdiff = fas_stats_intervention_itt$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_intervention_itt$fas_sum_change_pre_followup_sd,
             n = fas_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_fas_itt_2 <- d.dep.t.diff(mdiff = fas_stats_control_itt$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_control_itt$fas_sum_change_pre_followup_sd,
             n = fas_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_fas_itt_2 <- d.ind.t(m1 = fas_stats_intervention_itt$fas_sum_change_pre_followup_mean,  
        m2 = fas_stats_control_itt$fas_sum_change_pre_followup_mean,  
        sd1 = fas_stats_intervention_itt$fas_sum_change_pre_followup_sd,  
        sd2 = fas_stats_control_itt$fas_sum_change_pre_followup_sd,  
        n1 = fas_stats_intervention_itt$n,  
        n2 = fas_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Body image flexibility descriptives

##Descriptives for intervention
biaaq_stats_intervention_itt <- df_randomized_imputed_intervention %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biaaq_stats_control_itt <- df_randomized_imputed_control %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image flexibility pre-post

##within-in person d(av) for intervention
dav_intervention_biaaq_itt_1 <- d.dep.t.avg(m1 = biaaq_stats_intervention_itt$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_itt$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_itt$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_itt$pi_biaaq_sum_sd, 
            n = biaaq_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_biaaq_itt_1 <- d.dep.t.avg(m1 = biaaq_stats_control_itt$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_itt$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_itt$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_itt$pi_biaaq_sum_sd, 
            n = biaaq_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_biaaq_itt_1 <- d.dep.t.diff(mdiff = biaaq_stats_intervention_itt$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_intervention_itt$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_biaaq_itt_1 <- d.dep.t.diff(mdiff = biaaq_stats_control_itt$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_control_itt$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_biaaq_itt_1 <- d.ind.t(m1 = biaaq_stats_intervention_itt$biaaq_sum_change_pre_post_mean,  
        m2 = biaaq_stats_control_itt$biaaq_sum_change_pre_post_mean,  
        sd1 = biaaq_stats_intervention_itt$biaaq_sum_change_pre_post_sd,  
        sd2 = biaaq_stats_control_itt$biaaq_sum_change_pre_post_sd,  
        n1 = biaaq_stats_intervention_itt$n,  
        n2 = biaaq_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image flexibility pre-followup

##within-person d(av) for intervention
dav_intervention_biaaq_itt_2 <- d.dep.t.avg(m1 = biaaq_stats_intervention_itt$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_itt$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_itt$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_itt$f_biaaq_sum_sd, 
            n = biaaq_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_biaaq_itt_2 <- d.dep.t.avg(m1 = biaaq_stats_control_itt$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_itt$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_itt$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_itt$f_biaaq_sum_sd, 
            n = biaaq_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_biaaq_itt_2 <- d.dep.t.diff(mdiff = biaaq_stats_intervention_itt$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_intervention_itt$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_biaaq_itt_2 <- d.dep.t.diff(mdiff = biaaq_stats_control_itt$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_control_itt$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_biaaq_itt_2 <- d.ind.t(m1 = biaaq_stats_intervention_itt$biaaq_sum_change_pre_followup_mean,  
        m2 = biaaq_stats_control_itt$biaaq_sum_change_pre_followup_mean,  
        sd1 = biaaq_stats_intervention_itt$biaaq_sum_change_pre_followup_sd,  
        sd2 = biaaq_stats_control_itt$biaaq_sum_change_pre_followup_sd,  
        n1 = biaaq_stats_intervention_itt$n,  
        n2 = biaaq_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness descriptives

##Descriptives for intervention
chime_stats_intervention_itt <- df_randomized_imputed_intervention %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
chime_stats_control_itt <- df_randomized_imputed_control %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body-related mindfulness pre-post

##within-in person d(av) for intervention
dav_intervention_chime_itt_1 <- d.dep.t.avg(m1 = chime_stats_intervention_itt$b_chime_sum_mean, 
            m2 = chime_stats_intervention_itt$pi_chime_sum_mean, 
            sd1 = chime_stats_intervention_itt$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_itt$pi_chime_sum_sd, 
            n = chime_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_chime_itt_1 <- d.dep.t.avg(m1 = chime_stats_control_itt$b_chime_sum_mean, 
            m2 = chime_stats_control_itt$pi_chime_sum_mean, 
            sd1 = chime_stats_control_itt$b_chime_sum_sd, 
            sd2 = chime_stats_control_itt$pi_chime_sum_sd, 
            n = chime_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_chime_itt_1 <- d.dep.t.diff(mdiff = chime_stats_intervention_itt$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_intervention_itt$chime_sum_change_pre_post_sd,
             n = chime_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_chime_itt_1 <- d.dep.t.diff(mdiff = chime_stats_control_itt$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_control_itt$chime_sum_change_pre_post_sd,
             n = chime_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_chime_itt_1 <- d.ind.t(m1 = chime_stats_intervention_itt$chime_sum_change_pre_post_mean,  
        m2 = chime_stats_control_itt$chime_sum_change_pre_post_mean,  
        sd1 = chime_stats_intervention_itt$chime_sum_change_pre_post_sd,  
        sd2 = chime_stats_control_itt$chime_sum_change_pre_post_sd,  
        n1 = chime_stats_intervention_itt$n,  
        n2 = chime_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness pre-followup

##within-person d(av) for intervention
dav_intervention_chime_itt_2 <- d.dep.t.avg(m1 = chime_stats_intervention_itt$b_chime_sum_mean, 
            m2 = chime_stats_intervention_itt$f_chime_sum_mean, 
            sd1 = chime_stats_intervention_itt$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_itt$f_chime_sum_sd, 
            n = chime_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_chime_itt_2 <- d.dep.t.avg(m1 = chime_stats_control_itt$b_chime_sum_mean, 
            m2 = chime_stats_control_itt$f_chime_sum_mean, 
            sd1 = chime_stats_control_itt$b_chime_sum_sd, 
            sd2 = chime_stats_control_itt$f_chime_sum_sd, 
            n = chime_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_chime_itt_2 <- d.dep.t.diff(mdiff = chime_stats_intervention_itt$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_intervention_itt$chime_sum_change_pre_followup_sd,
             n = chime_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_chime_itt_2 <- d.dep.t.diff(mdiff = chime_stats_control_itt$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_control_itt$chime_sum_change_pre_followup_sd,
             n = chime_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_chime_itt_2 <- d.ind.t(m1 = chime_stats_intervention_itt$chime_sum_change_pre_followup_mean,  
        m2 = chime_stats_control_itt$chime_sum_change_pre_followup_mean,  
        sd1 = chime_stats_intervention_itt$chime_sum_change_pre_followup_sd,  
        sd2 = chime_stats_control_itt$chime_sum_change_pre_followup_sd,  
        n1 = chime_stats_intervention_itt$n,  
        n2 = chime_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Depression symptoms descriptives

##Descriptives for intervention
mfq_stats_intervention_itt <- df_randomized_imputed_intervention %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mfq_stats_control_itt <- df_randomized_imputed_control %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Depression symptoms pre-followup

##within-person d(av) for intervention
dav_intervention_mfq_itt <- d.dep.t.avg(m1 = mfq_stats_intervention_itt$b_mfq_sum_mean, 
            m2 = mfq_stats_intervention_itt$f_mfq_sum_mean, 
            sd1 = mfq_stats_intervention_itt$b_mfq_sum_sd, 
            sd2 = mfq_stats_intervention_itt$f_mfq_sum_sd, 
            n = mfq_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_mfq_itt <- d.dep.t.avg(m1 = mfq_stats_control_itt$b_mfq_sum_mean, 
            m2 = mfq_stats_control_itt$f_mfq_sum_mean, 
            sd1 = mfq_stats_control_itt$b_mfq_sum_sd, 
            sd2 = mfq_stats_control_itt$f_mfq_sum_sd, 
            n = mfq_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_mfq_itt <- d.dep.t.diff(mdiff = mfq_stats_intervention_itt$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_intervention_itt$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_mfq_itt <- d.dep.t.diff(mdiff = mfq_stats_control_itt$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_control_itt$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_mfq_itt <- d.ind.t(m1 = mfq_stats_intervention_itt$mfq_sum_change_pre_followup_mean,  
        m2 = mfq_stats_control_itt$mfq_sum_change_pre_followup_mean,  
        sd1 = mfq_stats_intervention_itt$mfq_sum_change_pre_followup_sd,  
        sd2 = mfq_stats_control_itt$mfq_sum_change_pre_followup_sd,  
        n1 = mfq_stats_intervention_itt$n,  
        n2 = mfq_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Eating disorder symptoms descriptives

##Descriptives for intervention
edeq_stats_intervention_itt <- df_randomized_imputed_intervention %>%
  select(b_edeq_global, f_edeq_global) %>%
  mutate(edeq_global_change_pre_followup = f_edeq_global - b_edeq_global) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
edeq_stats_control_itt <- df_randomized_imputed_control %>%
  select(b_edeq_global, f_edeq_global) %>%
  mutate(edeq_global_change_pre_followup = f_edeq_global - b_edeq_global) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Eating disorder symptoms pre-followup

##within-person d(av) for intervention
dav_intervention_edeq_itt <- d.dep.t.avg(m1 = edeq_stats_intervention_itt$b_edeq_global_mean, 
            m2 = edeq_stats_intervention_itt$f_edeq_global_mean, 
            sd1 = edeq_stats_intervention_itt$b_edeq_global_sd, 
            sd2 = edeq_stats_intervention_itt$f_edeq_global_sd, 
            n = edeq_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_edeq_itt <- d.dep.t.avg(m1 = edeq_stats_control_itt$b_edeq_global_mean, 
            m2 = edeq_stats_control_itt$f_edeq_global_mean, 
            sd1 = edeq_stats_control_itt$b_edeq_global_sd, 
            sd2 = edeq_stats_control_itt$f_edeq_global_sd, 
            n = edeq_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_edeq_itt <- d.dep.t.diff(mdiff = edeq_stats_intervention_itt$edeq_global_change_pre_followup_mean,
             sddiff = edeq_stats_intervention_itt$edeq_global_change_pre_followup_sd,
             n = edeq_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_edeq_itt <- d.dep.t.diff(mdiff = edeq_stats_control_itt$edeq_global_change_pre_followup_mean,
             sddiff = edeq_stats_control_itt$edeq_global_change_pre_followup_sd,
             n = edeq_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_edeq_itt <- d.ind.t(m1 = edeq_stats_intervention_itt$edeq_global_change_pre_followup_mean,  
        m2 = edeq_stats_control_itt$edeq_global_change_pre_followup_mean,  
        sd1 = edeq_stats_intervention_itt$edeq_global_change_pre_followup_sd,  
        sd2 = edeq_stats_control_itt$edeq_global_change_pre_followup_sd,  
        n1 = edeq_stats_intervention_itt$n,  
        n2 = edeq_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")

#Muscle dysmorphia symptoms descriptives

##Descriptives for intervention
mddi_stats_intervention_itt <- df_randomized_imputed_intervention %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mddi_stats_control_itt <- df_randomized_imputed_control %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Muscle dysmorphia symptoms pre-followup

##within-person d(av) for intervention
dav_intervention_mddi_itt <- d.dep.t.avg(m1 = mddi_stats_intervention_itt$b_mddi_sum_mean, 
            m2 = mddi_stats_intervention_itt$f_mddi_sum_mean, 
            sd1 = mddi_stats_intervention_itt$b_mddi_sum_sd, 
            sd2 = mddi_stats_intervention_itt$f_mddi_sum_sd, 
            n = mddi_stats_intervention_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_mddi_itt <- d.dep.t.avg(m1 = mddi_stats_control_itt$b_mddi_sum_mean, 
            m2 = mddi_stats_control_itt$f_mddi_sum_mean, 
            sd1 = mddi_stats_control_itt$b_mddi_sum_sd, 
            sd2 = mddi_stats_control_itt$f_mddi_sum_sd, 
            n = mddi_stats_control_itt$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_mddi_itt <- d.dep.t.diff(mdiff = mddi_stats_intervention_itt$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_intervention_itt$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_intervention_itt$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_mddi_itt <- d.dep.t.diff(mdiff = mddi_stats_control_itt$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_control_itt$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_control_itt$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_mddi_itt <- d.ind.t(m1 = mddi_stats_intervention_itt$mddi_sum_change_pre_followup_mean,  
        m2 = mddi_stats_control_itt$mddi_sum_change_pre_followup_mean,  
        sd1 = mddi_stats_intervention_itt$mddi_sum_change_pre_followup_sd,  
        sd2 = mddi_stats_control_itt$mddi_sum_change_pre_followup_sd,  
        n1 = mddi_stats_intervention_itt$n,  
        n2 = mddi_stats_control_itt$n,  
        a = 0.05) %>%
  pluck("estimate")
```

```{r effect-sizes-TOT}
#Make new dataframes to separate Intervention and Control folks (with imputed data)
df_completer_baseline_imputed_intervention <- df_completer_baseline_imputed %>% 
  filter(treatment_group == "Intervention")

df_completer_baseline_imputed_control <- df_completer_baseline_imputed %>% 
  filter(treatment_group == "Control")

#Hopelessness descriptives

##Descriptives for intervention
bhs_stats_intervention_tot <- df_completer_baseline_imputed_intervention %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
bhs_stats_control_tot <- df_completer_baseline_imputed_control %>%
  select(b_bhs_sum,  pi_bhs_sum, f_bhs_sum) %>%
  mutate(bhs_sum_change_pre_post = pi_bhs_sum - b_bhs_sum,
         bhs_sum_change_pre_followup = f_bhs_sum - b_bhs_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Hopelessness pre-post

##within-in person d(av) for intervention
dav_intervention_bhs_tot_1 <- d.dep.t.avg(m1 = bhs_stats_intervention_tot$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_tot$pi_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_tot$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_tot$pi_bhs_sum_sd, 
            n = bhs_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_bhs_tot_1 <- d.dep.t.avg(m1 = bhs_stats_control_tot$b_bhs_sum_mean, 
            m2 = bhs_stats_control_tot$pi_bhs_sum_mean, 
            sd1 = bhs_stats_control_tot$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_tot$pi_bhs_sum_sd, 
            n = bhs_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_bhs_tot_1 <- d.dep.t.diff(mdiff = bhs_stats_intervention_tot$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_intervention_tot$bhs_sum_change_pre_post_sd,
             n = bhs_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_bhs_tot_1 <- d.dep.t.diff(mdiff = bhs_stats_control_tot$bhs_sum_change_pre_post_mean,
             sddiff = bhs_stats_control_tot$bhs_sum_change_pre_post_sd,
             n = bhs_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_bhs_tot_1 <- d.ind.t(m1 = bhs_stats_intervention_tot$bhs_sum_change_pre_post_mean,  
        m2 = bhs_stats_control_tot$bhs_sum_change_pre_post_mean,  
        sd1 = bhs_stats_intervention_tot$bhs_sum_change_pre_post_sd,  
        sd2 = bhs_stats_control_tot$bhs_sum_change_pre_post_sd,  
        n1 = bhs_stats_intervention_tot$n,  
        n2 = bhs_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Hopelessness pre-followup

##within-person d(av) for intervention
dav_intervention_bhs_tot_2 <- d.dep.t.avg(m1 = bhs_stats_intervention_tot$b_bhs_sum_mean, 
            m2 = bhs_stats_intervention_tot$f_bhs_sum_mean, 
            sd1 = bhs_stats_intervention_tot$b_bhs_sum_sd, 
            sd2 = bhs_stats_intervention_tot$f_bhs_sum_sd, 
            n = bhs_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_bhs_tot_2 <- d.dep.t.avg(m1 = bhs_stats_control_tot$b_bhs_sum_mean, 
            m2 = bhs_stats_control_tot$f_bhs_sum_mean, 
            sd1 = bhs_stats_control_tot$b_bhs_sum_sd, 
            sd2 = bhs_stats_control_tot$f_bhs_sum_sd, 
            n = bhs_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_bhs_tot_2 <- d.dep.t.diff(mdiff = bhs_stats_intervention_tot$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_intervention_tot$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_bhs_tot_2 <- d.dep.t.diff(mdiff = bhs_stats_control_tot$bhs_sum_change_pre_followup_mean,
             sddiff = bhs_stats_control_tot$bhs_sum_change_pre_followup_sd,
             n = bhs_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_bhs_tot_2 <- d.ind.t(m1 = bhs_stats_intervention_tot$bhs_sum_change_pre_followup_mean,  
        m2 = bhs_stats_control_tot$bhs_sum_change_pre_followup_mean,  
        sd1 = bhs_stats_intervention_tot$bhs_sum_change_pre_followup_sd,  
        sd2 = bhs_stats_control_tot$bhs_sum_change_pre_followup_sd,  
        n1 = bhs_stats_intervention_tot$n,  
        n2 = bhs_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency descriptives

##Descriptives for intervention
shs_agency_stats_intervention_tot <- df_completer_baseline_imputed_intervention %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
shs_agency_stats_control_tot <- df_completer_baseline_imputed_control %>%
  select(b_shs_agency_sum,  pi_shs_agency_sum, f_shs_agency_sum) %>%
  mutate(shs_agency_sum_change_pre_post = pi_shs_agency_sum - b_shs_agency_sum,
         shs_agency_sum_change_pre_followup = f_shs_agency_sum - b_shs_agency_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Agency pre-post

##within-in person d(av) for intervention
dav_intervention_shs_agency_tot_1 <- d.dep.t.avg(m1 = shs_agency_stats_intervention_tot$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_tot$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_tot$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_tot$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_shs_agency_tot_1 <- d.dep.t.avg(m1 = shs_agency_stats_control_tot$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_tot$pi_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_tot$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_tot$pi_shs_agency_sum_sd, 
            n = shs_agency_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_shs_agency_tot_1 <- d.dep.t.diff(mdiff = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_shs_agency_tot_1 <- d.dep.t.diff(mdiff = shs_agency_stats_control_tot$shs_agency_sum_change_pre_post_mean,
             sddiff = shs_agency_stats_control_tot$shs_agency_sum_change_pre_post_sd,
             n = shs_agency_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_shs_agency_tot_1 <- d.ind.t(m1 = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_post_mean,  
        m2 = shs_agency_stats_control_tot$shs_agency_sum_change_pre_post_mean,  
        sd1 = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_post_sd,  
        sd2 = shs_agency_stats_control_tot$shs_agency_sum_change_pre_post_sd,  
        n1 = shs_agency_stats_intervention_tot$n,  
        n2 = shs_agency_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Agency pre-followup

##within-person d(av) for intervention
dav_intervention_shs_agency_tot_2 <- d.dep.t.avg(m1 = shs_agency_stats_intervention_tot$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_intervention_tot$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_intervention_tot$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_intervention_tot$f_shs_agency_sum_sd, 
            n = shs_agency_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_shs_agency_tot_2 <- d.dep.t.avg(m1 = shs_agency_stats_control_tot$b_shs_agency_sum_mean, 
            m2 = shs_agency_stats_control_tot$f_shs_agency_sum_mean, 
            sd1 = shs_agency_stats_control_tot$b_shs_agency_sum_sd, 
            sd2 = shs_agency_stats_control_tot$f_shs_agency_sum_sd, 
            n = shs_agency_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_shs_agency_tot_2 <-  d.dep.t.diff(mdiff = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_shs_agency_tot_2 <- d.dep.t.diff(mdiff = shs_agency_stats_control_tot$shs_agency_sum_change_pre_followup_mean,
             sddiff = shs_agency_stats_control_tot$shs_agency_sum_change_pre_followup_sd,
             n = shs_agency_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_shs_agency_tot_2 <- d.ind.t(m1 = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_followup_mean,  
        m2 = shs_agency_stats_control_tot$shs_agency_sum_change_pre_followup_mean,  
        sd1 = shs_agency_stats_intervention_tot$shs_agency_sum_change_pre_followup_sd,  
        sd2 = shs_agency_stats_control_tot$shs_agency_sum_change_pre_followup_sd,  
        n1 = shs_agency_stats_intervention_tot$n,  
        n2 = shs_agency_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state descriptives

##Descriptives for intervention
biss_stats_intervention_tot <- df_completer_baseline_imputed_intervention %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biss_stats_control_tot <- df_completer_baseline_imputed_control %>%
  select(b_biss_sum,  pi_biss_sum, f_biss_sum) %>%
  mutate(biss_sum_change_pre_post = pi_biss_sum - b_biss_sum,
         biss_sum_change_pre_followup = f_biss_sum - b_biss_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image state pre-post

##within-in person d(av) for intervention
dav_intervention_biss_tot_1 <- d.dep.t.avg(m1 = biss_stats_intervention_tot$b_biss_sum_mean, 
            m2 = biss_stats_intervention_tot$pi_biss_sum_mean, 
            sd1 = biss_stats_intervention_tot$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_tot$pi_biss_sum_sd, 
            n = biss_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_biss_tot_1 <- d.dep.t.avg(m1 = biss_stats_control_tot$b_biss_sum_mean, 
            m2 = biss_stats_control_tot$pi_biss_sum_mean, 
            sd1 = biss_stats_control_tot$b_biss_sum_sd, 
            sd2 = biss_stats_control_tot$pi_biss_sum_sd, 
            n = biss_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_biss_tot_1 <- d.dep.t.diff(mdiff = biss_stats_intervention_tot$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_intervention_tot$biss_sum_change_pre_post_sd,
             n = biss_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_biss_tot_1 <- d.dep.t.diff(mdiff = biss_stats_control_tot$biss_sum_change_pre_post_mean,
             sddiff = biss_stats_control_tot$biss_sum_change_pre_post_sd,
             n = biss_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_biss_tot_1 <- d.ind.t(m1 = biss_stats_intervention_tot$biss_sum_change_pre_post_mean,  
        m2 = biss_stats_control_tot$biss_sum_change_pre_post_mean,  
        sd1 = biss_stats_intervention_tot$biss_sum_change_pre_post_sd,  
        sd2 = biss_stats_control_tot$biss_sum_change_pre_post_sd,  
        n1 = biss_stats_intervention_tot$n,  
        n2 = biss_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image state pre-followup

##within-person d(av) for intervention
dav_intervention_biss_tot_2 <- d.dep.t.avg(m1 = biss_stats_intervention_tot$b_biss_sum_mean, 
            m2 = biss_stats_intervention_tot$f_biss_sum_mean, 
            sd1 = biss_stats_intervention_tot$b_biss_sum_sd, 
            sd2 = biss_stats_intervention_tot$f_biss_sum_sd, 
            n = biss_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_biss_tot_2 <- d.dep.t.avg(m1 = biss_stats_control_tot$b_biss_sum_mean, 
            m2 = biss_stats_control_tot$f_biss_sum_mean, 
            sd1 = biss_stats_control_tot$b_biss_sum_sd, 
            sd2 = biss_stats_control_tot$f_biss_sum_sd, 
            n = biss_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_biss_tot_2 <- d.dep.t.diff(mdiff = biss_stats_intervention_tot$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_intervention_tot$biss_sum_change_pre_followup_sd,
             n = biss_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_biss_tot_2 <- d.dep.t.diff(mdiff = biss_stats_control_tot$biss_sum_change_pre_followup_mean,
             sddiff = biss_stats_control_tot$biss_sum_change_pre_followup_sd,
             n = biss_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_biss_tot_2 <- d.ind.t(m1 = biss_stats_intervention_tot$biss_sum_change_pre_followup_mean,  
        m2 = biss_stats_control_tot$biss_sum_change_pre_followup_mean,  
        sd1 = biss_stats_intervention_tot$biss_sum_change_pre_followup_sd,  
        sd2 = biss_stats_control_tot$biss_sum_change_pre_followup_sd,  
        n1 = biss_stats_intervention_tot$n,  
        n2 = biss_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")   
  
#Functionality appreciation descriptives

##Descriptives for intervention
fas_stats_intervention_tot <- df_completer_baseline_imputed_intervention %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
fas_stats_control_tot <- df_completer_baseline_imputed_control %>%
  select(b_fas_sum,  pi_fas_sum, f_fas_sum) %>%
  mutate(fas_sum_change_pre_post = pi_fas_sum - b_fas_sum,
         fas_sum_change_pre_followup = f_fas_sum - b_fas_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Functionality appreciation pre-post

##within-in person d(av) for intervention
dav_intervention_fas_tot_1 <- d.dep.t.avg(m1 = fas_stats_intervention_tot$b_fas_sum_mean, 
            m2 = fas_stats_intervention_tot$pi_fas_sum_mean, 
            sd1 = fas_stats_intervention_tot$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_tot$pi_fas_sum_sd, 
            n = fas_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_fas_tot_1 <- d.dep.t.avg(m1 = fas_stats_control_tot$b_fas_sum_mean, 
            m2 = fas_stats_control_tot$pi_fas_sum_mean, 
            sd1 = fas_stats_control_tot$b_fas_sum_sd, 
            sd2 = fas_stats_control_tot$pi_fas_sum_sd, 
            n = fas_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_fas_tot_1 <- d.dep.t.diff(mdiff = fas_stats_intervention_tot$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_intervention_tot$fas_sum_change_pre_post_sd,
             n = fas_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_fas_tot_1 <- d.dep.t.diff(mdiff = fas_stats_control_tot$fas_sum_change_pre_post_mean,
             sddiff = fas_stats_control_tot$fas_sum_change_pre_post_sd,
             n = fas_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_fas_tot_1 <- d.ind.t(m1 = fas_stats_intervention_tot$fas_sum_change_pre_post_mean,  
        m2 = fas_stats_control_tot$fas_sum_change_pre_post_mean,  
        sd1 = fas_stats_intervention_tot$fas_sum_change_pre_post_sd,  
        sd2 = fas_stats_control_tot$fas_sum_change_pre_post_sd,  
        n1 = fas_stats_intervention_tot$n,  
        n2 = fas_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Functionality appreciation pre-followup

##within-person d(av) for intervention
dav_intervention_fas_tot_2 <- d.dep.t.avg(m1 = fas_stats_intervention_tot$b_fas_sum_mean, 
            m2 = fas_stats_intervention_tot$f_fas_sum_mean, 
            sd1 = fas_stats_intervention_tot$b_fas_sum_sd, 
            sd2 = fas_stats_intervention_tot$f_fas_sum_sd, 
            n = fas_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_fas_tot_2 <- d.dep.t.avg(m1 = fas_stats_control_tot$b_fas_sum_mean, 
            m2 = fas_stats_control_tot$f_fas_sum_mean, 
            sd1 = fas_stats_control_tot$b_fas_sum_sd, 
            sd2 = fas_stats_control_tot$f_fas_sum_sd, 
            n = fas_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_fas_tot_2 <- d.dep.t.diff(mdiff = fas_stats_intervention_tot$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_intervention_tot$fas_sum_change_pre_followup_sd,
             n = fas_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_fas_tot_2 <- d.dep.t.diff(mdiff = fas_stats_control_tot$fas_sum_change_pre_followup_mean,
             sddiff = fas_stats_control_tot$fas_sum_change_pre_followup_sd,
             n = fas_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_fas_tot_2 <- d.ind.t(m1 = fas_stats_intervention_tot$fas_sum_change_pre_followup_mean,  
        m2 = fas_stats_control_tot$fas_sum_change_pre_followup_mean,  
        sd1 = fas_stats_intervention_tot$fas_sum_change_pre_followup_sd,  
        sd2 = fas_stats_control_tot$fas_sum_change_pre_followup_sd,  
        n1 = fas_stats_intervention_tot$n,  
        n2 = fas_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Body image flexibility descriptives

##Descriptives for intervention
biaaq_stats_intervention_tot <- df_completer_baseline_imputed_intervention %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
biaaq_stats_control_tot <- df_completer_baseline_imputed_control %>%
  select(b_biaaq_sum,  pi_biaaq_sum, f_biaaq_sum) %>%
  mutate(biaaq_sum_change_pre_post = pi_biaaq_sum - b_biaaq_sum,
         biaaq_sum_change_pre_followup = f_biaaq_sum - b_biaaq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body image flexibility pre-post

##within-in person d(av) for intervention
dav_intervention_biaaq_tot_1 <- d.dep.t.avg(m1 = biaaq_stats_intervention_tot$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_tot$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_tot$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_tot$pi_biaaq_sum_sd, 
            n = biaaq_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_biaaq_tot_1 <- d.dep.t.avg(m1 = biaaq_stats_control_tot$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_tot$pi_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_tot$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_tot$pi_biaaq_sum_sd, 
            n = biaaq_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_biaaq_tot_1 <- d.dep.t.diff(mdiff = biaaq_stats_intervention_tot$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_intervention_tot$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_biaaq_tot_1 <- d.dep.t.diff(mdiff = biaaq_stats_control_tot$biaaq_sum_change_pre_post_mean,
             sddiff = biaaq_stats_control_tot$biaaq_sum_change_pre_post_sd,
             n = biaaq_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_biaaq_tot_1 <- d.ind.t(m1 = biaaq_stats_intervention_tot$biaaq_sum_change_pre_post_mean,  
        m2 = biaaq_stats_control_tot$biaaq_sum_change_pre_post_mean,  
        sd1 = biaaq_stats_intervention_tot$biaaq_sum_change_pre_post_sd,  
        sd2 = biaaq_stats_control_tot$biaaq_sum_change_pre_post_sd,  
        n1 = biaaq_stats_intervention_tot$n,  
        n2 = biaaq_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body image flexibility pre-followup

##within-person d(av) for intervention
dav_intervention_biaaq_tot_2 <- d.dep.t.avg(m1 = biaaq_stats_intervention_tot$b_biaaq_sum_mean, 
            m2 = biaaq_stats_intervention_tot$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_intervention_tot$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_intervention_tot$f_biaaq_sum_sd, 
            n = biaaq_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_biaaq_tot_2 <- d.dep.t.avg(m1 = biaaq_stats_control_tot$b_biaaq_sum_mean, 
            m2 = biaaq_stats_control_tot$f_biaaq_sum_mean, 
            sd1 = biaaq_stats_control_tot$b_biaaq_sum_sd, 
            sd2 = biaaq_stats_control_tot$f_biaaq_sum_sd, 
            n = biaaq_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_biaaq_tot_2 <- d.dep.t.diff(mdiff = biaaq_stats_intervention_tot$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_intervention_tot$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_biaaq_tot_2 <- d.dep.t.diff(mdiff = biaaq_stats_control_tot$biaaq_sum_change_pre_followup_mean,
             sddiff = biaaq_stats_control_tot$biaaq_sum_change_pre_followup_sd,
             n = biaaq_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_biaaq_tot_2 <- d.ind.t(m1 = biaaq_stats_intervention_tot$biaaq_sum_change_pre_followup_mean,  
        m2 = biaaq_stats_control_tot$biaaq_sum_change_pre_followup_mean,  
        sd1 = biaaq_stats_intervention_tot$biaaq_sum_change_pre_followup_sd,  
        sd2 = biaaq_stats_control_tot$biaaq_sum_change_pre_followup_sd,  
        n1 = biaaq_stats_intervention_tot$n,  
        n2 = biaaq_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness descriptives

##Descriptives for intervention
chime_stats_intervention_tot <- df_completer_baseline_imputed_intervention %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
chime_stats_control_tot <- df_completer_baseline_imputed_control %>%
  select(b_chime_sum,  pi_chime_sum, f_chime_sum) %>%
  mutate(chime_sum_change_pre_post = pi_chime_sum - b_chime_sum,
         chime_sum_change_pre_followup = f_chime_sum - b_chime_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Body-related mindfulness pre-post

##within-in person d(av) for intervention
dav_intervention_chime_tot_1 <- d.dep.t.avg(m1 = chime_stats_intervention_tot$b_chime_sum_mean, 
            m2 = chime_stats_intervention_tot$pi_chime_sum_mean, 
            sd1 = chime_stats_intervention_tot$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_tot$pi_chime_sum_sd, 
            n = chime_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_chime_tot_1 <- d.dep.t.avg(m1 = chime_stats_control_tot$b_chime_sum_mean, 
            m2 = chime_stats_control_tot$pi_chime_sum_mean, 
            sd1 = chime_stats_control_tot$b_chime_sum_sd, 
            sd2 = chime_stats_control_tot$pi_chime_sum_sd, 
            n = chime_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_chime_tot_1 <- d.dep.t.diff(mdiff = chime_stats_intervention_tot$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_intervention_tot$chime_sum_change_pre_post_sd,
             n = chime_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_chime_tot_1 <- d.dep.t.diff(mdiff = chime_stats_control_tot$chime_sum_change_pre_post_mean,
             sddiff = chime_stats_control_tot$chime_sum_change_pre_post_sd,
             n = chime_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_chime_tot_1 <- d.ind.t(m1 = chime_stats_intervention_tot$chime_sum_change_pre_post_mean,  
        m2 = chime_stats_control_tot$chime_sum_change_pre_post_mean,  
        sd1 = chime_stats_intervention_tot$chime_sum_change_pre_post_sd,  
        sd2 = chime_stats_control_tot$chime_sum_change_pre_post_sd,  
        n1 = chime_stats_intervention_tot$n,  
        n2 = chime_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Body-related mindfulness pre-followup

##within-person d(av) for intervention
dav_intervention_chime_tot_2 <- d.dep.t.avg(m1 = chime_stats_intervention_tot$b_chime_sum_mean, 
            m2 = chime_stats_intervention_tot$f_chime_sum_mean, 
            sd1 = chime_stats_intervention_tot$b_chime_sum_sd, 
            sd2 = chime_stats_intervention_tot$f_chime_sum_sd, 
            n = chime_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_chime_tot_2 <- d.dep.t.avg(m1 = chime_stats_control_tot$b_chime_sum_mean, 
            m2 = chime_stats_control_tot$f_chime_sum_mean, 
            sd1 = chime_stats_control_tot$b_chime_sum_sd, 
            sd2 = chime_stats_control_tot$f_chime_sum_sd, 
            n = chime_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_chime_tot_2 <- d.dep.t.diff(mdiff = chime_stats_intervention_tot$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_intervention_tot$chime_sum_change_pre_followup_sd,
             n = chime_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_chime_tot_2 <- d.dep.t.diff(mdiff = chime_stats_control_tot$chime_sum_change_pre_followup_mean,
             sddiff = chime_stats_control_tot$chime_sum_change_pre_followup_sd,
             n = chime_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_chime_tot_2 <- d.ind.t(m1 = chime_stats_intervention_tot$chime_sum_change_pre_followup_mean,  
        m2 = chime_stats_control_tot$chime_sum_change_pre_followup_mean,  
        sd1 = chime_stats_intervention_tot$chime_sum_change_pre_followup_sd,  
        sd2 = chime_stats_control_tot$chime_sum_change_pre_followup_sd,  
        n1 = chime_stats_intervention_tot$n,  
        n2 = chime_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")
  
#Depression symptoms descriptives

##Descriptives for intervention
mfq_stats_intervention_tot <- df_completer_baseline_imputed_intervention %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mfq_stats_control_tot <- df_completer_baseline_imputed_control %>%
  select(b_mfq_sum, f_mfq_sum) %>%
  mutate(mfq_sum_change_pre_followup = f_mfq_sum - b_mfq_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Depression symptoms pre-followup

##within-person d(av) for intervention
dav_intervention_mfq_tot <- d.dep.t.avg(m1 = mfq_stats_intervention_tot$b_mfq_sum_mean, 
            m2 = mfq_stats_intervention_tot$f_mfq_sum_mean, 
            sd1 = mfq_stats_intervention_tot$b_mfq_sum_sd, 
            sd2 = mfq_stats_intervention_tot$f_mfq_sum_sd, 
            n = mfq_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_mfq_tot <- d.dep.t.avg(m1 = mfq_stats_control_tot$b_mfq_sum_mean, 
            m2 = mfq_stats_control_tot$f_mfq_sum_mean, 
            sd1 = mfq_stats_control_tot$b_mfq_sum_sd, 
            sd2 = mfq_stats_control_tot$f_mfq_sum_sd, 
            n = mfq_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_mfq_tot <- d.dep.t.diff(mdiff = mfq_stats_intervention_tot$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_intervention_tot$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_mfq_tot <- d.dep.t.diff(mdiff = mfq_stats_control_tot$mfq_sum_change_pre_followup_mean,
             sddiff = mfq_stats_control_tot$mfq_sum_change_pre_followup_sd,
             n = mfq_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_mfq_tot <- d.ind.t(m1 = mfq_stats_intervention_tot$mfq_sum_change_pre_followup_mean,  
        m2 = mfq_stats_control_tot$mfq_sum_change_pre_followup_mean,  
        sd1 = mfq_stats_intervention_tot$mfq_sum_change_pre_followup_sd,  
        sd2 = mfq_stats_control_tot$mfq_sum_change_pre_followup_sd,  
        n1 = mfq_stats_intervention_tot$n,  
        n2 = mfq_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Eating disorder symptoms descriptives

##Descriptives for intervention
edeq_stats_intervention_tot <- df_completer_baseline_imputed_intervention %>%
  select(b_edeq_global, f_edeq_global) %>%
  mutate(edeq_global_change_pre_followup = f_edeq_global - b_edeq_global) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
edeq_stats_control_tot <- df_completer_baseline_imputed_control %>%
  select(b_edeq_global, f_edeq_global) %>%
  mutate(edeq_global_change_pre_followup = f_edeq_global - b_edeq_global) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Eating disorder symptoms pre-followup

##within-person d(av) for intervention
dav_intervention_edeq_tot <- d.dep.t.avg(m1 = edeq_stats_intervention_tot$b_edeq_global_mean, 
            m2 = edeq_stats_intervention_tot$f_edeq_global_mean, 
            sd1 = edeq_stats_intervention_tot$b_edeq_global_sd, 
            sd2 = edeq_stats_intervention_tot$f_edeq_global_sd, 
            n = edeq_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_edeq_tot <- d.dep.t.avg(m1 = edeq_stats_control_tot$b_edeq_global_mean, 
            m2 = edeq_stats_control_tot$f_edeq_global_mean, 
            sd1 = edeq_stats_control_tot$b_edeq_global_sd, 
            sd2 = edeq_stats_control_tot$f_edeq_global_sd, 
            n = edeq_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_edeq_tot <- d.dep.t.diff(mdiff = edeq_stats_intervention_tot$edeq_global_change_pre_followup_mean,
             sddiff = edeq_stats_intervention_tot$edeq_global_change_pre_followup_sd,
             n = edeq_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_edeq_tot <- d.dep.t.diff(mdiff = edeq_stats_control_tot$edeq_global_change_pre_followup_mean,
             sddiff = edeq_stats_control_tot$edeq_global_change_pre_followup_sd,
             n = edeq_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_edeq_tot <- d.ind.t(m1 = edeq_stats_intervention_tot$edeq_global_change_pre_followup_mean,  
        m2 = edeq_stats_control_tot$edeq_global_change_pre_followup_mean,  
        sd1 = edeq_stats_intervention_tot$edeq_global_change_pre_followup_sd,  
        sd2 = edeq_stats_control_tot$edeq_global_change_pre_followup_sd,  
        n1 = edeq_stats_intervention_tot$n,  
        n2 = edeq_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")

#Muscle dysmorphia symptoms descriptives

##Descriptives for intervention
mddi_stats_intervention_tot <- df_completer_baseline_imputed_intervention %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

##Descriptives for control
mddi_stats_control_tot <- df_completer_baseline_imputed_control %>%
  select(b_mddi_sum, f_mddi_sum) %>%
  mutate(mddi_sum_change_pre_followup = f_mddi_sum - b_mddi_sum) %>%
  summarize(n = n(), 
            across(everything(),  list(mean = mean,  sd = sd))) 

#Muscle dysmorphia symptoms pre-followup

##within-person d(av) for intervention
dav_intervention_mddi_tot <- d.dep.t.avg(m1 = mddi_stats_intervention_tot$b_mddi_sum_mean, 
            m2 = mddi_stats_intervention_tot$f_mddi_sum_mean, 
            sd1 = mddi_stats_intervention_tot$b_mddi_sum_sd, 
            sd2 = mddi_stats_intervention_tot$f_mddi_sum_sd, 
            n = mddi_stats_intervention_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(av) for control
dav_control_mddi_tot <- d.dep.t.avg(m1 = mddi_stats_control_tot$b_mddi_sum_mean, 
            m2 = mddi_stats_control_tot$f_mddi_sum_mean, 
            sd1 = mddi_stats_control_tot$b_mddi_sum_sd, 
            sd2 = mddi_stats_control_tot$f_mddi_sum_sd, 
            n = mddi_stats_control_tot$n, 
            a = .05) %>%
  pluck("estimate")

##within-person d(z) for intervention
dz_intervention_mddi_tot <- d.dep.t.diff(mdiff = mddi_stats_intervention_tot$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_intervention_tot$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_intervention_tot$n,
             a = .05) %>%
  pluck("estimate")

##within-person d(z) for control
dz_control_mddi_tot <- d.dep.t.diff(mdiff = mddi_stats_control_tot$mddi_sum_change_pre_followup_mean,
             sddiff = mddi_stats_control_tot$mddi_sum_change_pre_followup_sd,
             n = mddi_stats_control_tot$n,
             a = .05) %>%
  pluck("estimate")

##between-group d
dbetween_mddi_tot <- d.ind.t(m1 = mddi_stats_intervention_tot$mddi_sum_change_pre_followup_mean,  
        m2 = mddi_stats_control_tot$mddi_sum_change_pre_followup_mean,  
        sd1 = mddi_stats_intervention_tot$mddi_sum_change_pre_followup_sd,  
        sd2 = mddi_stats_control_tot$mddi_sum_change_pre_followup_sd,  
        n1 = mddi_stats_intervention_tot$n,  
        n2 = mddi_stats_control_tot$n,  
        a = 0.05) %>%
  pluck("estimate")
```

```{r create-tables-for-outcomes}
#Hopelessness
bhs_itt_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_bhs_itt_1, p_value_bhs_itt_2),
  `d.av Intervention` = c(dav_intervention_bhs_itt_1, dav_intervention_bhs_itt_2),
  `d.av Control` = c(dav_control_bhs_itt_1, dav_control_bhs_itt_2),
  `d.z Intervention` = c(dz_intervention_bhs_itt_1, dz_intervention_bhs_itt_2),
  `d.z Control` = c(dz_control_bhs_itt_1, dz_control_bhs_itt_2),
  `d Between Groups` = c(dbetween_bhs_itt_1, dbetween_bhs_itt_2))
bhs_itt_table
bhs_tot_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_bhs_tot_1, p_value_bhs_tot_2),
  `d.av Intervention` = c(dav_intervention_bhs_tot_1, dav_intervention_bhs_tot_2),
  `d.av Control` = c(dav_control_bhs_tot_1, dav_control_bhs_tot_2),
  `d.z Intervention` = c(dz_intervention_bhs_tot_1, dz_intervention_bhs_tot_2),
  `d.z Control` = c(dz_control_bhs_tot_1, dz_control_bhs_tot_2),
  `d Between Groups` = c(dbetween_bhs_tot_1, dbetween_bhs_tot_2))
bhs_tot_table

#Agency
shs_agency_itt_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_shs_agency_itt_1, p_value_shs_agency_itt_2),
  `d.av Intervention` = c(dav_intervention_shs_agency_itt_1, dav_intervention_shs_agency_itt_2),
  `d.av Control` = c(dav_control_shs_agency_itt_1, dav_control_shs_agency_itt_2),
  `d.z Intervention` = c(dz_intervention_shs_agency_itt_1, dz_intervention_shs_agency_itt_2),
  `d.z Control` = c(dz_control_shs_agency_itt_1, dz_control_shs_agency_itt_2),
  `d Between Groups` = c(dbetween_shs_agency_itt_1, dbetween_shs_agency_itt_2))
shs_agency_itt_table
shs_agency_tot_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_shs_agency_tot_1, p_value_shs_agency_tot_2),
  `d.av Intervention` = c(dav_intervention_shs_agency_tot_1, dav_intervention_shs_agency_tot_2),
  `d.av Control` = c(dav_control_shs_agency_tot_1, dav_control_shs_agency_tot_2),
  `d.z Intervention` = c(dz_intervention_shs_agency_tot_1, dz_intervention_shs_agency_tot_2),
  `d.z Control` = c(dz_control_shs_agency_tot_1, dz_control_shs_agency_tot_2),
  `d Between Groups` = c(dbetween_shs_agency_tot_1, dbetween_shs_agency_tot_2))
shs_agency_tot_table

#Body image state
biss_itt_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_biss_itt_1, p_value_biss_itt_2),
  `d.av Intervention` = c(dav_intervention_biss_itt_1, dav_intervention_biss_itt_2),
  `d.av Control` = c(dav_control_biss_itt_1, dav_control_biss_itt_2),
  `d.z Intervention` = c(dz_intervention_biss_itt_1, dz_intervention_biss_itt_2),
  `d.z Control` = c(dz_control_biss_itt_1, dz_control_biss_itt_2),
  `d Between Groups` = c(dbetween_biss_itt_1, dbetween_biss_itt_2))
biss_itt_table
biss_tot_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_biss_tot_1, p_value_biss_tot_2),
  `d.av Intervention` = c(dav_intervention_biss_tot_1, dav_intervention_biss_tot_2),
  `d.av Control` = c(dav_control_biss_tot_1, dav_control_biss_tot_2),
  `d.z Intervention` = c(dz_intervention_biss_tot_1, dz_intervention_biss_tot_2),
  `d.z Control` = c(dz_control_biss_tot_1, dz_control_biss_tot_2),
  `d Between Groups` = c(dbetween_biss_tot_1, dbetween_biss_tot_2))
biss_tot_table

#Functionality appreciation
fas_itt_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_fas_itt_1, p_value_fas_itt_2),
  `d.av Intervention` = c(dav_intervention_fas_itt_1, dav_intervention_fas_itt_2),
  `d.av Control` = c(dav_control_fas_itt_1, dav_control_fas_itt_2),
  `d.z Intervention` = c(dz_intervention_fas_itt_1, dz_intervention_fas_itt_2),
  `d.z Control` = c(dz_control_fas_itt_1, dz_control_fas_itt_2),
  `d Between Groups` = c(dbetween_fas_itt_1, dbetween_fas_itt_2))
fas_itt_table
fas_tot_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_fas_tot_1, p_value_fas_tot_2),
  `d.av Intervention` = c(dav_intervention_fas_tot_1, dav_intervention_fas_tot_2),
  `d.av Control` = c(dav_control_fas_tot_1, dav_control_fas_tot_2),
  `d.z Intervention` = c(dz_intervention_fas_tot_1, dz_intervention_fas_tot_2),
  `d.z Control` = c(dz_control_fas_tot_1, dz_control_fas_tot_2),
  `d Between Groups` = c(dbetween_fas_tot_1, dbetween_fas_tot_2))
fas_tot_table

#Body image flexibility
biaaq_itt_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_biaaq_itt_1, p_value_biaaq_itt_2),
  `d.av Intervention` = c(dav_intervention_biaaq_itt_1, dav_intervention_biaaq_itt_2),
  `d.av Control` = c(dav_control_biaaq_itt_1, dav_control_biaaq_itt_2),
  `d.z Intervention` = c(dz_intervention_biaaq_itt_1, dz_intervention_biaaq_itt_2),
  `d.z Control` = c(dz_control_biaaq_itt_1, dz_control_biaaq_itt_2),
  `d Between Groups` = c(dbetween_biaaq_itt_1, dbetween_biaaq_itt_2))
biaaq_itt_table
biaaq_tot_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_biaaq_tot_1, p_value_biaaq_tot_2),
  `d.av Intervention` = c(dav_intervention_biaaq_tot_1, dav_intervention_biaaq_tot_2),
  `d.av Control` = c(dav_control_biaaq_tot_1, dav_control_biaaq_tot_2),
  `d.z Intervention` = c(dz_intervention_biaaq_tot_1, dz_intervention_biaaq_tot_2),
  `d.z Control` = c(dz_control_biaaq_tot_1, dz_control_biaaq_tot_2),
  `d Between Groups` = c(dbetween_biaaq_tot_1, dbetween_biaaq_tot_2))
biaaq_tot_table

#Body-related mindfulness
chime_itt_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_chime_itt_1, p_value_chime_itt_2),
  `d.av Intervention` = c(dav_intervention_chime_itt_1, dav_intervention_chime_itt_2),
  `d.av Control` = c(dav_control_chime_itt_1, dav_control_chime_itt_2),
  `d.z Intervention` = c(dz_intervention_chime_itt_1, dz_intervention_chime_itt_2),
  `d.z Control` = c(dz_control_chime_itt_1, dz_control_chime_itt_2),
  `d Between Groups` = c(dbetween_chime_itt_1, dbetween_chime_itt_2))
chime_itt_table
chime_tot_table <- data.frame(
  `Phase` = c("Pre to Post", "Pre to Follow-up"),
  `p-Value` = c(p_value_chime_tot_1, p_value_chime_tot_2),
  `d.av Intervention` = c(dav_intervention_chime_tot_1, dav_intervention_chime_tot_2),
  `d.av Control` = c(dav_control_chime_tot_1, dav_control_chime_tot_2),
  `d.z Intervention` = c(dz_intervention_chime_tot_1, dz_intervention_chime_tot_2),
  `d.z Control` = c(dz_control_chime_tot_1, dz_control_chime_tot_2),
  `d Between Groups` = c(dbetween_chime_tot_1, dbetween_chime_tot_2))
chime_tot_table

#Depression symptoms
mfq_itt_table <- data.frame(
  `Phase` = "Pre to Post",
  `p-Value` = p_value_mfq_itt,
  `d.av Intervention` = dav_intervention_mfq_itt,
  `d.av Control` = dav_control_mfq_itt,
  `d.z Intervention` = dz_intervention_mfq_itt,
  `d.z Control` = dz_control_mfq_itt,
  `d Between Groups` = dbetween_mfq_itt)
mfq_itt_table
mfq_tot_table <- data.frame(
  `Phase` = "Pre to Post",
  `p-Value` = p_value_mfq_tot,
  `d.av Intervention` = dav_intervention_mfq_tot,
  `d.av Control` = dav_control_mfq_tot,
  `d.z Intervention` = dz_intervention_mfq_tot,
  `d.z Control` = dz_control_mfq_tot,
  `d Between Groups` = dbetween_mfq_tot)
mfq_tot_table

#Eating disorder symptoms
edeq_itt_table <- data.frame(
  `Phase` = "Pre to Post",
  `p-Value` = p_value_edeq_itt,
  `d.av Intervention` = dav_intervention_edeq_itt,
  `d.av Control` = dav_control_edeq_itt,
  `d.z Intervention` = dz_intervention_edeq_itt,
  `d.z Control` = dz_control_edeq_itt,
  `d Between Groups` = dbetween_edeq_itt)
edeq_itt_table
edeq_tot_table <- data.frame(
  `Phase` = "Pre to Post",
  `p-Value` = p_value_edeq_tot,
  `d.av Intervention` = dav_intervention_edeq_tot,
  `d.av Control` = dav_control_edeq_tot,
  `d.z Intervention` = dz_intervention_edeq_tot,
  `d.z Control` = dz_control_edeq_tot,
  `d Between Groups` = dbetween_edeq_tot)
edeq_tot_table

#Muscle dysmorphia symptoms
mddi_itt_table <- data.frame(
  `Phase` = "Pre to Post",
  `p-Value` = p_value_mddi_itt,
  `d.av Intervention` = dav_intervention_mddi_itt,
  `d.av Control` = dav_control_mddi_itt,
  `d.z Intervention` = dz_intervention_mddi_itt,
  `d.z Control` = dz_control_mddi_itt,
  `d Between Groups` = dbetween_mddi_itt)
mddi_itt_table
mddi_tot_table <- data.frame(
  `Phase` = "Pre to Post",
  `p-Value` = p_value_mddi_tot,
  `d.av Intervention` = dav_intervention_mddi_tot,
  `d.av Control` = dav_control_mddi_tot,
  `d.z Intervention` = dz_intervention_mddi_tot,
  `d.z Control` = dz_control_mddi_tot,
  `d Between Groups` = dbetween_mddi_tot)
mddi_tot_table
```

```{r acceptability}
#New dataframes to seperate intervention and control participants
df_completer_pfs_nonimputed_intervention <- df_completer_pfs_nonimputed %>% 
  filter(treatment_group == "Intervention")

df_completer_pfs_nonimputed_control <- df_completer_pfs_nonimputed %>% 
  filter(treatment_group == "Control")

#Check if there are differences in total PFS
t.test(df_completer_pfs_nonimputed_intervention$pi_pfs_sum,  df_completer_pfs_nonimputed_control$pi_pfs_sum)
#Significant differences in favor of PBN

#Overall score for intervention participants
df_completer_pfs_nonimputed_intervention %>%
    summarize(mean = mean(pi_pfs_sum), 
              sd = sd(pi_pfs_sum))

#Overall score for control participants
df_completer_pfs_nonimputed_control %>%
    summarize(mean = mean(pi_pfs_sum), 
              sd = sd(pi_pfs_sum))

#Individual items for intervention participants
df_completer_pfs_nonimputed_intervention %>%
  select(pi_pfs_1:pi_pfs_7) %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  summarize(mean = mean(value), 
            sd = sd(value))

#Individual items for control participants
df_completer_pfs_nonimputed_control %>%
  select(pi_pfs_1:pi_pfs_7) %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  summarize(mean = mean(value), 
            sd = sd(value))

#N and percent of intervention participants with sum score >3 (selects Agree and Strongly Agree only),  reflect overall perceived SSI acceptability
df_completer_pfs_nonimputed_intervention %>%
  mutate(pi_pfs_sum_scores = pi_pfs_sum / 7,  
         pi_pfs_sum_scores_acceptable = pi_pfs_sum_scores > 3) %>%
  summarise(pi_pfs_sum_scores_acceptable_percent = scales::percent(mean(pi_pfs_sum_scores_acceptable)))

#N and percent of control participants with sum score >3 (selects Agree and Strongly Agree only),  reflect overall perceived SSI acceptability
df_completer_pfs_nonimputed_control %>%
  mutate(pi_pfs_sum_scores = pi_pfs_sum / 7,  
         pi_pfs_sum_scores_acceptable = pi_pfs_sum_scores > 3) %>%
  summarise(pi_pfs_sum_scores_acceptable_percent = scales::percent(mean(pi_pfs_sum_scores_acceptable)))
```

```{r demographics}
#Sex assigned at birth
imputation_ready_with_IDs %>%
  count(b_dem_sex) %>%
  mutate(percent = (n / sum(n))*100)

#Sexual orientation
imputation_ready_with_IDs %>%
  count(b_dem_sexuality) %>%
  mutate(percent = (n / sum(n))*100)

#Age
imputation_ready_with_IDs %>% 
  count(b_dem_age) %>% 
  mutate(percent = (n / sum(n))*100)

#Gender
#imputation_ready_with_IDs %>%
#  select(starts_with("b_dem_gender")) %>%
#  summarize(across(everything(), #The line defines a function where x represents a column. List is used because there are two functions (n and %).
#                   list(n = function(x) sum(x == 1), #Counts occurrences of 1 within the column x
#                        percent = function(x) mean(x == 1) * 100))) #Calculates the percentages of 1s in the column x by calculating the proportion where the value of x is 1, and multiplying it by 100
#The concise, tidyverse version of the above would be:
imputation_ready_with_IDs %>%
  select(starts_with("b_dem_gender")) %>% 
  summarize(across(everything(), 
                   list(n = ~ sum(. == 1),
                        percent = ~ mean(. == 1) * 100)))

#Race and ethnicity
imputation_ready_with_IDs %>% 
  select(starts_with("b_dem_race")) %>% 
  summarize(across(everything(),
                   list(n = ~ sum(.x == 1),
                        percent = ~ mean(. == 1))))

#We could not get the disability items approved by the IRB in time

#Food insecurity
imputation_ready_with_IDs %>%
  mutate(b_food_insecure = if_else(b_hunger_1 >= 2 | b_hunger_2 >= 2, 1, 0)) %>% 
  count(b_food_insecure) %>% 
  mutate(percent = (n / sum(n))*100)

#Access to care
#b_past_x is only displayed if b_current_x is marked "No"
#b_unmet_x_past is only displayed if b_unmet_x_now is marked "No"

##Depression and mood problems
imputation_ready_with_IDs %>% 
  select(b_current_mood, b_past_mood, b_unmet_mood_now, b_unmet_mood_past) %>% 
  summarize(across(everything(),
                   list(n = ~ sum(.x == 1, na.rm = TRUE),
                        percent = ~ mean(. == 1, na.rm = TRUE) * 100)))

##Eating disorder and body image concerns
imputation_ready_with_IDs %>% 
  select(b_current_ed, b_past_ed, b_unmet_ed_now, b_unmet_ed_past) %>% 
  summarize(across(everything(),
                   list(n = ~ sum(.x == 1, na.rm = TRUE),
                        percent = ~ mean(. == 1, na.rm = TRUE) * 100)))
```

```{r compare-3-month-treatment-seeking}
#Depression treatment seeking

#Change from numeric to factor if still numeric
if(is.numeric(df_completer_followup_nonimputed$f_new_support_mood)) {
  df_completer_followup_nonimputed <- df_completer_followup_nonimputed %>%
    mutate(f_new_support_mood = case_when(
      f_new_support_mood == 0 ~ "No",
      f_new_support_mood == 1 ~ "Yes"
    ))
}

#Make contingency table
f_new_support_mood_table <- table(df_completer_followup_nonimputed$f_new_support_mood, df_completer_followup_nonimputed$treatment_group)
f_new_support_mood_table

#Chi square
chisq.test(f_new_support_mood_table)

#Eating disorder treatment seeking

#Change from numeric to factor if still numeric
if(is.numeric(df_completer_followup_nonimputed$f_new_support_ed)) {
  df_completer_followup_nonimputed <- df_completer_followup_nonimputed %>%
    mutate(f_new_support_ed = case_when(
      f_new_support_ed == 0 ~ "No",
      f_new_support_ed == 1 ~ "Yes"
    ))
}
df_completer_followup_nonimputed$f_new_support_ed <- factor(df_completer_followup_nonimputed$f_new_support_ed, levels = c("No", "Yes"))

#Make contingency table
f_new_support_ed_table <- table(df_completer_followup_nonimputed$f_new_support_ed, df_completer_followup_nonimputed$treatment_group)
f_new_support_ed_table

#Chi square
chisq.test(f_new_support_ed_table)
```

```{r patterns-of-use}
#Completion

#Number of individuals who began the SSI, regardless of completion - intervention
missingness_handled %>% 
  filter(treatment_group == "Intervention") %>% 
  count()

#Number of individuals who completed the SSI - intervention
missingness_handled %>% 
  filter(treatment_group == "Intervention" & completer_intervention_assignment == "Completed") %>% 
  count()

#Completion of Program Feedback Scale - intervention 
missingness_handled %>% 
  filter(treatment_group == "Intervention" & completer_pfs == "Completed") %>% 
  count()

#Completion of all pre-intervention and post-intervention questionnaires - intervention
missingness_handled %>% 
  filter(treatment_group == "Intervention" & `Measures Completed.baseline` == "Measures Completed") %>% 
  count()

#Completion of all follow-up questionnaires - intervention
missingness_handled %>% 
  filter(treatment_group == "Intervention" & `Measures Completed.followup` == "Measures Completed") %>% 
  count()

#Completion of all pre-intervention, post-intervention questionnaires, and follow-up questionnaires - intervention
missingness_handled %>% 
  filter(treatment_group == "Intervention" & `Measures Completed.baseline` == "Measures Completed" & `Measures Completed.followup` == "Measures Completed") %>% 
  count()

#Number of individuals who began the SSI, regardless of completion - control
missingness_handled %>% 
  filter(treatment_group == "Control") %>% 
  count()

#Number of individuals who completed the SSI - control
missingness_handled %>% 
  filter(treatment_group == "Control" & completer_intervention_assignment == "Completed") %>% 
  count()

#Completion of Program Feedback Scale - control 
missingness_handled %>% 
  filter(treatment_group == "Control" & completer_pfs == "Completed") %>% 
  count()

#Completion of all pre-intervention and post-intervention questionnaires - control
missingness_handled %>% 
  filter(treatment_group == "Control" & `Measures Completed.baseline` == "Measures Completed") %>% 
  count()

#Completion of all follow-up questionnaires - control
missingness_handled %>% 
  filter(treatment_group == "Control" & `Measures Completed.followup` == "Measures Completed") %>% 
  count()

#Completion of all pre-intervention, post-intervention questionnaires, and follow-up questionnaires - control
missingness_handled %>% 
  filter(treatment_group == "Control" & `Measures Completed.baseline` == "Measures Completed" & `Measures Completed.followup` == "Measures Completed") %>% 
  count()

#Duration

#Since the main goal here is to see how long it took people to use the SSIs, use nonimputed data which still has "real" timing variables and select intervention assignment completers 
missingness_handled_intervention_completers <- missingness_handled %>% 
  filter(completer_intervention_assignment == "Completed")

#Extract columns with relevant timing variables
names_in_order <- missingness_handled_intervention_completers %>%
  select(ends_with("Page Submit")) %>%
  names()

#Put mean duration and sd for each page into a new data frame
page_durations <- missingness_handled_intervention_completers %>% #
  select(ends_with("Page Submit")) %>%
    mutate(across(everything(), ~ as.numeric(as.character(.)))) %>%
  pivot_longer(cols = everything(),
               names_to = "page",
               values_to = "duration") %>%
  group_by(page) %>%
  summarise(mean_duration = mean(duration, na.rm = T),
            sd_duration = sd(duration,  na.rm = T), .groups = "drop") 
page_durations

#Summarize duration for PBN
mean_sd_durations_intervention <- page_durations %>% 
  mutate(page_category = case_when(
    grepl("^bn_", page) ~ "intervention",
    TRUE ~ "other"
  )) %>%
  group_by(page_category) %>%
  summarize(mean_duration_seconds = sum(mean_duration, na.rm = TRUE), 
            sd_duration_seconds = sum(sd_duration, na.rm = TRUE), 
            .groups = "drop") %>%
  mutate(mean_duration_minutes = mean_duration_seconds / 60,
         sd_duration_minutes = sd_duration_seconds / 60)
mean_sd_durations_intervention

#Summarize duration for Control
mean_sd_durations_control <- page_durations %>% 
  mutate(page_category = case_when(
    grepl("^sf_", page) ~ "control",
    TRUE ~ "other"
  )) %>%
  group_by(page_category) %>%
  summarize(mean_duration_seconds = sum(mean_duration, na.rm = TRUE), 
            sd_duration_seconds = sum(sd_duration, na.rm = TRUE), 
            .groups = "drop") %>%
  mutate(mean_duration_minutes = mean_duration_seconds / 60,
         sd_duration_minutes = sd_duration_seconds / 60)
mean_sd_durations_control

#Now see how far those who were randomized but did not complete the SSI (a subset of the ITT sample) got through the intervention assigned

#Number of people randomized who did not finish their condition - for intervention 
missingness_handled_randomized_incomplete_intervention <- missingness_handled %>% 
  filter(completer_intervention_assignment != "Completed" & treatment_group == "Intervention")
count(missingness_handled_randomized_incomplete_intervention)

#Progress of people randomized who did not finish their condition - for intervention 
ssi_columns_randomized_incomplete_intervention <- missingness_handled_randomized_incomplete_intervention %>%
  select(starts_with("bn_"))
total_ssi_pages <- ncol(ssi_columns_randomized_incomplete_intervention)
ssi_progress_randomized_incomplete_intervention <- missingness_handled_randomized_incomplete_intervention %>%
  mutate(ssi_pages_completed = rowSums(!is.na(ssi_columns_randomized_incomplete_intervention)),
         ssi_percent_completed = (ssi_pages_completed / total_ssi_pages) * 100)
ssi_progress_randomized_incomplete_intervention %>%
  select(Participant_ID, ssi_pages_completed, ssi_percent_completed)

#Number of people randomized who did not finish their condition - for control 
missingness_handled_randomized_incomplete_control <- missingness_handled %>% 
  filter(completer_intervention_assignment != "Completed" & treatment_group == "Control")
count(missingness_handled_randomized_incomplete_control)

#Progress of people randomized who did not finish their condition - for control
ssi_columns_randomized_incomplete_control <- missingness_handled_randomized_incomplete_control %>%
  select(starts_with("sf_"))
total_ssi_pages <- ncol(ssi_columns_randomized_incomplete_control)
ssi_progress_randomized_incomplete_control <- missingness_handled_randomized_incomplete_control %>%
  mutate(ssi_pages_completed = rowSums(!is.na(ssi_columns_randomized_incomplete_control)),
         ssi_percent_completed = (ssi_pages_completed / total_ssi_pages) * 100)
ssi_progress_randomized_incomplete_control %>%
  select(Participant_ID, ssi_pages_completed, ssi_percent_completed)
```

```{r}
p.values <- runif(n = 100)
p.adjust(
  p = p.values,
  method = "BH"
)

hist(df_randomized_imputed$b_edeq_global)

lm(data = df_randomized_imputed, formula = f_edeq_global ~ b_edeq_global * treatment_group) %>% 
  summary()

df_randomized_imputed %>%
  mutate(
    edeq_threshold = b_edeq_global >= 2.3
  ) %>%
  group_by(treatment_group, edeq_threshold) %>%
  summarize(
    b_edeq_mean = mean(b_edeq_global),
    f_edeq_mean = mean(f_edeq_global),
    .groups = "drop"
  ) %>%
  pivot_longer(
    cols = c(b_edeq_mean, f_edeq_mean)
  ) %>%
  ggplot() +
  geom_point(
    aes(
      x = name,
      y = value,
      color = treatment_group,
      linetype = edeq_threshold
    )
  ) + 
  theme_classic()
```